### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor#1]
Maven is the defacto dependency management system.

Either get builds into Maven Central, or use an alternative repository such as [Sonatype](https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide).

Some old versions are already in Maven central.

(migrated from [Google Code](https://code.google.com/p/metadata-extractor/issues/detail?id=39))

**Comment by jvdb** [comment]
Could you release 2.6.4 to Maven Central? I noticed that 2.6.2 and 2.7.0 are there, but not 2.6.4. I'm trying to build a project that depends on 2.6.4 and there seem to be compatibility issues with 2.7.0 (checked exceptions).

**Comment by jvdb** [comment]
Sorry for my late response. I simply substituted 2.6.4 with 2.7.0 and got compiler errors about at least one checked exception on at least one public method in 2.7.0 that wasn't there on 2.6.4. I'll see if I can reproduce the exact error(s) shortly.

**Comment by drewnoakes** [comment]
2.7 is not 100% API compatible with earlier releases. It should be
straightforward to migrate. Please ping the mailing list if you have any
questions.
