### ISSUE TITLE
"Padding" EXIF entry

### ISSUE THREAD

**Issue by theefer** [drewnoakes/metadata-extractor#100]
The 3.8.0 now causes the extraction of a new "Padding" EXIF field that contains data such as "[4108 bytes]". Is it expected, and what does this field and value refer to?

See for instance the following image:
![getty](https://cloud.githubusercontent.com/assets/36964/7071656/7c4ce99a-dede-11e4-8d8c-c248140f6930.jpg)

**Comment by drewnoakes** [comment]
It is literally padding data and serves no useful function. It's technically a tag value, and has it's own tag ID, so metadata-extractor exposes it.

**Comment by theefer** [comment]
OK thanks, will just filter it post-extraction in that case.
