### ISSUE TITLE
webp exif can not support!

### ISSUE THREAD

**Issue by hyhhui** [drewnoakes/metadata-extractor#101]
In RiffReader class, chunkFourCC = "VP8 ", but WebpRiffHandler shouldAcceptChunk method can not accept "VP8"

**Comment by drewnoakes** [comment]
Do you have an image that reproduces this issue?

**Comment by drewnoakes** [comment]
I don't understand the issue here. Exif data is stored in chunk `EXIF`, not `VP8 `. The VP8 chunk holds compressed image data (as does VP8L) which metadata-extractor currently ignores.

I'm going to close this for now. Let me know if you think it should be reopened.
