### ISSUE TITLE
Get creation date from "arbitrary" file-types

### ISSUE THREAD

**Issue by black-snow** [drewnoakes/metadata-extractor#106]
Hi,

for my current project I have to read the creation date from **jpg, png** and possibly other file-types. The creation time from the filesystem is not sufficient for me thus I need to read that from exif etc.
**Is the example from the FAQ suited for this usecase?**

```java
Metadata metadata = ImageMetadataReader.readMetadata(file);
Directory directory = metadata.getFirstDirectoryOfType(ExifSubIFDDirectory.class);
return directory.getDate(ExifSubIFDDirectory.TAG_DATETIME_ORIGINAL);
```

This looks as if it was only suited for jpgs (and other files containing exif data). Do I have to determine the file-type myself and query the appropriate tag(s)? Or is there any simple built-in solution for this?
If it's only for "jpg-ish" files this should be mentioned in the FAQ (it says "photo" but I think it's not quite clear that this means "jpg").

**Comment by drewnoakes** [comment]
This is a good question, and a specific example of what's discussed in #10.

Indeed there are multiple potential ways of obtaining a creation time from an image. It's possible to even have multiple conflicting values.

The code you quote is only reading a single tag from the first instance of the ExifSubIFD0 directory.

I'd be interested to hear your thoughts on a strategy for extracting a single date value from whatever metadata might be available in a given image.

**Comment by black-snow** [comment]
Hi & thanks for the reply.

I'd say there's two different issues - they are somehow connected but not quite the same:

*1)* It would be nice to have some "top-level" functionality to obtain metadata that's somehow common across different file types, e. g. the creation date (is it?). I'd love to have something like `ImageReader.readMetadata(file).getCreationDate()` where file can be *jpeg*, *png*, *tiff*, *bmp*, ...

*2)* For jpeg / exif (and others I guess) there can be multiple fields that somehow map to the same semantic thing - such as the creation date (*datetime original*, *datetime digitized*, *last modification time*, ...). I must say that I'm not quite familiar with exif etc. thus I can't tell if it's actually semantically the same or not. If I got it right there can even be multiple *directories* that actually have the same "keyset" but w/ different values, right?
In that case I'd either just take the first creation time I come across or the oldest I can find. But as I said, my understanding of those meta formats is very limited.

---

To my original issue: I just wrote a custom switch. At first I try to extract *ExifSubIFDDirectory.TAG_DATETIME_ORIGINAL* from the first *ExifSubIFDDirectoy* I find (if any). If this gives me *null* I continue to search for *ExifInteropDirectory.TAG_DATETIME_ORIGINAL*, *ExifInteropDirectory.TAG_DATETIME_DIGITIZED*, *ExifInteropDirectory.TAG_DATETIME*, *PngDirectory.TAG_LAST_MODIFICATION_TIME* and if all these fail I fall back to *FileMetadataDirectory.TAG_FILE_MODIFIED_DATE*.

Are there other *Directory* types and *Tags* I should check?

**Comment by drewnoakes** [comment]
I think this is a sensible approach. Making a prioritised list of
tags/directories and accepting the first which is present.

Tags are documented in the Exif spec, but vendor implementations can vary
in places.

Please do share what you learn, as I suppose this is a common problem

[via phone]

**Comment by black-snow** [comment]
Maybe I should create another issue for this question; it seems like for **PNG** the *common* keys from the [spec](http://www.w3.org/TR/PNG/#11textinfo) are missing from *com.drew.metadata.png.PngDirectory*. Or do I have to fetch *TAG_TEXTUAL_DATA* and look for *"Creation Date"* inside?

What I learned so far is that I have to read the actual specs for the different formats. I thought I could avoid that by using your library but apparently I can't. Maybe *metadata-extractor* is just not suited for me as it's quite "feature-packed" but the only feature I actually need is geting a creation date for an arbitrary image-file (i. e. jpeg, png, ...).

I'll do some more research on how to enhance my process of retrieving a good creation date and report back.
Thank you very much for your quick replies.

**Comment by drewnoakes** [comment]
I understand your need and it's really the basis for the longstanding issue
I linked to (#10 I think, from memory).

Any software that can produce the result you're after would need to do what
metadata-extractor does. This feels like a good fit for the library, so if
you make ground in this area we can look at getting it into the repo.

I'll have to research the PNG keys you mention when online (underground
this moment).

The challenge will be dealing with inconsistencies between images. The
standards are not always followed. I don't think it'd ever be possible to
make a guaranteed statement about the date at which some event occurred,
but covering the majority correctly should be possible.

**Comment by drewnoakes** [comment]
Folding this issue into #10.
