### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by black-snow** [drewnoakes/metadata-extractor#107]
Are any proguard rules required to use metadata-extractor w/ proguard on android?

Currently with no special rules for *metadata-extractor* and *-dontobfuscate* and *-dontoptimize* in effect my app crashes w/ the following message:

> java.lang.AssertionError: impossible
at java.lang.Enum$1.create(Enum.java:45)
at java.lang.Enum$1.create(Enum.java:35)
at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
at java.lang.Enum.getSharedConstants(Enum.java:211)
at java.lang.Class.getEnumConstants(Class.java:1029)
at com.drew.imaging.jpeg.JpegSegmentType.<clinit>(JpegSegmentType.java:148)
at com.drew.metadata.jpeg.JpegReader.getSegmentTypes(JpegReader.java:45)
at com.drew.imaging.jpeg.JpegMetadataReader.process(JpegMetadataReader.java:111)
...

I'd like to see a little *Proguard* section added to the wiki as soon as we figured out if/what's necessary.

I'll play around w/ some -keep options on com.drew.** and report back.

Best regards

**Comment by drewnoakes** [comment]
I have no idea what proguard is. If you think there's something worth
documenting, feel free to write it up.

[via phone]

**Comment by black-snow** [comment]
[Proguard](http://developer.android.com/tools/help/proguard.html) is a tool that optimizes, shrinks and obfuscates source code (...). It's commonly used when generating release apk for android.

I'll try figuring it out by myself then. Will report back.

**Comment by drewnoakes** [comment]
@black-snow, did you find any useful rules in the end?

**Comment by black-snow** [comment]
Ah, I forgot ... Yes I did. I don't know whether all three rules are required (keeps pretty much everything) but it works for me:

    -keep class com.drew.** {*;}
    -keep interface com.drew.** {*;}
    -keep enum com.drew.** {*;}

**Comment by drewnoakes** [comment]
Thanks. Where do these lines go? Could you pop a pull request together?

**Comment by black-snow** [comment]
I'm using gradle and this goes into my module's proguard-rules.pro.
As you're currently not using gradle and I don't know if/how proguard is available outside of the gradle-world I'd suggest that you just add a small proguard section to the wiki/readme that says: If you're using proguard you'll most probably have to add those lines to your proguard-file: ...

**Comment by drewnoakes** [comment]
Good idea. I've added a [ProGuard page to the wiki](https://github.com/drewnoakes/metadata-extractor/wiki/ProGuard).

**Comment by black-snow** [comment]
Excellent
