### ISSUE TITLE
Metadata of Fujifilm "Raf" files not read correctly

### ISSUE THREAD

**Issue by TSGames** [drewnoakes/metadata-extractor#109]
Library Version 2.8.1

When trying to read Metadata from a Fujifilm Raf file, an exception is thrown:

`com.drew.imaging.ImageProcessingException: File format is not supported
at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:129)`

Sample raw files taken from here:
http://www.photographyblog.com/reviews/fujifilm_x_e2_review/sample_images/

**Comment by Odrahcyr** [comment]
The file format is currently not supported (see #73). Only the file detection works but is not yet implemented in ImageMetadataReader.

**Comment by TSGames** [comment]
I see. In older versions, I could fix the parsing by adding these lines:

```java
if(magicNumber==RAF_MAGIC_NUMBER){ // RAF file
	       	bufferedInputStream.mark(512);
        	byte[] data=new byte[512];
        	bufferedInputStream.read(data);
        	bufferedInputStream.reset();
        	for(int i=0;i<data.length;i++){
        		//System.out.print(data[i]);
        		if(data[i]==(byte)0xff && data[i+1]==(byte)0xd8 && data[i+2]==(byte)0xff){
        			bufferedInputStream.skip(i);
        			break;
        		}
        	}
        	magicNumber=JPEG_FILE_MAGIC_NUMBER;
        }
```

As seen here, the Raf file just havs a jpg container (this was a workaround so the parser tried to parse regular jpg data). Maybe this could help implementing native support, thanks!

**Comment by TSGames** [comment]
I could add support for the Raf Format (as well for all the files I've here for testing). The implementation is rather simple, although it should be getting confirmed that it'll work across several raf image files. Here's my fix.
```java
public class RafMetadataReader
{

    @NotNull
    public static Metadata readMetadata(@NotNull InputStream inputStream) throws JpegProcessingException, IOException
    {
        inputStream.mark(512);
        byte[] data=new byte[512];
        inputStream.read(data);
        inputStream.reset();
        for(int i=0;i<data.length;i++){
            //System.out.print(data[i]);
            if(data[i]==(byte)0xff && data[i+1]==(byte)0xd8 && data[i+2]==(byte)0xff){
                inputStream.skip(i);
                break;
            }
        }
        return JpegMetadataReader.readMetadata(inputStream);
    }

    private RafMetadataReader() throws Exception
    {
        throw new Exception("Not intended for instantiation");
    }
}
```

Finally, add the reader to the readMetadata() Method in ImageMetadataReader:
```java
@NotNull
    public static Metadata readMetadata(@NotNull final InputStream inputStream) throws ImageProcessingException, IOException
    {
      ...
         if (fileType == FileType.Raf)
                    return RafMetadataReader.readMetadata(bufferedInputStream);
      ...
}
```

Would be nice if this could be implemented in one of the next releases, so I don't have to add the fix myself. Thanks!

**Comment by drewnoakes** [comment]
Thanks for this. I'll get it merged ASAP.

Do you have some more sample images you could contribute to the project? Currently [there are only two RAF images](https://github.com/drewnoakes/metadata-extractor-images/tree/master/raf). This makes it hard to have much confidence in the correctness of an implementation.

**Comment by drewnoakes** [comment]
Just tried this out and it's great, thanks! Will put some error checking in and get it pushed up.
