### ISSUE TITLE
Support loading metadata from BufferedImage

### ISSUE THREAD

**Issue by sksamuel** [drewnoakes/metadata-extractor#112]
The ImageMetadataReader supports loading from streams and files. It would be very useful if it supported reading from already loaded buffered images.

**Comment by drewnoakes** [comment]
[`BufferedImage`](http://docs.oracle.com/javase/7/docs/api/java/awt/image/BufferedImage.html) has been around since Java 1.5 which is the same version the library currently targets, so it should be fine to add support directly.

**Comment by drewnoakes** [comment]
Are you sure `BufferedImage` contains metadata and not just pixel data?

**Comment by sksamuel** [comment]
It must do, as I can load into BufferedImage and save back out and meta
data is persisted.

**Comment by dragon66** [comment]
I don't think BufferedImage contains any metadata itself. When you load an image into a BufferedImage, it relies on the image reader to decide whether or not to keep the metadata and when you save a BufferedImage it relies on the image writer to put in the metadata.

**Comment by sksamuel** [comment]
Ok that makes sense, would explain why some of it disappears then - buffered image isn't keeping any its just the writer re-creating it.
