### ISSUE TITLE
Not finding textual metadata.

### ISSUE THREAD

**Issue by sksamuel** [drewnoakes/metadata-extractor#115]
![gibson](https://cloud.githubusercontent.com/assets/743706/8397511/c70a9556-1dc5-11e5-9729-eaab639baa1d.jpg)

Take the image I've attached. If you run that through the metadata extractor, it finds some of the information but not all.

For example, if I load the same image into this tool: http://regex.info/exif.cgi
Then I can see info such as:

_"Comment" -> "Dated: 12-09-09 FC Chairman Steve Gibson talks to the media about his support for the Corus steelworkers facing redundancy prior to the match against Ipswich this afternoon."_

Am I doing something wrong or does the library only support directories it explicitly knows about?

**Comment by drewnoakes** [comment]
This is an interesting image. It contains an APPC segment with some data I haven't seen before:

![image](https://cloud.githubusercontent.com/assets/350947/8398636/c03a9144-1dee-11e5-8252-0d7bac0b5909.png)

Do you know what software produced this image?

Are you able to contribute this image to the image database so we can have a regression test on this?

**Comment by sksamuel** [comment]
It's not my image, I can't remember where I got it from. I'll try and find
it again.

**Comment by sksamuel** [comment]
It's from this page.
http://www.mfc.co.uk.p.preprod.performgroup.com/page/shopping/stadium-tours

**Comment by drewnoakes** [comment]
Looks like that data is saved by Photoshop when using _Save for Web_.

http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/APP12.html#Ducky

Looking into this a little more now.

**Comment by sksamuel** [comment]
Do you only handle directories that you know about? Or could you dump
everything not recongized into an "unknown" directory?

**Comment by drewnoakes** [comment]
The `JpegSegmentReader` can spit out all JPEG segments found in a file. That's how I produced the above screenshots.

Turning one of these byte arrays into a meaningful `Directory` takes some understanding of the encoding.

Dumping everything unknown could result in some very large memory allocations. As it stands, metadata-extractor can handle very large files that you wouldn't want to load into memory in their entirety.

JPEG segments tend to be prefaced with a preamble to identify the payload. That's what `Ducky\0` is, in this case.

I'll add support for this in the next couple of days.

**Comment by drewnoakes** [comment]
Some preliminary notes on this segment, reverse engineered as I haven't found any definitive specification for this data.

```text
44 75 63 6B 79 // Ducky

00 01          // tag 1 (quality)
00 04          // length (4 bytes)
00 00 00 3C    // 60

00 02          // tag 2 (comment)
01 7C          // length (380 bytes)
00 00 00 BC    // ... unsure what this is (188 decimal)
// string data "Dated: 12-09-09" ... UTF-16?
00 44 00 61 00 74 00 65 00 64 00 3A 00 20 00 31 00 32 00 2D 00 30 00 39 00 2D 00 30 00 39 00 0D 00 0D 00 4D 00 69 00 64 00 64 00 6C 00 65 00 73 00 62 00 72 00 6F 00 75 00 67 00 68 00 20 00 46 00 43 00 20 00 43 00 68 00 61 00 69 00 72 00 6D 00 61 00 6E 00 20 00 53 00 74 00 65 00 76 00 65 00 20 00 47 00 69 00 62 00 73 00 6F 00 6E 00 20 00 74 00 61 00 6C 00 6B 00 73 00 20 00 74 00 6F 00 20 00 74 00 68 00 65 00 20 00 6D 00 65 00 64 00 69 00 61 00 20 00 61 00 62 00 6F 00 75 00 74 00 20 00 68 00 69 00 73 00 20 00 73 00 75 00 70 00 70 00 6F 00 72 00 74 00 20 00 66 00 6F 00 72 00 20 00 74 00 68 00 65 00 20 00 43 00 6F 00 72 00 75 00 73 00 20 00 73 00 74 00 65 00 65 00 6C 00 77 00 6F 00 72 00 6B 00 65 00 72 00 73 00 20 00 66 00 61 00 63 00 69 00 6E 00 67 00 20 00 72 00 65 00 64 00 75 00 6E 00 64 00 61 00 6E 00 63 00 79 00 20 00 70 00 72 00 69 00 6F 00 72 00 20 00 74 00 6F 00 20 00 74 00 68 00 65 00 20 00 6D 00 61 00 74 00 63 00 68 00 20 00 61 00 67 00 61 00 69 00 6E 00 73 00 74 00 20 00 49 00 70 00 73 00 77 00 69 00 63 00 68 00 20 00 74 00 68 00 69 00 73 00 20 00 61 00 66 00 74 00 65 00 72 00 6E 00 6F 00 6F 00 6E 00 2E

00 03          // tag 3 (copyright)
00 3A          // length 
00 00 00 1B    // ... unsure what this is (27 decimal)
// string data "Copyright north news & Pictures ltd"...
00 A9 00 20 00 4E 00 6F 00 72 00 74 00 68 00 20 00 4E 00 65 00 77 00 73 00 20 00 26 00 20 00 50 00 69 00 63 00 74 00 75 00 72 00 65 00 73 00 20 00 6C 00 74 00 64 00 00
```

**Comment by sksamuel** [comment]
Cool good work

**Comment by drewnoakes** [comment]
There's code on master for this now. Will get something up on Maven before long, but mostly focussing on getting the new [.NET implementation](https://github.com/drewnoakes/metadata-extractor-dotnet) to have identical output with this Java version.
