### ISSUE TITLE
Reading Orientation with 2.8.1

### ISSUE THREAD

**Issue by neilchaudhuri** [drewnoakes/metadata-extractor#119]
I am attempting to read the orientation of photos, and I am able to iterate through all the tags and find orientation buried among them. But when I attempt to write code virtually identical to what I see in the tests--i.e. using ExifIFD0Directory.TAG_ORIENTATION--I find that this constant isn't available. This suggests the tests and certainly the Javadoc are out-of-date.

How can we accomplish reading orientation in 2.8.1?

Thanks.

**Comment by neilchaudhuri** [comment]
I should mention since I'm using Scala the way I'm accomplishing this is like so:

metadata..getFirstDirectoryOfType(classOf[ExifIFD0Directory]).getTags.find(_.getTagName.compareToIgnoreCase("orientation") == 0)

Not pretty but gets the job done.

**Comment by drewnoakes** [comment]
`TAG_ORIENTATION` is, nowadays, defined on [`ExifDirectoryBase`](https://github.com/drewnoakes/metadata-extractor/blob/master/Source/com/drew/metadata/exif/ExifDirectoryBase.java#L107). However `ExifIFD0Directory` derives from that class so I cannot see why it wouldn't work.

If you run one of your images through `ImageMetadataReader.main(string[])` do you actually see a value for the orientation tag?

**Comment by drewnoakes** [comment]
Closing this for now. Feel free to reopen if you want to.
