### ISSUE TITLE
EPS support?

### ISSUE THREAD

**Issue by rmuller** [drewnoakes/metadata-extractor#120]
I would be awesome to have support for EPS. In many environments EPS pictures are very important.

**Comment by drewnoakes** [comment]
Sounds do-able, provided documentation exists on the file format.

Do you have some EPS files you can donate to the project for testing purposes? Ideally create an issue/PR against the https://github.com/drewnoakes/metadata-extractor-images repository.

Also, what metadata would you expect to find in EPS files?

**Comment by rmuller** [comment]
Great to hear this!

I do not own the EPS pictures, so I need permission. Will try next week. I expect to have this metadata:

Critical to have:

+ Width
+ Height
+ Format (example: EPT, Encapsulated PostScript with TIFF preview)
+ Resolution (example: 72x72)
+ Colorspace (example: CMYK)
+ Depth (example: 16/8-bit)

Important to have:

+ xap:CreateDate (example: 2010-03-02T15:46:35+01:00)
+ xap:CreatorTool (example: Adobe Illustrator CS3)

(more in general XMP)

Good to have:

+ Other

**Comment by rmuller** [comment]
Here are some pure Java based libraries claiming EPS support:

+ http://reader.imagero.com/ This site does not work anymore, see this [SO Question]
(http://stackoverflow.com/questions/32139822)
+ [freehep](http://java.freehep.org/) 
([source code](http://java.freehep.org/freehep-psviewer/source-repository.html))
+ http://www.spectotechnologies.com/en/open-projects/imageio-eps-plugin
+ [scifio](https://github.com/scifio/scifio)

Maybe this is helpful for you.

**Comment by drewnoakes** [comment]
Thanks, that's definitely helpful. I'll need to find some sample images for
testing too. Also I should say that I mightn't get to look at this for a
while. If you want to put a PR together I'd be happy to review and accept
it.

**Comment by drewnoakes** [comment]
https://en.wikipedia.org/wiki/Encapsulated_PostScript

http://stackoverflow.com/q/39607878/24874

**Comment by drewnoakes** [comment]
Thanks to @PaytonGarland for implementing this!

**Comment by drewnoakes** [comment]
#268
