### ISSUE TITLE
Support QuickTime (MOV) files

### ISSUE THREAD

**Issue by mbmast** [drewnoakes/metadata-extractor#127]
MOV files contain meta data, including the ever popular date created.  It would be nice to be able to extract meta data from MOV files.

**Comment by drewnoakes** [comment]
QuickTime file format specification: https://developer.apple.com/library/mac/documentation/QuickTime/QTFF/qtff.pdf

**Comment by drewnoakes** [comment]
A challenge with MOV files is that the current file type classification requires the first N bytes to be unique to the file type. Quicktime containers start with a length, which varies. It's possible to look for the `ftyp` atom, which should always be at a fixed offset, then verify from there. However the current classifier will need extending somehow.

**Comment by drewnoakes** [comment]
I have some basic code that extracts core metadata from MOV files. It actually also works for several other file formats, as the general Quicktime structure is used in multiple different video formats. This still needs some work and testing, and I've been prototyping in the [.NET port](https://github.com/drewnoakes/metadata-extractor-dotnet) so will have to back-port it to Java as well. But progress is being made on the first video file format for the library!

**Comment by drewnoakes** [comment]
This is now working in the .NET version. I hope to port this to Java before long. If someone wants to take a stab at it, feel free.

**Comment by ivanooi** [comment]
Anyway to update the metadata ?

**Comment by drewnoakes** [comment]
@ivanooi not yet, nor likely any time soon without some help from others. This is tracked in #14.

**Comment by PaytonGarland** [comment]
Our organization has Quicktime support in our legacy Java metadata extraction library that I can move over fairly easily if this project has not already been started by someone else.

**Comment by PaytonGarland** [comment]
I finished the Quicktime integration from our old library a little while ago, but I am debating two possible ways to go about it.

1) We leave the files as close to the original as possible [here](https://github.com/PaytonGarland/metadata-extractor/blob/quicktime/Source/com/drew/metadata/mov/QtReader.java)

- Positive: This has been tested through time with our organization
- Negative: The 'style' in that data is extracted does not generally follow that of the library

2) We do a larger reformat to more closely match the extraction 'style' of the riff file types by recursively reading through the atoms (while still attempting to reuse as much code as possible).  I've started this example[ here
](https://github.com/PaytonGarland/metadata-extractor/blob/quicktime-reformat/Source/com/drew/metadata/mov/QtReader.java)
- Positive: This will be integrated much better into the library
- Negative: It will not be thoroughly tested like option 1

@drewnoakes Any thoughts on this?

**Comment by drewnoakes** [comment]
I've read through the code of both on GitHub and have some observations. Let me know if I'm mistaken or miss anything.

Both options offer a rich object model for working with QT formatted data. They walk through the data, building a DOM-like tree structures with offsets/pointers back into the original QT stream. Once the whole file is walked, a second pass uses the offsets stored within the atom tree to go back to the stream and pull out whatever bits are needed. This requires the stream to be seekable (which is not the case with network streams, for example).

It is actually possible to process QT data in a single pass. This can involve fewer, shorter lived allocations on the heap, and supports non-seekable streams. The distinction is similar to that of SAX vs DOM for XML. SAX is more fiddly to work with and reason about, but can have better performance characteristics. 

The .NET version of metadata extractor [supports QuickTime](https://github.com/drewnoakes/metadata-extractor-dotnet/blob/7884b361d001443dbd5ec679ab9f57ebc710cdc3/MetadataExtractor/Formats/QuickTime/QuickTimeReader.cs#L108) data in this way. During the single linear walk through of the file, a handler (think of it as a visitor) is invoked which can either 1) read the atom's data from the stream directly 2) ignore the atom altogether 3) indicate that no further reads are required.

The .NET implementation's output for QuickTime files is in the `metadata/*.txt` files of the image repo.

I would say that the .NET and the Java libraries aim to be as close as possible to one another in their output, and having similar implementations makes maintaining both simpler. However it's clear you've done a lot of work here and the result is beneficial as is.

Let me know your thoughts. Ultimately I'm happy to go whichever route you choose as you're doing the work here.

**Comment by PaytonGarland** [comment]
Yes, that is correct on the structure of the first option from our legacy library.  You probably noticed the QtTree in my second option.  I was fiddling with storing some sort of history as the data is read.  

Ultimately, I would also like the reformatted version to extract everything in one pass using the same strategy as the Riff reader.  My biggest difficulty right now is making the reader aware of its location in the tree.  It may be as simple as constantly updating a list of atom names.  I know there are some atoms that have the same name, but offer different information depending upon its ancestors.  I'm currently working on going through the QuickTime documentation to get a better understanding of this.

Just from quickly looking at the reader class, it seems the .NET implementation is quite similar to how the Riff reader works with handlers.  I will go through your .NET implementation in more depth and see how things are done over there.

**Comment by drewnoakes** [comment]
The .NET implementation uses multiple handlers/visitors, all emitting directories into the same place. One handler can look for sub-atoms, and pass them off to other handlers. In .NET this can be done with delegates (function pointers) but a simple interface should suffice in Java.

**Comment by PaytonGarland** [comment]
I've gone through and reformatted a lot of the code and made more additions.  This is set to extract all metadata in one read and will skip over any unneeded atoms.  A HandlerFactory is used to introduce new handlers when a handler atom is encountered.  Each handler has its own set of atoms/containers to accept.  I've also added a print option to the processAtoms method in QtReader.  This is just used for debugging purposes and will print the visited parts of the tree to console.  https://github.com/PaytonGarland/metadata-extractor/tree/quicktime-support

It is probably better I hold off on a PR until after the File Type/MIME Type PR which makes changes to how containers are read in.  QuickTIme files have an offset of 4 (size is displayed first), so there will need to be some minor changes to the filetype detector.

**Comment by drewnoakes** [comment]
Huge thanks to @PaytonGarland for landing this! Will do some more testing with it and get a release out soon.
