### ISSUE TITLE
getObject and getDate return different date.

### ISSUE THREAD

**Issue by ivanooi** [drewnoakes/metadata-extractor#130]
Hi,

  With the latest update or event the old one. 
the following code return different date.

ExifSubIFDDirectory idir_exif_sub_dir = imd_metadata.getFirstDirectoryOfType( com.drew.metadata.exif.ExifSubIFDDirectory.class   );

This code return correct date : 
idir_exif_sub_dir.getObject( ExifSubIFDDirectory.TAG_DATETIME_DIGITIZED) 

This is wrong. 
idir_exif_sub_dir.getDate(ExifSubIFDDirectory.TAG_DATETIME_DIGITIZED )

Any ideas ? 

Thanks

**Comment by drewnoakes** [comment]
What is the return type of the getObject call? Is it String? If so, what is
the string value? Exif stores dates as strings, and I assume the library
can't parse the stored string.

Or are you saying that getDate also returns a date but it has an incorrect
value? Some concrete example would be useful.

**Comment by ivanooi** [comment]
Hi, ya. getObject return a correct date but getDate incorrect.

**Comment by ivanooi** [comment]
this is the test result. do you need the photo not? but please keep it private as it is not mine

getObject=2015:05:10 14:46:15 getDate=Sun May 10 22:46:15 SGT 2015

**Comment by ivanooi** [comment]
oh ya! thanks for the good work... it help a lot...am using this to create a tool for volunteer work. a big thanks

**Comment by drewnoakes** [comment]
You should pass your local time zone to `getDate`. You can get this via [`TimeZone.getDefault()`](http://docs.oracle.com/javase/6/docs/api/java/util/TimeZone.html#getDefault%28%29).

If you don't supply a time zone, metadata-extractor defaults to GMT (UTC), which explains the difference in hours between the input and output in SGT.

So you should write something like:

    directory.getDate(tag, TimeZone.getDefault());

**Comment by ivanooi** [comment]
hey thanks! problem solved

**Comment by drewnoakes** [comment]
Glad to hear it.
