### ISSUE TITLE
Problem to read metadata from jpeg correctly

### ISSUE THREAD

**Issue by mani76** [drewnoakes/metadata-extractor#131]
Hello,

I tried to use the library to extract metadata from the file:
http://mani.kapsi.fi/example.jpg

and got following metadata:

JFIF : Version : 1.1
JFIF : Resolution Units : none
JFIF : X Resolution : 1 dot
JFIF : Y Resolution : 1 dot
File : File Name : 260375-0859_20100521094238014501002001.jpg
File : File Size : 487334 bytes
File : File Modified Date : Fri Nov 13 10:47:29 EET 2015
Fundus Camera; Timer:0.0/Field Angle:50/Ref-ERR Comp. Lens:N/Flash Intensity:COLOR/Flash Intensity Compensation:-0,3/Flash Observation:134/Image Comment:;1230516173;Firmware Version 1.0.6;MANUAL;SINGLE;800;1;60;0;	1;
UNKNOWN;
<REMOVED SOME TEXT>
JPEG : Compression Type : Baseline
JPEG : Data Precision : 8 bits
JPEG : Image Height : 1568 pixels
JPEG : Image Width : 2352 pixels
JPEG : Number of Components : 3
JPEG : Component 1 : null component: Quantization table 0, Sampling factors 2 horiz/2 vert
JPEG : Component 2 : Y component: Quantization table 1, Sampling factors 1 horiz/1 vert
JPEG : Component 3 : Cb component: Quantization table 1, Sampling factors 1 horiz/1 vert

------------------------------------------------------

When using Phil Harvey’s  ExifTool I got following metadata:

ExifTool Version Number         : 9.46
File Name                       : 260375-0859_20100521094238014501002001.jpg
Directory                       : .
File Size                       : 476 kB
File Modification Date/Time     : 2015:11:13 10:47:29+02:00
File Access Date/Time           : 2015:11:13 10:47:47+02:00
File Inode Change Date/Time     : 2015:11:13 10:47:30+02:00
File Permissions                : rw-r-----
File Type                       : JPEG
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : None
X Resolution                    : 1
Y Resolution                    : 1
Comment                         : ;.CF-1;..CANON;..Fundus Camera;..300236;..1.1.00  ;..2 1 4 5 ;.$Retinal imaging control software MYD;..2.0.0.8;..20100521094300;..;..260375-0859;..;...L;..;..50;...COLOR ;...Color;...-0,3;...134;..;...1,112;...1;..;. .OUT;.!.NONE;.".UNKNOWN;.#;.$.OUT;.%.OUT;.&.OUT;.'.OUT;.(.OUT;.).OUT;.;...xxxx;...xxxx;..;..xxxx;...XX^xxx;...xxx^xxxx;.81.2.392.200046.100.3.5.200.3.5.300236.145.20100521094258;..:1.2.392.200046.100.3.5.200.3.5.300236.145.20100521094258.1;..@1.2.392.200046.100.3.5.200.3.5.300236.145.20100521094258.1.1.2.1;...145;...1;...2;...20100521;...094238;...20100521;...094256;..;...Color/L;..�Timer:0.0/Field Angle:50/Ref-ERR Comp. Lens:N/Flash Intensity:COLOR/Flash Intensity Compensation:-0,3/Flash Observation:134/Image Comment:;..EOS 50D;...1230516173;...Firmware Version 1.0.6;...MANUAL;...SINGLE;...800;...1;...60;...0;...1;...UNKNOWN;..;..;..;..;..;...UNKNOWN;..;..;...UNKNOWN;...UNKNOWN;...UNKNOWN;..0;...0;...1;...0;...0;...0;.;..;..;..; ; .; ..xxx^xxx; ..xxx^xxxx; .; .; .; .; .;�.20127
Image Width                     : 2352
Image Height                    : 1568
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 2352x1568

-----------------------------------------

Notice the differences in Comment field, which is missing in the metadata-extractor dump.

Is this some vendor specific way to encode fields or possible bug?

Any idea what might be the reason for the difference?

**Comment by drewnoakes** [comment]
This image has encoded data in the JPEG comment segment. Neither metadata extractor nor Exiftool provide any special decoding for this, and just treat the encoded byte stream as a string. The difference in formatting comes from how these bytes are presented to the user. Exiftool seems to convert some non-printable characters into full stops (`.`).

If you need to access this data, you should try to work out how it is encoded and operate on the raw bytes directly. Attempting to treat this data as a string in any encoding is invalid.

To access the raw bytes, use `JpegSegmentType.COM` with `JpegSegmentReader`.
