### ISSUE TITLE
Maven does not run NikonType2MakernoteTest1 and NikonType2MakernoteTest2

### ISSUE THREAD

**Issue by rdvdijk** [drewnoakes/metadata-extractor#133]
The [surefire plugin](https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html) in Maven runs the tests that match:

* `"**/Test*.java"`
* `"**/*Test.java"`
* `"**/*TestCase.java"`

The `NikonType2MakernoteTest1` and `NikonType2MakernoteTest2` files do not match these criteria.

Side note: there is a failing test in `NikonType2MakernoteTest2`.

**Comment by drewnoakes** [comment]
Well spotted. Will get these tests running, and fix the broken test.

    org.junit.ComparisonFailure: 
    Expected :80 114 105 110 116 73 77 0 48 49 48 48 0 0 13 0 1 0 22 0 22 0 2 0 1 0 0 0 3 0 94 0 0 0 7 0 0 0 0 0 8 0 0 0 0 0 9 0 0 0 0 0 10 0 0 0 0 0 11 0 -90 0 0 0 12 0 0 0 0 0 13 0 0 0 0 0 14 0 -66 0 0 0 0 1 5 0 0 0 1 1 1 0 0 0 9 17 0 0 16 39 0 0 11 15 0 0 16 39 0 0 -105 5 0 0 16 39 0 0 -80 8 0 0 16 39 0 0 1 28 0 0 16 39 0 0 94 2 0 0 16 39 0 0 -117 0 0 0 16 39 0 0 -53 3 0 0 16 39 0 0 -27 27 0 0 16 39 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    Actual   :80 114 105 110 116 73 77 0 48 49 48 48 0 0 13 0 1 0 22 0 22 0 2 0 1 0 0 0 3 0 94 0 0 0 7 0 0 0 0 0 8 0 0 0 0 0 9 0 0 0 0 0 10 0 0 0 0 0 11 0 166 0 0 0 12 0 0 0 0 0 13 0 0 0 0 0 14 0 190 0 0 0 0 1 5 0 0 0 1 1 1 0 0 0 9 17 0 0 16 39 0 0 11 15 0 0 16 39 0 0 151 5 0 0 16 39 0 0 176 8 0 0 16 39 0 0 1 28 0 0 16 39 0 0 94 2 0 0 16 39 0 0 139 0 0 0 16 39 0 0 203 3 0 0 16 39 0 0 229 27 0 0 16 39 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

    at com.drew.metadata.exif.NikonType2MakernoteTest2.testNikonMakernote_MatchesKnownValues(NikonType2MakernoteTest2.java:100)

Seems it's an issue with signed/unsigned bytes. This code changed recently when I introduced the .NET port, as .NET has both signed and unsigned types which more closely matches the Exif/TIFF format. I want both applications to produce the same output to assist regression testing, so there have been some (apparently breaking) changes here lately.

**Comment by rdvdijk** [comment]
I noticed a `& 0xff` in `Directory` ([line 884](https://github.com/drewnoakes/metadata-extractor/blob/master/Source/com/drew/metadata/Directory.java#L884)), which makes these values unsigned.
