### ISSUE TITLE
getNullTerminatedString should not use the default charset

### ISSUE THREAD

**Issue by trejkaz** [drewnoakes/metadata-extractor#135]
There is this method in BufferedReader:

    String getNullTerminatedString(int index, int maxLengthBytes) 

In implementing this method, I find it impossible to figure out what I should use as the charset. We're using forbidden-apis in our project to find this sort of suspicious usage and this was flagged.

I can fix this in our own project by passing the correct default charset into the constructor of our BufferedReader implementation and using that instead, but I looked at metadata-extractor's other implementations of this interface, and they're (of course) all using the platform default charset.

**Comment by drewnoakes** [comment]
I believe this is now obsolete. Please let me know if you feel otherwise.
