### ISSUE TITLE
Canon Makernote Illegally sized IFD

### ISSUE THREAD

**Issue by eicm** [drewnoakes/metadata-extractor#136]
I get this error "Illegally sized IFD" while trying to read Canon Makernote for the following image:
![img_1782 medium](https://cloud.githubusercontent.com/assets/4117330/12055623/d4c81330-aee3-11e5-8fa7-694e1608067c.JPG)

**Comment by highend3d** [comment]
Here is another example from another camera that does not work.
[piano 006.zip](https://github.com/drewnoakes/metadata-extractor/files/75344/piano.006.zip)

**Comment by drewnoakes** [comment]
@eicm, the image pasted in the issue appears to have been exported from picasa and doesn't contain any makernote data.

@highend3d the image you provided is useful, thanks. The makernote IFD is interpreted as having 9472 entries, which would spill outside the length of the file -- hence it's considered illegally sized. That number is `0x2500` in hex, which might actually be `0x0025` if there's a byte ordering issues.

I'll have to do some more research into why this may be the case with this image. Are you willing and able to provide the `piano 006.jpg` file to the project's sample image collection for future testing?

If you see this problem with other images from different camera models, that'd be good to know as well.

**Comment by eicm** [comment]
@drewnoakes Please check the photo using this meta data retriever http://regex.info/exif.cgi , it has a long list for maker note.

**Comment by highend3d** [comment]
Hi Drew, thanks for getting back to us.  Yes feel free to use piano picture.  Glad to give back to your project!  

Regarding the picture from eicm:  I just saved it and loaded it up here: http://regex.info/exif.cgi and it contains maker notes.

I also tried some of your own images from your test data repo for canon maker notes and we were not able to get results.  I will try to get the exact images we tried and update here.

**Comment by drewnoakes** [comment]
@eicm apologies I used the displayed image, not the linked one. I see the metadata now.

@highend3d this problem doesn't seem to occur for all Canon cameras. There's only one image in the test data repo that has this problem, and it's the Canon Powershot

**Comment by drewnoakes** [comment]
I think I've discovered the problem. It seems that the Canon makernote is always stored in Intel (little-endian) byte order. Most Canon files have this order throughout the whole file. The problematic files appear to have Motorolla (big-endian) throughout the file, with little-endian makernote data. I'll run some experiments with code that manually overrides this for Canon cameras.

**Comment by drewnoakes** [comment]
The manual override fixes these images, but breaks another (`issue 122.jpg`). Reading [this discussion](http://u88.n24.queensu.ca/exiftool/forum/index.php?topic=2843.0) with the ExifTool author, Phil Harvey, suggests that some software attempts to modify the byte order, but fails to do it properly.

I'll look at adding a heuristic to determine when to swizzle the byte order for an IFD. However given that technically this image has invalid encoding, I will only commit this to master if it doesn't break any well-behaved images.

**Comment by highend3d** [comment]
Hey Drew, thanks for taking the time on this.  We are finding problems in most of the Canon files we've tested, both our own and off the net.  For reference, the Piano picture was downloaded directly from my Canon to windows 7 computer and no external software was used.  I have tested others downloaded directly to Mac OSX as well, and it seems to be happening on all DLSR that we've tested and happy to contribute to your tests.  Let me know if you need more Canon samples as I have quite a few from different cameras (t2i, mark iii, 6d). The first picture from eicm was taken from a friends Canon as well.  I have a feeling this is a more common issue for current cameras -- but perhaps thats the latest software downloading software on the OS's? But I can tell you we've tested quite a lot of photos from many sources, but all sources are semi recent (past few years).  Hope that helps.

**Comment by drewnoakes** [comment]
In the linked discussion, Phil Harvey says the import software sometimes does this. If you shoot directly onto the SD Card, then copy the file directly, I suspect this might not happen. Either way, I found a decent heuristic that doesn't cause any issues with the existing test images, so I'll get that added to the lib. Thanks for your help with this.

**Comment by drewnoakes** [comment]
@highend3d I'd be happy to have sample images from any cameras you have that aren't currently represented in:

https://github.com/drewnoakes/metadata-extractor-images/tree/master/jpg

**Comment by eicm** [comment]
@drewnoakes Thanks for the support.

**Comment by eicm** [comment]
@drewnoakes I just build the master and tried it on the given test image. The lens type is return 0 and the lens model "".

**Comment by kwhopper** [comment]
@drewnoakes There's a possible fix for this in the dotnet project here:

https://github.com/drewnoakes/metadata-extractor-dotnet/pull/31
