### ISSUE TITLE
GifHeaderDirectory.TAG_TRANSPARENT_COLOR_INDEX should be TAG_BACKGROUND_COLOR_INDEX

### ISSUE THREAD

**Issue by nagix** [drewnoakes/metadata-extractor#141]
GifHeaderDirectory class has TAG_TRANSPARENT_COLOR_INDEX tag, but its value is read from the Background Color Index field in the GIF header. According to the GIF89a Specification, this is for the background color, not for the transparent color. The Transparent Color Index field is in the Graphic Control Extension and it is used only when the Transparent Color Flag is set.
https://www.w3.org/Graphics/GIF/spec-gif89a.txt

So, I think TAG_TRANSPARENT_COLOR_INDEX should be renamed to TAG_BACKGROUND_COLOR_INDEX. Also, do you have a plan to implement a method for extracting metadata from the Image Blocks, Graphic Control Extensions, Comment Extension, Plain Text Extension and Application Extension?

**Comment by drewnoakes** [comment]
Sounds sensible. Can you put a pull request together?
