### ISSUE TITLE
JfifDirectory.getImageWidth() and JfifDirectory.getImageHeight() should be renamed

### ISSUE THREAD

**Issue by nagix** [drewnoakes/metadata-extractor#143]
JfifDirectory.getImageWidth() returns the value for JfifDirectory.TAG_RESY, but the name of the method should be renamed to getResolutionY(). In the same manner, JfifDirectory.getImageHeight() returns the value for JfifDirectory.TAG_RESX, but it should be renamed to getResolutionX().

**Comment by nagix** [comment]
There are JfifDescriptor.getImageResXDescription() and JfifDescriptor.getImageResYDescription(), so maybe JfifDirectory.getResX() and JfifDirectory.getResY() are better.

**Comment by drewnoakes** [comment]
You're right. A PR would be great.
