### ISSUE TITLE
Cannot extract metadata from webp VP8L

### ISSUE THREAD

**Issue by Bouki** [drewnoakes/metadata-extractor#150]
Hello

The current parser does not supports all possible headers for webp.
It fails with an image an like this :
https://lh3.googleusercontent.com/xpkyqgacjrWTa_IzKVCRPskmB0DH89tHb6Pl55vw9CYd3rx3edBkuqNiKZ8-ALuT_6oi=h900-rw

Regards

**Comment by drewnoakes** [comment]
Want to put a PR together for this?

**Comment by Bouki** [comment]
I've just wrote a code to decode WEBPVP8L / WEBPVP8X / WEBPVP8

You'll need to adapt it for this library but it's already working as is using an inputstream

https://gist.github.com/Bouki/cca63b5dd6a8abba967c

for tests images you can use :

- WEBPVP8L : https://lh3.googleusercontent.com/xpkyqgacjrWTa_IzKVCRPskmB0DH89tHb6Pl55vw9CYd3rx3edBkuqNiKZ8-ALuT_6oi=h900-rw
- WEBPVP8X : https://lh4.ggpht.com/Czy6tBGNPrTPy9V4qIlevnDPIy3qwdeU3iGpc_ajMTAyOgLP3QU96U4rqq9NyrSbA9A=h900-rw
- WEBPVP8 : https://lh4.ggpht.com/HeK2BYWTstbVMcPJI3jC5lvTlr8oA-oMlg98cwWT_hkwLkDmWaMTEY_knciDxEx5gw=h900-rw

**Comment by drewnoakes** [comment]
Thanks for the report. Issue fixed by linked commits in both the Java and .NET projects.
