### ISSUE TITLE
Cannot access to a tag data

### ISSUE THREAD

**Issue by Teiki** [drewnoakes/metadata-extractor#151]
Hi,
I'm using the library to get some metadata value from an agronomic captor image.
The captor take two kind of image: tif and jpg

With jpg format I get almost all meta data but with tif image I get only 2/6 directory (no GPS data).
There is also a special tag value that I would like to get, but can't neither with jpg than tif format: "field of view" = 65.5°

Is there any way to get this data by modifying myself the code, or with a special command?

Thank you a lot for the library and your help.

Here is two sample file:

![img_160106_101106_0000_rgb](https://cloud.githubusercontent.com/assets/3765593/13355372/42295922-dca0-11e5-89be-975ec8875837.JPG)

[IMG_160106_101106_0000_REG.TIF.zip](https://github.com/drewnoakes/metadata-extractor/files/148465/IMG_160106_101106_0000_REG.TIF.zip)

**Comment by Teiki** [comment]
It looks like the libtiff who create this tiff is using 0x0d inste0x04 au lieu de

**Comment by kwhopper** [comment]
If my commit on the .NET project is correct, this isn't an issue with format 13 and getting the XMP. There was an IFD0 tag not being processed that appears to hold the XMP string.

The "ExifIFDPointer" issues you see are addressed in another (hopefully) good commit on the .NET project  - drewnoakes/metadata-extractor-dotnet#37. Tiff formatCode 13 is a more explicit indicator that a tag is definitely an ifd pointer; it doesn't use the four-byte rule. Neither the Java nor .NET versions were aware of this format, and testing your image with the .NET fix shows two "missing" ifd's for sub and GPS that you probably expected.

I'm happy to try and port the XMP fix to Java if @drewnoakes thinks it's ok on the .NET side. But feel free to give it a go.

**Comment by drewnoakes** [comment]
Running the latest code from `master` gives:

```text
FILE: Issue 151.tif

[Exif IFD0 - 0x0100] Image Width = 1280 pixels
[Exif IFD0 - 0x0101] Image Height = 964 pixels
[Exif IFD0 - 0x0102] Bits Per Sample = 16 bits/component/pixel
[Exif IFD0 - 0x0103] Compression = Uncompressed
[Exif IFD0 - 0x0106] Photometric Interpretation = BlackIsZero
[Exif IFD0 - 0x010e] Image Description = 735 nm
[Exif IFD0 - 0x010f] Make = Parrot
[Exif IFD0 - 0x0110] Model = Chlorophyll
[Exif IFD0 - 0x0111] Strip Offsets = 8
[Exif IFD0 - 0x0115] Samples Per Pixel = 1 samples/pixel
[Exif IFD0 - 0x0117] Strip Byte Counts = 2467840 bytes
[Exif IFD0 - 0x0118] Minimum Sample Value = 0
[Exif IFD0 - 0x011c] Planar Configuration = Chunky (contiguous for each subsampling pixel)
[Exif IFD0 - 0x0131] Software = v0.5.1
[Exif IFD0 - 0xc62f] Unknown tag (0xc62f) = PI040378D25L000046
[Exif IFD0 - 0xc68b] Unknown tag (0xc68b) = [31 values]

[Xmp - 0xffff] XMP Value Count = 21

[Exif SubIFD - 0x829a] Exposure Time = 3320340/2147483647 sec
[Exif SubIFD - 0x829d] F-Number = f/2.2
[Exif SubIFD - 0x8824] Spectral Sensitivity = 735 nm
[Exif SubIFD - 0x8827] ISO Speed Ratings = 200
[Exif SubIFD - 0x9003] Date/Time Original = 2016:01:06 10:11:06
[Exif SubIFD - 0x9004] Date/Time Digitized = 1970:01:01 00:03:26
[Exif SubIFD - 0x9201] Shutter Speed Value = 1/646 sec
[Exif SubIFD - 0x9202] Aperture Value = f/2.2
[Exif SubIFD - 0x9205] Max Aperture Value = f/2.2
[Exif SubIFD - 0x920a] Focal Length = 4 mm
[Exif SubIFD - 0x9211] Image Number = 0
[Exif SubIFD - 0x9291] Sub-Sec Time Original = 534657
[Exif SubIFD - 0x9292] Sub-Sec Time Digitized = 937153
[Exif SubIFD - 0xa20e] Focal Plane X Resolution = 8053064/2147483647 unknown (4)
[Exif SubIFD - 0xa20f] Focal Plane Y Resolution = 8053064/2147483647 unknown (4)
[Exif SubIFD - 0xa210] Focal Plane Resolution Unit = Unknown (4)
[Exif SubIFD - 0xa402] Exposure Mode = Auto exposure
[Exif SubIFD - 0xa405] Focal Length 35 = 30 mm
[Exif SubIFD - 0xa420] Unique Image ID = 49D2981FC92CBC43F09C1DAB9896BC4F
[Exif SubIFD - 0xa431] Body Serial Number = PI040378D25L000046

[GPS - 0x0000] GPS Version ID = 2.200
[GPS - 0x0001] GPS Latitude Ref = N
[GPS - 0x0002] GPS Latitude = 49° 11' 11.57"
[GPS - 0x0003] GPS Longitude Ref = E
[GPS - 0x0004] GPS Longitude = 1° 39' 19.85"
[GPS - 0x0005] GPS Altitude Ref = Sea level
[GPS - 0x0006] GPS Altitude = 162 metres
[GPS - 0x0012] GPS Map Datum = WGS-84

[File - 0x0001] File Name = Issue 151.tif
[File - 0x0002] File Size = 2471086 bytes
[File - 0x0003] File Modified Date = <omitted for regression testing as checkout dependent>
```

Are you expecting to see more metadata than this? You say you received only two of six. There are four here (five if you include file system data).

**Comment by Teiki** [comment]
Hi DrewNoakes,
Thanks a lot! It's a big enhancement! 

The things that miss are:
XMP-Camera tags:
![capture d ecran 2016-03-28 a 17 00 22](https://cloud.githubusercontent.com/assets/3765593/14080717/1b623bcc-f507-11e5-8921-ba3858ecf37a.png)

There is also a tag that isn't in your result:
Field of View
![capture d ecran 2016-03-28 a 17 08 59](https://cloud.githubusercontent.com/assets/3765593/14080873/f20f6b2c-f507-11e5-937f-d69763dab56b.png)

**Comment by Teiki** [comment]
Hi,
I finally had time to take a look to the new update.
In my test, I was able to get the XMP-Camera folder (the one I mention above).
But I didn't find the "field of view".
I'm going to look for a reason about that. I will post tomorrow my research.

**Comment by kwhopper** [comment]
Hi Teiki. "Field of View" isn't a tag - it's a composite calculation using values from other tags. I was going to look into this again as part of a larger R&D project for some kind of "Composite" directory. In lieu of that, we could try and see if the calculation can be done outside the directory using tag values or maybe @drewnoakes has other ideas. Thanks

**Comment by drewnoakes** [comment]
100% what @kwhopper said :)

**Comment by Teiki** [comment]
Hi kwhopper and drewnoakes,
Oh ok, I didn't know but yes you right it must be calculate with the Focal Length.
Thank you, now the library is fully compatible with this kind of structure.

**Comment by drewnoakes** [comment]
I'll close this for now. Reopen if we missed something.
