### ISSUE TITLE
Horiz/Vert sampling factors reversed?

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor#152]
Suresh said on the mailing list:

> I found an issue with the JPEG sampling factors extracted by your library. I found the Horizontal and Vertical sampling factors switched (1,2 instead of 2,1) when I compared it with the information provided by JPEGTRAN.
>
> I have attached a zip file with a sample program, a sample image and the jpegtran command I used to compare check the sampling factor.
>
> Is it just an issue of switching of the 2 fields or is there some other bug? After finding this issue I am using a jpegtran crop command just to get this info which will make my date stamping a little bit slower.

Here is the ZIP file: [sampling_factor.zip](https://github.com/drewnoakes/metadata-extractor/files/150142/sampling_factor.zip)

**Comment by kwhopper** [comment]
They appear to be reversed. All you have to do is swap the method bodies in JpegComponent.java for getHorizontalSamplingFactor()  and  getVerticalSamplingFactor(). This is confirmed with ExifTool and metadata-extractor-dotnet testing.

**Comment by drewnoakes** [comment]
Closed via #156.
