### ISSUE TITLE
Make GpsDirectory#getGpsDate() locale independent

### ISSUE THREAD

**Issue by LZaruba** [drewnoakes/metadata-extractor#160]
When running in locale which uses comma as decimal separator, loading of the gps date fails and return snulls which causes ExifDirectoryTest to fail.

**Comment by LZaruba** [comment]
I should probably mention that this commit doesn't change any output values from the API and the change itself is "locale independent".

**Comment by drewnoakes** [comment]
Thanks for these two PRs.
