### ISSUE TITLE
Add possibility to provide additional possible encodings to IPTC encoding guessing

### ISSUE THREAD

**Issue by LZaruba** [drewnoakes/metadata-extractor#165]
`com.drew.metadata.iptc.Iso2022Converter.guessEncoding(byte[])` tries to guess from following encodings
- UTF-8
- System property "file.encoding" (platform dependent)
- ISO-8859-1

When there are images with certain encoding that is not properly referenced in the IPTC metadata, guessing is limited to the hardcoded list (as long as one is not willing to switch file.encoding property).

I am suggesting to add System property for additional encodings that can be added to the guessing list.

**Comment by drewnoakes** [comment]
Given the recent change to support decoding strings using different `Charset`s _after_ extraction has completed, I'm on the fence about this PR. Do you think it's still needed?

**Comment by LZaruba** [comment]
Hi,
as far as I understood from diffs, reading values from Directory using getStringValue and then specifying the encoding will not be in anyway affected by calls to Iso2022Converter.convertISO2022CharsetToJavaCharset(bytes). Do I get it right?
If so, your solutions is much more elegant and will be happy to change the usage to the StringValue :)

Thanks!

**Comment by drewnoakes** [comment]
Closing this as in general it's now possible to use `StringValue` to re-encode strings from the original bytes at any point.
