### ISSUE TITLE
License mix (Apache + GPL)

### ISSUE THREAD

**Issue by yschkatula** [drewnoakes/metadata-extractor#170]
Hi all,

I'm confused with a license situation here:
a) The project itself is Apache-licensed, so far so good for commercial apps.
b) Once installed via NuGet, the project pumps up SharpZipLib as a dependency. And this is a GPL beast. Red flag from legal department, with no doubt.

Any hint/clue?

Very thanks in advance,
Yury

**Comment by drewnoakes** [comment]
This issue applies to the .NET version of the library only. This is the Java repo, so I've migrated the issue to drewnoakes/metadata-extractor-dotnet#48.
