### ISSUE TITLE
Subject Area related metadata not found - Iphone 5s

### ISSUE THREAD

**Issue by se7en007** [drewnoakes/metadata-extractor#177]
Please forgive for any mistakes. I am working on a tool that extracts any Face detection data embedded in image metadata.

I have this photo IMG_5130 which has location of 2 Subject area and tells the type of both subjects - Face. This is attached exiftool metadata:-

        **Subject Area                    : 1042 1378 682 682**
[Some other metadatas....]
	**Region Area Y                   : 0.491422, 0.570670
	Region Area W                   : 0.137255, 0.193627
	Region Area X                   : 0.731005, 0.306066
	Region Area H                   : 0.183007, 0.258170**
	**Region Area Unit                : normalized, normalized**
	**Region Type                     : Face, Face**
	Region Extensions Angle Info Yaw: 315
	Region Extensions Angle Info Roll: 0
	Region Extensions Confidence Level: 298
	Region Extensions Time Stamp    : 612444756063
	Region Extensions Face ID       : 16
	**Region Applied To Dimensions H  : 2448
	Region Applied To Dimensions W  : 3264
	Region Applied To Dimensions Unit: pixel** 

[IMG_5130_Exiftool.txt](https://github.com/drewnoakes/metadata-extractor/files/231740/IMG_5130_Exiftool.txt)
 - The file with complete exiftool output.

On running MetadataExtractor, I do get SubjectArea from Exif IFD0, but not other metadatas. Any insight you can provide will be helpful.

JPEG
	Compression Type = Baseline
	Data Precision = 8 bits
	Image Height = 2448 pixels
	Image Width = 3264 pixels
	Number of Components = 3
	Component 1 = Y component: Quantization table 0, Sampling factors 2 horiz/2 vert
	Component 2 = Cb component: Quantization table 1, Sampling factors 1 horiz/1 vert
	Component 3 = Cr component: Quantization table 1, Sampling factors 1 horiz/1 vert
Exif IFD0
	Make = Apple
	Model = iPhone 5s
	Orientation = Top, left side (Horizontal / normal)
	X Resolution = 72 dots per inch
	Y Resolution = 72 dots per inch
	Resolution Unit = Inch
	Software = 9.3.1
	Date/Time = 2016:04:19 14:49:49
	YCbCr Positioning = Center of pixel array
Exif SubIFD
	Exposure Time = 1/33 sec
	F-Number = f/2.2
	Exposure Program = Program normal
	ISO Speed Ratings = 125
	Exif Version = 2.21
	Date/Time Original = 2016:04:19 14:49:49
	Date/Time Digitized = 2016:04:19 14:49:49
	Components Configuration = YCbCr
	Shutter Speed Value = 1/33 sec
	Aperture Value = f/2.2
	Brightness Value = 3563/1370
	Exposure Bias Value = 0 EV
	Metering Mode = Multi-segment
	Flash = Flash did not fire, auto
	Focal Length = 4.2 mm
	**Subject Location = 1042 1378 682 682**
	Makernote = [838 values]
	Sub-Sec Time Original = 625
	Sub-Sec Time Digitized = 625
	FlashPix Version = 1.00
	Color Space = sRGB
	Exif Image Width = 3264 pixels
	Exif Image Height = 2448 pixels
	Sensing Method = One-chip color area sensor
	Scene Type = Directly photographed image
	Exposure Mode = Auto exposure
	White Balance Mode = Auto white balance
	Focal Length 35 = 29 mm
	Scene Capture Type = Standard
	Lens Specification = 4.15mm f/2.2
	Lens Make = Apple
	Lens Model = iPhone 5s back camera 4.15mm f/2.2
Exif Thumbnail
	Compression = JPEG (old-style)
	X Resolution = 72 dots per inch
	Y Resolution = 72 dots per inch
	Resolution Unit = Inch
	Thumbnail Offset = 1692 bytes
	Thumbnail Length = 9594 bytes
XMP
	XMP Value Count = 34
File
	File Name = IMG_5130.JPG
	File Size = 1247708 bytes
	File Modified Date = Tue Apr 19 14:49:49 +05:30 2016

I have attached the image. This is my picture(from my Iphone) and I have taken consent of both my colleagues in the pic. You are free to use the pic as you may see fit.

Thanks in  advance.

![img_5130](https://cloud.githubusercontent.com/assets/15953020/14741393/8dd8051e-08b3-11e6-8e4d-1fd4debd35c5.JPG)

**Comment by drewnoakes** [comment]
The values you are after appear to be defined in XMP.

You can see in the output:

> XMP Value Count = 34

You can access the full `XMPMeta` object from `XmpDirectory.getXMPMeta()`. At that point, you're using Adobe's XMP library.

**Comment by se7en007** [comment]
Hi, Thanks for the quick reply. I studied XMP a liitte from http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/XMP.html and further found metadata I am looking for here: http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/MWG.html#Regions. I understand XMP metadata is from Adobe and is in XML/RDF format. 

My question is I used the code from [here](https://github.com/drewnoakes/metadata-extractor/wiki/GettingStarted#print-out-all-tag-values) to extract all metadata as it says. Wouldn't XMP be an exception to this as it deviates from the intended behaviour?

Second, can't we have an iterator which traverses each tag of XMP tree?

**Comment by se7en007** [comment]
Hi, Thanks for the iterator part as well. I used below code to find XMP data.

```
List<XmpDirectory> xmpDirectories = (List<XmpDirectory>) metadata.getDirectoriesOfType(XmpDirectory.class);
for (XmpDirectory xmpDirectory : xmpDirectories) {
	XMPMeta xmpMeta = xmpDirectory.getXMPMeta();
	
	//Fetch root node
	XMPIterator iterator = xmpMeta.iterator();
	while (iterator.hasNext()) {
		XMPPropertyInfo xmpPropertyInfo = (XMPPropertyInfo) iterator.next();
		System.out.println(xmpPropertyInfo.getPath() + ":" + xmpPropertyInfo.getValue());
	}
} 
```

**Comment by drewnoakes** [comment]
As you discovered, the structure of XMP is a little different to metadata-extractor's directory/tag structures. In fact, it's a complete analog. Another limitation of metadata-extractor is that it expects tags to be identified by integers, and XMP uses strings. This makes it hard to stuff all the XMP values into a `Directory` so they can be iterated over. In future I'd like to overhaul the API considerably to remove this and other limitations, but that will take time.

For now, the approach you use to iterate XMP values looks good. If you don't mind I'll include that code on the wiki so that it might help others.

I'll close this for now. Reopen if you need it.

**Comment by se7en007** [comment]
Sure, that code would help a lot to any one who is a newbie like me. This has been due for long - I would like to thank you for this amazing library. It has been a great help. Good wishes to you.

**Comment by drewnoakes** [comment]
You're very welcome. Thanks for your contribution.

https://github.com/drewnoakes/metadata-extractor/wiki/XMP

**Comment by Webreaper** [comment]
> In future I'd like to overhaul the API considerably to remove this and other limitations, but that will take time.

Just out of interest, did this ever happen? :)

**Comment by drewnoakes** [comment]
Not to date. It's a reasonably sized chunk of work.
