### ISSUE TITLE
[Q] Video formats supported?

### ISSUE THREAD

**Issue by peterlitvak** [drewnoakes/metadata-extractor#178]
The original page https://drewnoakes.com/code/exif/ mentions the support for MOV MP4 M4V 3G2 3GP 3GP but I couldn't find anything in the code or javadoc that mentions video format support.
What am I missing?
Thank you

**Comment by drewnoakes** [comment]
Support for these file types exists in the .NET implementation, but not yet the Java one. This is tracked in #127, and contributions here are welcome. The C# source exists as a reference.

**Comment by peterlitvak** [comment]
Nice, thank you!
