### ISSUE TITLE
Dependency on XMPCore ?

### ISSUE THREAD

**Issue by baszero** [drewnoakes/metadata-extractor#179]
Is there a dependency to http://mvnrepository.com/artifact/com.adobe.xmp/xmpcore ?

I use metadata-extractor 2.9.1 and I get a runtime error in Java:

`java.lang.NoClassDefFoundError: com/adobe/xmp/XMPException`

in the pom.xml I don't see any dependency.

**Comment by drewnoakes** [comment]
This should do it:

https://github.com/drewnoakes/metadata-extractor/blob/master/pom.xml#L69

**Comment by baszero** [comment]
Yes, SOLVED. Thanks!
