### ISSUE TITLE
Extended XMP support

### ISSUE THREAD

**Issue by bezineb5** [drewnoakes/metadata-extractor#184]
Hi,

It seems that metadata-extractor doesn't support Extended XMP yet, as described here:
[http://stackoverflow.com/questions/23253281/reading-jpg-files-xmp-metadata](http://stackoverflow.com/questions/23253281/reading-jpg-files-xmp-metadata)

The specifications of Extended XMP are here: 
[http://www.adobe.com/content/dam/Adobe/en/devnet/xmp/pdfs/XMPSpecificationPart3.pdf](http://www.adobe.com/content/dam/Adobe/en/devnet/xmp/pdfs/XMPSpecificationPart3.pdf)
(see page 19 in particular).

Google uses that for their focus feature on android camera and in the Cardboard Camera app.
It would be a nice feature to add to the lib!

I've written the code to support reading it, I'm ready to do a pull request if it's considered a useful feature for metadata-extractor.

**Comment by drewnoakes** [comment]
I haven't looked at this deeply yet, but are you referring to the XMP values surfaces as tags in the `XmpDirectory`, or are you referring to the `XMPMeta` object on `XmpDirectory`?

If the former, actually much of XMP is not supported. XMP has its own structure which doesn't easily map to the directory/tag model used in this library. Only a handful of common values are mapped to tags.

If the latter, then this is a limitation of the Adobe xmp-core.jar which hasn't been updated since 2012 as far as I can tell.

**Comment by paperboyo** [comment]
> actually much of XMP is not supported. XMP has its own structure which doesn't easily map to the directory/tag model used in this library

This results in problems in metadata quality and consistency. E.g. according to spec, some data written to the legacy fields is [truncated and appear in full only in the XMP](https://github.com/guardian/grid/issues/1117#issuecomment-143583140) portion of the metadata. XMP portion is more standardised when it comes to [Unicode support](https://github.com/guardian/grid/issues/1117#issuecomment-149366878), date formats etc. There are plenty of sources that show how to map/reconcile field contents in different parts of the metadata, e.g.:
- http://www.metadataworkinggroup.org/pdf/mwg_guidance.pdf (p. 23)
- http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2014-12/XMPSpecificationPart3.pdf (p. 49)
- http://www.controlledvocabulary.com/imagedatabases/iptc_core_mapped.pdf
- https://www.iptc.org/std/photometadata/documentation/GenericGuidelines/index.htm#!Documents/fieldreferencetable.htm

As metadata-extractor is [not reading most of XMP](http://www.metadataworkinggroup.org/pdf/mwg_guidance.pdf), I would like to know what's your opinion on the future-proof system, @drewnoakes ? Would you expect the reconciliation to one day happen [within metadata-extractor](https://github.com/drewnoakes/metadata-extractor/issues/10) or would you rather users of metadata-extractor to perform reconciliation externally?

**Comment by bezineb5** [comment]
Hi,

Actually I think I refer to yet another thing, as the "Extended XMP" I'm referring to is not about the content itself, but the way large pieces of XMP data are stored into JPEG files specifically.

To quote Adobe's documentation about this:

> 2.1.3.1 Extended XMP in JPEG
> Following the normal rules for JPEG sections, the header plus the following data can be at most 65535 bytes long. If the XMP packet is not split across multiple APP1 sections, the size of the XMP packet can be at most 65502 bytes. It is unusual for XMP to exceed this size; typically, it is around 2 KB.
> If the serialized XMP packet becomes larger than the 64 KB limit, you can divide it into a main portion (StandardXMP) and an extended portion (ExtendedXMP), and store it in multiple JPEG marker segment. A reader must check for the existence of ExtendedXMP, and if it is present, integrate the data with the main XMP. Each portion (standard and extended) is a fully formed XMP metadata tree, although only the standard portion contains a complete packet wrapper. If the data is more than twice the 64 KB limit, the extended portion can also be split and stored in multiple marker segments; in this case, the split portions are not fully formed metadata trees.

Here is an example of a file containing such Extended XMP data (it's from the Google Cardboard Camera: the right-eye image is stored in XMP data, as described here:
[http://vectorcult.com/2015/12/extracting-the-audio-stereo-pair-from-cardboard-camera-3d-panoramic-images/](http://vectorcult.com/2015/12/extracting-the-audio-stereo-pair-from-cardboard-camera-3d-panoramic-images/
)):
[https://www.dropbox.com/s/w71jep7aspfe961/CardboardCamera.vr.jpg?dl=0
](https://www.dropbox.com/s/w71jep7aspfe961/CardboardCamera.vr.jpg?dl=0
)

**Comment by drewnoakes** [comment]
@bezineb5 you're right, the XMP packet in the first APP1 segment points to data in the next APP1 segment.

![image](https://cloud.githubusercontent.com/assets/350947/20242686/dc5cc8d8-a92f-11e6-869c-673097310062.png)

Notice the property `xmpNote:HasExtendedXMP` with value 5740B4AB4292ABB7BDCE0639415FA33F. That code appears 25 bytes into the next APP1 segment, as shown.

The second segment starts with 0xFFE1 (which marks an APP1 segment) then 0xFFB4 (the length of the segment -- 65,460 bytes). After that there's an XMP extension marker `http://ns.adobe.com/xmp/extension/` which this library currently ignores. Then there's a null byte, the code seen in the prior XMP packet (5740B4AB4292ABB7BDCE0639415FA33F), a null byte, then seven bytes (2C 05 DE 00 00 00 00) before the XMP packet starts. I'm not clear exactly what those seven bytes represent.

At the next boundary, we see:

![image](https://cloud.githubusercontent.com/assets/350947/20242733/59e871f2-a931-11e6-9622-818dc09a034b.png)

The sequence of leading bytes is similar.

That file contains a lot of extended XMP segments, and they're all the same length (except the first and last). Looks like, as you say, the second image is encoded in Base-64.

```text
Type Length Padding  Offset
---- ------ -------  ------
App1    904       0       2
App1  65460       0     908
App1  65460       0   66370
App1  65460       0  131832
App1  65460       0  197294
App1  65460       0  262756
App1  65460       0  328218
App1  65460       0  393680
App1  65460       0  459142
App1  65460       0  524604
App1  65460       0  590066
App1  65460       0  655528
App1  65460       0  720990
App1  65460       0  786452
App1  65460       0  851914
App1  65460       0  917376
App1  65460       0  982838
App1  65460       0 1048300
App1  65460       0 1113762
App1  65460       0 1179224
App1  65460       0 1244686
App1  65460       0 1310148
App1  65460       0 1375610
App1  65460       0 1441072
App1  65460       0 1506534
App1  65460       0 1571996
App1  65460       0 1637458
App1  65460       0 1702920
App1  65460       0 1768382
App1  65460       0 1833844
App1  65460       0 1899306
App1  65460       0 1964768
App1  65460       0 2030230
App1  65460       0 2095692
App1  65460       0 2161154
App1  65460       0 2226616
App1  65460       0 2292078
App1  65460       0 2357540
App1  65460       0 2423002
App1  65460       0 2488464
App1  65460       0 2553926
App1  65460       0 2619388
App1  65460       0 2684850
App1  65460       0 2750312
App1  65460       0 2815774
App1   8311       0 2881236
 Dqt    132       0 2889549
Sof0     17       0 2889683
 Dht     30       0 2889702
 Dht     97       0 2889734
 Dht     28       0 2889833
 Dht     58       0 2889863
 Sos     12       0 2889923
 Eoi      0 1707046 4596983
```

It seems that the 'standard' XMP segment is one complete packet, and that all the 'extended' segments must be concatenated to form a complete packet.

There was some discussion here: http://dev.exiv2.org/boards/3/topics/1631

I'll have a look in the XMP specification for more details on how to interpret these leading byte sequences.

**Comment by drewnoakes** [comment]
Ok wow that was a bit weird! Issue lay dormant for ~4 months, I post a comment and you file a PR within five minutes. Either you're a very fast coder, or today is a good day for looking into extended XMP :)

**Comment by bezineb5** [comment]
Thanks for investigating! Actually, I already coded a fix for this. However it's only tested with Google VR Camera images, so I'm not 100% sure it's correct. Seems like today is a good for Extended XMP!

**Comment by drewnoakes** [comment]
Very nice. Code looks great.

I found another test image here, this time containing depth-map data (also from Android):

https://raw.githubusercontent.com/spite/android-lens-blur-depth-extractor/master/table.jpg

**Comment by bezineb5** [comment]
However, there are limitations:
- It's only able to read extended XMP, not write it.
- According to the Adobe documentation, the property xmpNote:HasExtendedXMP shouldn't be exposed to the application. In my change, I don't remove it from the XMP properties.
- There are no unit-tests.

**Comment by drewnoakes** [comment]
That's great.

1. There's no support for writing any metadata at this point, though XMP would be a good candidate for initial support (there's some initiative towards this in the .NET version).
2. Exposing `xmpNote:HasExtendedXMP` seems pretty harmless.
3. I'll add images with extended XMP to the `metadata-extractor-images` repo which acts as a regression test of sorts.

**Comment by r57zone** [comment]
Does anyone have a ready-made utility to extract the second image from Google VR Photo?
