### ISSUE TITLE
Upgrade to xmpcore 5.1.3 to avoid XXE vulnerability

### ISSUE THREAD

**Issue by tballison** [drewnoakes/metadata-extractor#188]
https://helpx.adobe.com/security/products/xmpcore/apsb16-24.html

<= 5.1.2 are vulnerable to an XXE.  Please upgrade to 5.1.3

**Comment by drewnoakes** [comment]
Thanks for the heads up. Can you make a PR?

**Comment by tballison** [comment]
Y, will do once this has been pushed to Maven Central.  Thank you!

**Comment by drewnoakes** [comment]
Looks like XMPCore 5.1.3 is still not available on Maven Central:

https://mvnrepository.com/artifact/com.adobe.xmp/xmpcore

Apache TIKA is also tracking this issue with no resolution as yet: 

https://issues.apache.org/jira/browse/TIKA-2034

**Comment by tballison** [comment]
Y, I just pinged our contact at Adobe.

**Comment by tballison** [comment]
Many thanks to Simo Tripodi, 5.1.3 has just been pushed... as well as quite a few in the [6.x branch](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.adobe.xmp%22%20AND%20a%3A%22xmpcore%22)

**Comment by drewnoakes** [comment]
Interesting. Do you know why the Adobe page for XMPCore only suggests 5.1.3 and not anything from the 6.x branch?

http://www.adobe.com/devnet/xmp/library/eula-xmp-library-java.html

**Comment by drewnoakes** [comment]
To see code changes between versions of Adobe's XMPCore, this repo has a reconstruction:

https://github.com/drewnoakes/adobe-xmp-core

**Comment by drewnoakes** [comment]
Closing this for now, as 5.1.3 is merged. Will consider 6.x separately.

**Comment by tballison** [comment]
> Do you know why the Adobe page for XMPCore only suggests 5.1.3 and not anything from the 6.x branch?

The feedback I got from Adobe was that they aren't putting resources into supporting public release.  However, Simone Tripodi kindly pushed the latest versions.  Many thanks to Jukka Zitting for putting us in touch with Simone.

**Comment by drewnoakes** [comment]
Thank you for following up, and to Adobe for supporting open source and XMP.

**Comment by andygale** [comment]
Hi, I am observing an XXE vulnerability using version metadata-extractor-2.11.0
If I exclude XmpReader (By passing in the list of readers), then the problem goes away.
Should this issue be re-opened? (Or should a new one be filed?)
I have not looked into newer versions of XMPCore

**Comment by drewnoakes** [comment]
@andygale how are you observing it? What version of xmpcore are you running? If it's 5.1.3 or newer then please open a new issue.

**Comment by andygale** [comment]
My bad.  I had upgraded to metadata-extractor-2.11.0, but due to an oddity in our dependency management system I was still using an older version of xmpcore.  Forcing the new version of xmpcore fixes the issue.   Sorry for the false alarm.
