### ISSUE TITLE
Iphone 6 - IOS9.3.5

### ISSUE THREAD

**Issue by bomberivo** [drewnoakes/metadata-extractor#196]
Last week I upload the IOS on my Iphone 6 smartphone to version 9.3.5 and now I'm not still able to read all metadata from pictures using my Java application. In particular I can't see tag referred to picture creation date/time (<exif subifd><date/time original>) and GPS coordinates.

I think something is changed on the IOS side.

Except for this the library is great.

![img_1570](https://cloud.githubusercontent.com/assets/22172914/18475282/20dfc882-79c6-11e6-9ddd-937f6d8932a1.JPG)

**Comment by drewnoakes** [comment]
It looks like there's no GPS data in that photo. Perhaps you have some privacy setting that excludes such data from the image.

* http://regex.info/exif.cgi?imgurl=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F22172914%2F18475282%2F20dfc882-79c6-11e6-9ddd-937f6d8932a1.JPG
* http://metapicz.com/#landing?imgsrc=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F22172914%2F18475282%2F20dfc882-79c6-11e6-9ddd-937f6d8932a1.JPG

Thanks for your interest in the library. Feel free to reopen if I closed this incorrectly.
