### ISSUE TITLE
Upgraded to 2.9.1 and now getDirectory symbol not found

### ISSUE THREAD

**Issue by codeguy007** [drewnoakes/metadata-extractor#199]
I upgraded to 2.9.1 in hopes of better support for different jpeg formats but now my code doesn't compile. I get an error saying that the getDirectory symbol is not found for ExifSubIFDDirectory and ExifIFD0Directory. I have both included

import com.drew.imaging.ImageMetadataReader;
import com.drew.imaging.ImageProcessingException;
import com.drew.metadata.Metadata;
import com.drew.metadata.Tag;
import com.drew.metadata.exif.ExifIFD0Directory;
import com.drew.metadata.exif.ExifSubIFDDirectory;

and this code worked fine with 2.6.4

	public static Date get_Exif_Date(File imagefile) throws ImageProcessingException, IOException {
		Metadata metadata =ImageMetadataReader.readMetadata(imagefile);
		Date date = null;
		
		ExifSubIFDDirectory dir;
                dir = metadata.getDirectory(ExifSubIFDDirectory.class);
		try {
			date = dir.getDate(ExifSubIFDDirectory.TAG_DATETIME_ORIGINAL);
		}
		catch (NullPointerException NPe) {
			date = new Date(imagefile.lastModified());
		}
		return date;
		
	}

Can someone tell me what I need to change here? I have tried clean and rebuilding the project.

**Comment by codeguy007** [comment]
I resolved this issue by using the getFirstDirectoryOfType instead of getDirectory which I guess has been removed.

**Comment by drewnoakes** [comment]
Yes, the API changed in 2.8.0 when it became possible to have multiple instances of the same type of directory in a metadata object.

**Comment by drewnoakes** [comment]
@rajesh-rockwell the library exposes whatever data is in the file. A file might have multiple instances of a given directory. It's unlikely for certain types of directory, but for others it's common.
