### ISSUE TITLE
Extracting metadata from GIF

### ISSUE THREAD

**Issue by Omnipresent** [drewnoakes/metadata-extractor#201]
From this image I can read xmp data using exiftool

```
$ exiftool -comment="This is a comment for testing" giphy_s.gif
    1 image files updated
$ exiftool -xmp-dc:subject=foobarisawesome giphy_s.gif
    1 image files updated
$ exiftool giphy_s.gif | grep "Subject"
Subject                         : foobarisawesome
$ exiftool giphy_s.gif | grep "comment"
Comment                         : This is a comment for testing
```

However, metadata-extractor can't seem to extract this metadata. Below is what I get from metadata-extractor. 

```
[GIF Header] GIF Format Version - 89a
[GIF Header] Image Width - 500
[GIF Header] Image Height - 375
[GIF Header] Color Table Size - 256
[GIF Header] Is Color Table Sorted - false
[GIF Header] Bits per Pixel - 8
[GIF Header] Has Global Color Table - true
[GIF Header] Background Color Index - 0
```

The code I'm using to print tags:

```
            for (XmpDirectory xmpDirectory : metadata.getDirectoriesOfType(XmpDirectory.class)) {
                XMPMeta xmpMeta = xmpDirectory.getXMPMeta();
                XMPIterator itr = xmpMeta.iterator();
                while (itr.hasNext()) {
                    XMPPropertyInfo property = (XMPPropertyInfo) itr.next();
                    System.out.println(property.getPath() + ": " + property.getValue());
                }
            }

            for (Directory directory : metadata.getDirectories()) {
                for (Tag tag : directory.getTags()) {
                        System.out.println(tag);
                    }
                }
```

![giphy_s](https://cloud.githubusercontent.com/assets/115446/19787144/2b00d038-9c6f-11e6-904d-91c5ff68ccac.gif)

**Comment by drewnoakes** [comment]
Thanks for the sample image.

Current GIF support only pulls out values from the file's header. There might also be XMP and ICC data in the file which would be good to get as well.

This file has two XMP packets. They both contain the same contents however:

```xml
<?xpacket begin='ï»¿' id='W5M0MpCehiHzreSzNTczkc9d'?>
<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='Image::ExifTool 9.34'>
  <rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'>
    <rdf:Description rdf:about=''.  xmlns:dc='http://purl.org/dc/elements/1.1/'>
      <dc:subject>
        <rdf:Bag>
          <rdf:li>foobarisawesome</rdf:li>
        </rdf:Bag>
      </dc:subject>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
```

I see no mention of the comment string `This is a comment for testing` in a hex dump, and http://regex.info/exif.cgi doesn't show the comment either, so I think this image doesn't have the comment you mention. Regardless, it should have ended up in the XMP data. I don't know why there are two packets though.

I'll take a further look at this as time permits.

**Comment by kwhopper** [comment]
If the .NET PR works and is accepted, the changes there shouldn't be too difficult to port if you want to use that as a reference.

**Comment by drewnoakes** [comment]
For reference: the .NET version now supports XMP, ICC and other forms of metadata in GIF files. See drewnoakes/metadata-extractor-dotnet@e01d19cfd464e64afb2ed789f60968cc8286a1c0.

**Comment by drewnoakes** [comment]
Closed thanks to @kwhopper's PR. @Omnipresent take a look if you can. We'll get a release upon on Maven Central soon.
