### ISSUE TITLE
Fastest way to get XMP-dc Creator value?

### ISSUE THREAD

**Issue by PeterCodar** [drewnoakes/metadata-extractor#209]
I try to extract only one specific XMP exiftag. Phil Harveys Exiftool.exe extract this tag as Creator
```
---- XMP-dc ----
...
Creator                         : James T. Kirk
...
Subject                         : Arts Culture and Entertainment, Starfleet 
...
```
The Subject(s) in the same group can easily be read (in VB.NET) with 
```
Dim AllTags = ImageMetadataReader.ReadMetadata(SingleJPGPictureName)
Dim XMPDirectory = AllTags.OfType(Of Formats.Xmp.XmpDirectory).FirstOrDefault()
Dim XMPSubjects() = XMPDirectory.GetStringArray(Formats.Xmp.XmpDirectory.TagSubject)
```
What is the reason that you don't offer all available tags to be read directly from XMP like .TagSubject?
I know this Wiki article: https://github.com/drewnoakes/metadata-extractor/wiki/XMP
but I don't unerstand, why you make a difference between Subject and Creator (and other XMP-dc tags).

What would be the fastest way to get the value "James T. Kirk" from "Creator" in XMP-dc?

Do I really have to loop through all `XMPDirectory.XmpMeta.Properties` and search for` .Path = "dc:rights[1]"`?

.PS
_Please let me know where I should place such a question if an issue would be the wrong channel._

**Comment by drewnoakes** [comment]
To access a single value, use the `GetProperty(namespace, propName)` method.

I would actually like to remove all the XMP tags from XmpDirectory as they just confuse users. The selection there is arbitrary, and could never be complete.
