### ISSUE TITLE
metadata-extractor exception when trying to read Reconyx Ultrafire image metadata

### ISSUE THREAD

**Issue by saulgreenberg** [drewnoakes/metadata-extractor#211]
Produces a 'System.ArgumentOutOfRangeExcepton', with additional information: Year, Month, and Day parameters describe an unrepresentable DateTime. 

Because this isn't caught gracefully, none of the other metadata can be read. An example Hyperfire image is attached.
![reconyx-hyperfire-hc500](https://cloud.githubusercontent.com/assets/15931952/21272034/c7096152-c37a-11e6-9120-e108a6fcc5a8.jpg)

**Comment by drewnoakes** [comment]
Thanks for the report. To be clear, this applies to the [.NET library](https://github.com/drewnoakes/metadata-extractor-dotnet), not this, the Java one.

**Comment by drewnoakes** [comment]
Which version of the library are you using?

**Comment by saulgreenberg** [comment]
Yes, .net version 1.5.3 acquired via nuget


On Dec 20, 2016, at 7:20 AM, Drew Noakes <notifications@github.com<mailto:notifications@github.com>> wrote:


Which version of the library are you using?

-

**Comment by drewnoakes** [comment]
Please test again using `2.0.0-rc2` prerelease version from NuGet. I don't see the exception you refer to with that build.

```text
[JPEG] Compression Type = Baseline
[JPEG] Data Precision = 8 bits
[JPEG] Image Height = 1080 pixels
[JPEG] Image Width = 1920 pixels
[JPEG] Number of Components = 3
[JPEG] Component 1 = Y component: Quantization table 0, Sampling factors 2 horiz/1 vert
[JPEG] Component 2 = Cb component: Quantization table 1, Sampling factors 1 horiz/1 vert
[JPEG] Component 3 = Cr component: Quantization table 1, Sampling factors 1 horiz/1 vert
[Exif IFD0] Make = RECONYX
[Exif IFD0] Model = HC500 HYPERFIRE
[Exif IFD0] X Resolution = 72 dots per inch
[Exif IFD0] Y Resolution = 72 dots per inch
[Exif IFD0] Resolution Unit = Inch
[Exif IFD0] Date/Time = 2016:04:19 15:03:00
[Exif IFD0] YCbCr Positioning = Datum point
[Exif SubIFD] Exposure Time = 1/576 sec
[Exif SubIFD] ISO Speed Ratings = 50
[Exif SubIFD] Exif Version = 2.20
[Exif SubIFD] Date/Time Original = 2016:04:19 15:03:00
[Exif SubIFD] Date/Time Digitized = 2016:04:19 15:03:00
[Exif SubIFD] Components Configuration = YCbCr
[Exif SubIFD] Flash = Flash did not fire, auto
[Exif SubIFD] FlashPix Version = 1.00
[Exif SubIFD] Color Space = sRGB
[Exif SubIFD] Exif Image Width = 1920 pixels
[Exif SubIFD] Exif Image Height = 1080 pixels
[Exif SubIFD] Exposure Mode = Auto exposure
[Exif SubIFD] White Balance Mode = Manual white balance
[Exif SubIFD] Scene Capture Type = Standard
[Reconyx HyperFire Makernote] Makernote Version = 61697
[Reconyx HyperFire Makernote] Firmware Version = 4.1.0.20150317
[Reconyx HyperFire Makernote] Trigger Mode = T
[Reconyx HyperFire Makernote] Sequence = 0/0
[Reconyx HyperFire Makernote] Event Number = 5001
[Reconyx HyperFire Makernote] Date/Time Original = 2016:04:19 15:03:00
[Reconyx HyperFire Makernote] Moon Phase = Waxing Gibbous
[Reconyx HyperFire Makernote] Ambient Temperature Fahrenheit = 87
[Reconyx HyperFire Makernote] Ambient Temperature = 30
[Reconyx HyperFire Makernote] Serial Number = H500HI11244984
[Reconyx HyperFire Makernote] Contrast = 128
[Reconyx HyperFire Makernote] Brightness = 0
[Reconyx HyperFire Makernote] Sharpness = 64
[Reconyx HyperFire Makernote] Saturation = 154
[Reconyx HyperFire Makernote] Infrared Illuminator = Off
[Reconyx HyperFire Makernote] Motion Sensitivity = 100
[Reconyx HyperFire Makernote] Battery Voltage = 9.550
[Reconyx HyperFire Makernote] User Label = HC500 HYPERFIRE
[File] File Name = Issue 211.jpg
[File] File Size = 358588 bytes
[File] File Modified Date = Tue Dec 20 14:10:46 +00:00 2016
```

Closing this for now. If you still see a problem I will reopen.

**Comment by saulgreenberg** [comment]
Will try it with the pre release and will report back

Saul Greenberg
Sent from my iPhone with the usual bizarre spelling corrections

On Dec 20, 2016, at 7:47 AM, Drew Noakes <notifications@github.com<mailto:notifications@github.com>> wrote:


Please test again using 2.0.0-rc2 prerelease version from NuGet. I don't see the exception you refer to with that build.

[JPEG] Compression Type = Baseline
[JPEG] Data Precision = 8 bits
[JPEG] Image Height = 1080 pixels
[JPEG] Image Width = 1920 pixels
[JPEG] Number of Components = 3
[JPEG] Component 1 = Y component: Quantization table 0, Sampling factors 2 horiz/1 vert
[JPEG] Component 2 = Cb component: Quantization table 1, Sampling factors 1 horiz/1 vert
[JPEG] Component 3 = Cr component: Quantization table 1, Sampling factors 1 horiz/1 vert
[Exif IFD0] Make = RECONYX
[Exif IFD0] Model = HC500 HYPERFIRE
[Exif IFD0] X Resolution = 72 dots per inch
[Exif IFD0] Y Resolution = 72 dots per inch
[Exif IFD0] Resolution Unit = Inch
[Exif IFD0] Date/Time = 2016:04:19 15:03:00
[Exif IFD0] YCbCr Positioning = Datum point
[Exif SubIFD] Exposure Time = 1/576 sec
[Exif SubIFD] ISO Speed Ratings = 50
[Exif SubIFD] Exif Version = 2.20
[Exif SubIFD] Date/Time Original = 2016:04:19 15:03:00
[Exif SubIFD] Date/Time Digitized = 2016:04:19 15:03:00
[Exif SubIFD] Components Configuration = YCbCr
[Exif SubIFD] Flash = Flash did not fire, auto
[Exif SubIFD] FlashPix Version = 1.00
[Exif SubIFD] Color Space = sRGB
[Exif SubIFD] Exif Image Width = 1920 pixels
[Exif SubIFD] Exif Image Height = 1080 pixels
[Exif SubIFD] Exposure Mode = Auto exposure
[Exif SubIFD] White Balance Mode = Manual white balance
[Exif SubIFD] Scene Capture Type = Standard
[Reconyx HyperFire Makernote] Makernote Version = 61697
[Reconyx HyperFire Makernote] Firmware Version = 4.1.0.20150317
[Reconyx HyperFire Makernote] Trigger Mode = T
[Reconyx HyperFire Makernote] Sequence = 0/0
[Reconyx HyperFire Makernote] Event Number = 5001
[Reconyx HyperFire Makernote] Date/Time Original = 2016:04:19 15:03:00
[Reconyx HyperFire Makernote] Moon Phase = Waxing Gibbous
[Reconyx HyperFire Makernote] Ambient Temperature Fahrenheit = 87
[Reconyx HyperFire Makernote] Ambient Temperature = 30
[Reconyx HyperFire Makernote] Serial Number = H500HI11244984
[Reconyx HyperFire Makernote] Contrast = 128
[Reconyx HyperFire Makernote] Brightness = 0
[Reconyx HyperFire Makernote] Sharpness = 64
[Reconyx HyperFire Makernote] Saturation = 154
[Reconyx HyperFire Makernote] Infrared Illuminator = Off
[Reconyx HyperFire Makernote] Motion Sensitivity = 100
[Reconyx HyperFire Makernote] Battery Voltage = 9.550
[Reconyx HyperFire Makernote] User Label = HC500 HYPERFIRE
[File] File Name = Issue 211.jpg
[File] File Size = 358588 bytes
[File] File Modified Date = Tue Dec 20 14:10:46 +00:00 2016


Closing this for now. If you still see a problem I will reopen.

-

**Comment by saulgreenberg** [comment]
FYI: confirming that prerelease 2.0.0.0-rc2 fixes that bug. Thanks much!
Saul
