### ISSUE TITLE
Minimum supported JDK misrepresented

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor#218]
(From #216)

> Your POM states Java 1.5, but it won't compile until Java 1.6 since `DecimalFormat.setRoundingMode()` is used many places and wasn't introduced until Java 1.6.

If anyone needs JDK 1.5 support, please speak up now. Otherwise the POM will likely be updated to state 1.6.

**Comment by Nadahar** [comment]
@drewnoakes It hasn't actually been Java 1.5 since you started using ```DecimalFormat.setRoundingMode()``` even though the POM states it. If it's been like that a while and no issues have come up, I'd say you already have your answer.

**Comment by drewnoakes** [comment]
@Nadahar you're right, though I'd still like to know whether anyone following the project needs 1.5 support (they may not have upgraded yet), as there's two ways this can go -- bump POM to 1.6, or drop code to 1.5.

I'm leaning towards bumping POM, but will let other users chime in before doing so.

**Comment by drewnoakes** [comment]
Just installed JDK 5 to see how hard it would be to maintain 1.5 support.

`DecimalFormat.setRoundingMode` can probably be replaced some `BigDecimal` tomfoolery:

    new BigDecimal(number).setScale(N, BigDecimal.ROUND_HALF_UP)

An additional issue: there's no ctor `String(byte[], Charset)`, though it's possible to pass the charset name instead.

*HOWEVER* Adobe's XMP Core 5.1.3 targets 1.6. So without losing that dependency, we cannot maintain 1.5 support.

I'll update the project, and uninstall JDK 1.5.
