### ISSUE TITLE
I'm getting directory null for all images

### ISSUE THREAD

**Issue by rameshT108** [drewnoakes/metadata-extractor#229]

**Comment by drewnoakes** [comment]
Please attach a sample image and show your code.

**Comment by rameshT108** [comment]
Hello ,
Thanks for the reply.
Code as simple as
 Metadata metadata = ImageMetadataReader.readMetadata(imageFile);
        Directory directory = metadata.getFirstDirectoryOfType(ExifIFD0Directory.class);
        JpegDirectory jpegDirectory = metadata.getFirstDirectoryOfType(JpegDirectory.class);

        int orientation = 1;
        try {
            orientation = directory.getInt(ExifIFD0Directory.TAG_ORIENTATION);
        } catch (MetadataException me) {
            me.printStackTrace();
        }
![img-20161224-wa0004](https://cloud.githubusercontent.com/assets/20964693/22235258/77cfe250-e224-11e6-99c8-d6d438a47a56.jpg)

**Comment by drewnoakes** [comment]
Looks like there's no `ExifIFD0Directory` in that image. Running it through the tooling I see:

```text
[JPEG] Compression Type = Baseline
[JPEG] Data Precision = 8 bits
[JPEG] Image Height = 960 pixels
[JPEG] Image Width = 1280 pixels
[JPEG] Number of Components = 3
[JPEG] Component 1 = Y component: Quantization table 0, Sampling factors 2 horiz/2 vert
[JPEG] Component 2 = Cb component: Quantization table 1, Sampling factors 1 horiz/1 vert
[JPEG] Component 3 = Cr component: Quantization table 1, Sampling factors 1 horiz/1 vert
[JFIF] Version = 1.1
[JFIF] Resolution Units = none
[JFIF] X Resolution = 1 dot
[JFIF] Y Resolution = 1 dot
[JFIF] Thumbnail Width Pixels = 0
[JFIF] Thumbnail Height Pixels = 0
[File] File Name = Issue 229.jpg
[File] File Size = 175938 bytes
[File] File Modified Date = Tue Jan 24 09:14:36 +00:00 2017
```

**Comment by drewnoakes** [comment]
Closing this as you didn't respond. If you still have trouble, let us know.
