### ISSUE TITLE
DecimalFormat is not thread-safe

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor#237]
We use DecimalFormat in fields in a few places. Turns out, surprisingly, that the class isn't thread-safe, thanks to [this comment by @Nadahar](https://github.com/drewnoakes/metadata-extractor/pull/233#issuecomment-277269865).

Create a new one each time instead.

**Comment by drewnoakes** [comment]
Looking at the source from Oracle's JDK, I don't see a threading issue. In fact they synchronise some operations internally, and all state is on the stack it seems. However if the spec says it's not threadsafe, other implementations might not be.

**Comment by kwhopper** [comment]
I don't know if it's desirable, but here's a short post on a ThreadLocal option:

[http://jonamiller.com/2015/12/21/decimalformat-is-not-thread-safe/](http://jonamiller.com/2015/12/21/decimalformat-is-not-thread-safe/)

Java isn't my forte so if the version you're targeting doesn't support it...

**Comment by drewnoakes** [comment]
@kwhopper hey sorry I didn't see your comment before pushing a fix for this. Looks like thread local support has been around since JDK 1.2, so I don't see a problem  there.
