### ISSUE TITLE
new Release

### ISSUE THREAD

**Issue by george84** [drewnoakes/metadata-extractor#238]
Would be nice to have a new release. It is almost a year since 2.9.1

**Comment by drewnoakes** [comment]
Fair. #217 is the only outstanding issue slated for 2.10.0, and that could spill to a subsequent release.

**Comment by drewnoakes** [comment]
Done. 2.10.0 is available (might take a few minutes before public). Please check it out and let us know if you have any troubles. Thanks.

**Comment by george84** [comment]
Thank you. Checks will take some time.

Am 10.02.2017 05:16 schrieb "Drew Noakes" <notifications@github.com>:

**Comment by george84** [comment]
I wanted to use the new release, but realized there is no jar file. Up to 2.9.1 there was always provided a jar, so for me a release meant a jar file. Sorry I wasn't more precise. Thank you

**Comment by drewnoakes** [comment]
You can download the JAR files directly from Maven:

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.drewnoakes%22%20AND%20a%3A%22metadata-extractor%22

You'll also need the XMPCore JAR from Adobe:

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.adobe.xmp%22%20AND%20a%3A%22xmpcore%22
