### ISSUE TITLE
How do I extract metadata from .mov and .mp4 videos?

### ISSUE THREAD

**Issue by davidekholm** [drewnoakes/metadata-extractor#244]
I'm currently transitioning jAlbum from an old version of metadata-extractor
 to the current one.
According to https://drewnoakes.com/code/exif/ metadata-extractor should support .mov and .mp4 video file types too, but when I try to extract metadata using ImageMetadataReader I get a "File format is not supported" error. What am I doing wrong? I see no other API for this.

Here's a copy of the sample .mov video. It should have a xmp IPTC section within it according to Adobe Bridge: http://jalbum.net/download/sample.mov

**Comment by drewnoakes** [comment]
Hi David,

Long time! Glad to see you and jAlbum going strong.

I should make the statement less ambiguous. Actually the .NET version supports QuickTime formatted video, but that hasn't been ported to the Java library yet. The task should be pretty straightforward I expect.

The relevant code is here, mostly in the `QuickTimeReader` and `QuickTimeMetadataReader` classes:

https://github.com/drewnoakes/metadata-extractor-dotnet/tree/master/MetadataExtractor/Formats/QuickTime

Issue #127 is tracking this, so I'll close this issue if you don't mind.
