### ISSUE TITLE
Possible issue with NEF format originating from Nikon D70

### ISSUE THREAD

**Issue by ghost** [drewnoakes/metadata-extractor#247]
I have a a collection of native format images from various Nikon camera (D70, D3300 and D750) and various JPG files from iPhone, Nikon and Canon cameras. I am trying to run the ProcessAllImagesInFolderUtility (args: --markdown /Volumes/Photos/Images/NEF) sample against a folder containing both raw image and jpg files and noticed errors being generated against a lot of files; a sample of the error output is included below:

```
/Volumes/Photos/Images/NEF/07369File.NEF
	[IPTC] Invalid IPTC tag marker at offset 21. Expected '0x1c' but got '0x0'.
/Volumes/Photos/Images/NEF/07371File.NEF
	[IPTC] Invalid IPTC tag marker at offset 21. Expected '0x1c' but got '0x0'.
/Volumes/Photos/Images/NEF/07706File.NEF
	[IPTC] Too few bytes remain for a valid IPTC tag
/Volumes/Photos/Images/NEF/07707File.NEF
	[IPTC] Too few bytes remain for a valid IPTC tag
/Volumes/Photos/Images/NEF/07708File.NEF
	[IPTC] Too few bytes remain for a valid IPTC tag
/Volumes/Photos/Images/NEF/07709File.NEF
	[IPTC] Too few bytes remain for a valid IPTC tag
```

All the file listed originate from a Nikon D70 and render perfectly well through the MAC finder, Apple Photos and the Nikon Capture NX-D running on OS X El Capitan. I can also see limited metadata details through the Finder Get Info option and comprehensive metadata in Nikon Capture NX-D. 

Has anyone seen similar issues or can anyone provide any pointers?

thanks.

Dermot

Images attached.

[D70-Images.zip](https://github.com/drewnoakes/metadata-extractor/files/798308/D70-Images.zip)

**Comment by drewnoakes** [comment]
Thanks for this. Those files contains mostly blank (zero-length) IPTC values. The library incorrectly assumed there'd always be one byte in the value portion. In the end it was a simple off-by-one bug.

However the images you provided only covered the _Too few bytes remain for a valid IPTC tag_ bug, not the _Invalid IPTC tag marker at offset_ problem.
