### ISSUE TITLE
Extracting embedded JPEG from Nikon NEF

### ISSUE THREAD

**Issue by connyhald** [drewnoakes/metadata-extractor#262]
Nikon raw files (NEF) have an embedded full-size JPEG included inside the EXIF header. I'm trying to extract that.

Using exiftool this would be:
```
$ exiftool -b -JpgFromRaw DSC_0001.NEF > out.jpg
```
or
```
$ exiftool -JpgFromRaw DSC_0001.NEF
Jpg From Raw   : (Binary data 1737279 bytes, use -b option to extract)
```

Running the following code
```
ExifSubIFDDirectory directory = metadata.getFirstDirectoryOfType(ExifSubIFDDirectory.class);
for (Tag tag : directory.getTags()) {
    logger.debug("[{}] - {} = {}", directory.getName(), tag.getTagName(), tag.getDescription());
}
```
results in
```
[Exif SubIFD] - New Subfile Type = Reduced-resolution image
[Exif SubIFD] - Compression = JPEG (old-style)
[Exif SubIFD] - X Resolution = 300 dots per inch
[Exif SubIFD] - Y Resolution = 300 dots per inch
[Exif SubIFD] - Resolution Unit = Inch
[Exif SubIFD] - Unknown tag (0x0201) = 1080832
[Exif SubIFD] - Unknown tag (0x0202) = 1737279
[Exif SubIFD] - YCbCr Positioning = Datum point
```

Now, comparing file sizes (```1737279```) with exiftools I figured ```0x0202``` should be the right one. So I do
```
byte[] imgData = directory.getByteArray(0x0202);
```
which results in imgData being null.

Am I doing it wrong or is this currently not possible with metadata-extractor?

**Comment by drewnoakes** [comment]
`0x0201` is thumbnail offset, and `0x0202` is thumbnail length. The library should identify these tags property (I've created issue #263).

With these two values, you should be able to extract the thumbnail from the original file. Unfortunately the offset is relative to the beginning of Exif data, not to the beginning of the file.

The library could help with this. Just need to find the right API, and deal with a few edge cases.

Some prior discussion about this happened here:

https://github.com/drewnoakes/metadata-extractor/commit/5371827edfbed4dde6f5e8188ea48a53cce8bedb#commitcomment-20668173

**Comment by connyhald** [comment]
Thanks for the quick response and the explanation. Makes sense now. I'll see how I can extract it semi-manual then.

**Comment by drewnoakes** [comment]
#149

**Comment by connyhald** [comment]
So it looks like the offset is actually already relativ to the beginning of the file. At least with NEF files.

The following code works for me. Only tested with NEF coming from Nikon D5500. Maybe it is usefull for others as well.

```
    public byte[] extractJpegFromRaw(InputStream inStream) {

        try {
            Metadata metadata = ImageMetadataReader.readMetadata(inStream);

            ExifSubIFDDirectory directory = metadata.getFirstDirectoryOfType(ExifSubIFDDirectory.class);

            int offset = directory.getInt(0x0201);
            int length = directory.getInt(0x0202);

            logger.info("Embedded jpeg offset: " + offset);
            logger.info("Embedded jpeg length: " + length);

            inStream.reset();
            inStream.skip(offset);

            byte[] jpegData = new byte[length];
            inStream.read(jpegData, 0, length);

            return jpegData;

        } catch (IOException | MetadataException | ImageProcessingException e) {
            e.printStackTrace();
            return new byte[0];
        }

    }

```
