### ISSUE TITLE
Add check for unknown marker(or unused space) in GIF

### ISSUE THREAD

**Issue by saurabheights** [drewnoakes/metadata-extractor#264]
In [GifReader.java#L121](https://github.com/drewnoakes/metadata-extractor/blob/master/Source/com/drew/metadata/gif/GifReader.java#L121), it would be better to improve the existence of such condition. Before `return;`, adding an ErrorDirectory is preferrable. This way at least one can easily find if the image has some corruption or not. This will also notify earlier if Gif87a format is not properly handled as given in comments by Kevin Mott. 

A pr if the signal is green, I can add. No trouble, it will be.

**Comment by drewnoakes** [comment]
Sounds good. Give it a shot against the image database and see how the output differs before/after.

**Comment by saurabheights** [comment]
Five files shows changed diff. Give me a day to fix the issue. Will add PR for both Error Directory and reading the unknown metadata.

Attached diff.
[GifUnknownBlockMarker.txt](https://github.com/drewnoakes/metadata-extractor/files/925540/GifUnknownBlockMarker.txt)

**Comment by saurabheights** [comment]
Hi Drew, 
 I checked all 4 files and seems this is just corrupt data. I have added output for reading and writing with gifsicle as well. A PR for this, I have added.

```
> filebasename=0646caeb9b9161c777f117007921a687
> gifsicle "${filebasename}.gif" -o "${filebasename}_1.gif"
gifsicle:0646caeb9b9161c777f117007921a687.gif:#7: read error: unknown block type 0 at file offset 16834
> filebasename=243d9798466d64aba0acaa41f980bea6
> gifsicle "${filebasename}.gif" -o "${filebasename}_1.gif"
gifsicle:243d9798466d64aba0acaa41f980bea6.gif:#3: read error: bad graphic extension (66 times)
> filebasename=7092f253998c1b6b869707ad7ae92854
> gifsicle "${filebasename}.gif" -o "${filebasename}_1.gif"
gifsicle:7092f253998c1b6b869707ad7ae92854.gif:#3: read error: bad graphic extension (66 times)
> filebasename=ce774930ac70449f38a18789c70095b8
> gifsicle "${filebasename}.gif" -o "${filebasename}_1.gif"
gifsicle:ce774930ac70449f38a18789c70095b8.gif:#5: read error: unknown block type 56 at file offset 39780
```

**Comment by saurabheights** [comment]
Just for context and for other users, the best library for handling gif files IMO is gifsicle however it fails to handle images with corrupt frames. The PR for this issue allows us to at least check such corruption issue in gif files.
