### ISSUE TITLE
8BIM Clipping Path Name and Path Information Support

### ISSUE THREAD

**Issue by PaytonGarland** [drewnoakes/metadata-extractor#266]
Currently, PhotoshopReader extracts the bytes of the Path and Clipping Path Name image resource blocks and PhotoshopDescriptor does not process the bytes for display.  I am working on adding this functionality to process and display all of the subpaths and other records (9 record types in total) of each path.  The Clipping Path Name is a much simpler solution as it is just converting x amount of bytes to ascii.  As of right now, I have Clipping Path Name working along with the selectors for the different subpath types.  That leaves 3 more selectors that I need to work on.  I can make a pull request sometime next week if this is something of interest to add.  I have the selectors printing on new lines just for show.  I'm assuming all of the descriptions should only be on one line like the rest.  Thanks!

![clipping path name path information](https://cloud.githubusercontent.com/assets/12602866/26504909/3213fbe6-420c-11e7-97f8-856ae1766698.png)

**Comment by drewnoakes** [comment]
Looks good. A PR would be welcome, along with a sample image for the [image database](https://github.com/drewnoakes/metadata-extractor-images/wiki).

**Comment by PaytonGarland** [comment]
Great!  I will do that within the next couple of days.

**Comment by drewnoakes** [comment]
Thanks for fixing this!
