### ISSUE TITLE
Support Apple bplist in makernotes

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor#298]
Apple's `bplist` (binary property list) format is present in certain Apple camera images. The sample library currently has three hits:

- `Apple iPhone 6 plus.jpg`
- `Apple iPhone 6.jpg`
- `Issue 177.jpg` (iPhone 5s)

Currently these binary values are left undecoded:

```text
[Apple Makernote - 0x0002] Unknown tag (0x0002) = [558 values]
```

Resources:

- https://synalysis.com/how-to-decode-apple-binary-property-list-files/
- https://opensource.apple.com/source/CF/CF-635/CFBinaryPList.c
- https://github.com/joeferner/node-bplist-creator/blob/master/bplistCreator.js

**Comment by BobJohnsonGitHub** [comment]
I can pick up this issue - I have a fork where I'm adding a couple more Apple tags and have a bare-bones BPLIST reader for the RUN_TIME tag

**Comment by drewnoakes** [comment]
@BobJohnsonGitHub that sounds great. Feel free to open a PR up while you're working on it if you'd like to get feedback or have questions along the way.

**Comment by BobJohnsonGitHub** [comment]
Actually, I've got a question before I prepare any commits. The contribution guidelines call out JDK 1.5, but the POM specifies 1.6 (maven-compiler-plugin) - which one is the max level I can code to?

**Comment by drewnoakes** [comment]
@BobJohnsonGitHub I _think_ the code still compiles for 1.5 and it'd be nice to keep it that way if possible. Are there any APIs in 1.6 that you would like to use?

**Comment by BobJohnsonGitHub** [comment]
javax.xml.stream.XMLStreamWriter, XMLOutputStream for the production of the PLIST XML format.
I know you can just do String concatenation, but for elements and attributes that need escaping, I like to defer to this module when I can. 

The current solution I have provides the following:

- For 0x0002 tag, the binary PLIST is parsed from the makernote and `AppleMakernoteDescriptor.getDescription()` returns an XML-formatted PLIST structure (see output below).

- For 0x0003 tag, the binary PLIST is parsed but XML is not needed - the individual fields of the CMTime structure encoded into the PLIST are used. `AppleMakernoteDescriptor.getDescription()` returns a string ihe form of `%d seconds`

(data element is base-64 encoded, but I truncated for now)
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<data>
2wC4AKEA4wCkAOMA...
</data>
</plist>
```

If we limit the parser/XML renderer to *just* PLIST data chunk as above, I could probably safely just use a StringBuilder to concatenate.  What do you think?

The next hurdle with the older JDK would be the Base64-encoding though!  I don't want to face PR comments of submitting sun.misc.Base64

Here is the XML version of the PLIST for the 0x0003 (run time) tag (1.65 days):
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>flags</key>
  <integer>1</integer>
  <key>value</key>
  <integer>142872557123708</integer>
  <key>timescale</key>
  <integer>1000000000</integer>
  <key>epoch</key>
  <integer>0</integer>
</dict>
</plist>
```

**Comment by drewnoakes** [comment]
@BobJohnsonGitHub thanks for clarifying.

I hadn't considered producing XML from the BPLIST data. In general I favour an approach that keep consistency with the current directory based approach, so consumers can continue to iterate through directories and their values.

However I wonder if this this would come up against the same issue that we have with XMP, namely that the set of available entries is open and the library currently desires a fixed set of tags in directories.

Is there a known structure to the Apple makernote? If so, we could read the bplist directly into a new directory class, maintaining consistency across the various metadata types in the library.

In future I'd like to revisit how we model values so that the approach can be more flexible.

**Comment by BobJohnsonGitHub** [comment]
The 0x0003 field seems pretty well-defined since it is the CMTime structure. I can see if that one makes sense as another nested directory for field iteration. I could potentially do the same for 0x0002 and return the byte array encoded within. I might get a PR for you over the weekend

**Comment by BobJohnsonGitHub** [comment]
PR https://github.com/drewnoakes/metadata-extractor/pull/395 submitted for your review

**Comment by drewnoakes** [comment]
@BobJohnsonGitHub thanks again for the PR.
