### ISSUE TITLE
Question: When will maven get updated to the code that is in master?

### ISSUE THREAD

**Issue by clarencewin** [drewnoakes/metadata-extractor#299]
(Please include as much information as possible, and attach a sample image if possible.)
I'm looking at the source code and it looks like it supports MP4 files, however when I use maven to pull in the dependencies it pulls is version 2.10.1 built on 15-Feb-2017 the source code doesn't support MP4 files.

**Comment by drewnoakes** [comment]
Thanks for the reminder. I will work to get a release out next weekend.

**Comment by deviceqaing** [comment]
That will be very helpful!
Thank you!!

**Comment by laughmetal** [comment]
I am also looking for video format supports. Please upload latetest .jar file when you get time. Thank you!

**Comment by drewnoakes** [comment]
2.11.0 is up on Maven now and includes support for MP4 files, along with a tonne of other stuff.

Again, huge thanks to @PaytonGarland for all his amazing work on this release!
