### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by Thaval** [drewnoakes/metadata-extractor#302]
Hi,

Im would this library to edit some video tags (mp4 or flv) but it seems like there are some packages missing in my local repo, but they here on github. So... what's the matter?
No update yet? 
Im using the latest version "2.10.1" that is specified on the front page here.

**Comment by PaytonGarland** [comment]
Video support has not yet been included in any official releases yes. See #299

**Comment by drewnoakes** [comment]
2.11.0 is up on Maven now. Huge thanks to @PaytonGarland for all his amazing work on this release!
