### ISSUE TITLE
MP4 Directory cannot parse date for TAG_CREATION_TIME and TAG_MODIFICATION_TIME

### ISSUE THREAD

**Issue by lukiluuk** [drewnoakes/metadata-extractor#303]
I Just noticed that the new MP4 Metadata Parser cannot parse the date string into a Date object from TAG_CREATION_TIME and TAG_MODIFICATION_TIME (at least with a Samsung Galaxy S4). The following code returns null for mp4Date:

`Metadata metadata = ImageMetadataReader.readMetadata(file);
Mp4Directory mp4Directory = metadata.getFirstDirectoryOfType(Mp4Directory.class);
Date mp4Date = mp4Directory.getDate(Mp4Directory.TAG_CREATION_TIME);`

I tested it with a video taken with a Samsung Galaxy S4. The string content of TAG_CREATION_TIME was:
Sat Oct 28 08:38:37 CEST 2017

**Problem**
The problem is in `com.drew.metadata.Directory.getDate(int tagType, @Nullable String subsecond, @Nullable TimeZone timeZone)`. This type of date string is not yet defined in the datePatterns.
**Solution**
The following date pattern should be able to parse this type of date string (together with Locale.US):
`EEE MMM dd HH:mm:ss zzz yyyy`

Camera Model: Samsung Galaxy S4

**Comment by PaytonGarland** [comment]
Thank you for catching this.  I have created a PR #305 that resolves the issue.

**Comment by lukiluuk** [comment]
Thanks for fixing it. This fix is even simpler than my solution.
