### ISSUE TITLE
Investigate test coverage reports from coveralls.io

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor#31]
https://coveralls.io
https://coveralls.io/r/drewnoakes/metadata-extractor

Needs a `.coveralls.yml` file with appropriate settings.

**Comment by sksamuel** [comment]
I can help with this if you need.

**Comment by drewnoakes** [comment]
That would be great. Is this something that can be set up simply?

**Comment by sksamuel** [comment]
Pretty much. You need to add a coverage tool to your pom, so emma or cobertua. Any pref?

**Comment by drewnoakes** [comment]
No preference. Whatever is easiest to work with.

**Comment by drewnoakes** [comment]
Note to self:

- https://vzurczak.wordpress.com/2014/04/04/no-plugin-found-for-prefix/
- https://maven.apache.org/guides/introduction/introduction-to-plugin-prefix-mapping.html

**Comment by drewnoakes** [comment]
https://coveralls.io/r/drewnoakes/metadata-extractor
