### ISSUE TITLE
Support IOS11 HEIF format

### ISSUE THREAD

**Issue by maczikasz** [drewnoakes/metadata-extractor#310]
At the moment HEIF format is not supported

**Comment by drewnoakes** [comment]
@PaytonGarland, you said you looked at this a while back. Is there anything you can point to?

http://nokiatech.github.io/heif/
https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format

**Comment by PaytonGarland** [comment]
At the time that I was looking through it, I was having some issues finding enough documentation on it, but the MPEG site provided some helpful documentation on HEVC https://mpeg.chiariglione.org/standards/mpeg-h
The website/documentation isn't the easiest to navigate through.

I'll do some more digging for better documentation now that it has seen more light in iOS11

**Comment by Nadahar** [comment]
I think the [ISO/IEC 23008-12 itself](http://standards.iso.org/ittf/PubliclyAvailableStandards/c066067_ISO_IEC_23008-12_2017.zip) should have all the documentation you'd need 😉

**Comment by payton** [comment]
@maczikasz If you have any sample HEIF images you could contribute to https://github.com/drewnoakes/metadata-extractor-images, that would help with continued development.

**Comment by payton** [comment]
Just to keep this issue updated, I am working on adding some of the image properties (as specified in ISO/IEC 23008-12:2017 in section 6.5).
https://github.com/payton/metadata-extractor/tree/heif-image-properties

Currently, I have added Image Rotation, Pixel Information, and Colour Information. These will extract image rotation (in degrees counter-clockwise), ICC Profile, and bits per channel (pixel depth). A PR will be made soon. These are the only properties I am able to test at the moment. We will be able to add more when we get sample images.

**Comment by Sami32** [comment]
@payton In case you still need some image samples:
http://ge.tt/2tRPVos2

**Comment by grizzly100** [comment]
Hi. Great library Drew.

I wrote this class to integrate the Nokia HEIF reference implementation.

https://github.com/grizzly100/metamorphosis/blob/master/src/main/java/org/grizzlytech/metamorphosis/imaging/heif/HEIFMetadataReader.java

I only wanted “date taken”, but the sample shows your library nicely parses the bytes returned by the Nokia native library.

**Comment by zosatapo** [comment]
> At the moment HEIF format is not supported

https://github.com/zosatapo/metadata-extractor-heif

> Hi. Great library Drew.
> I wrote this class to integrate the Nokia HEIF reference implementation.
> https://github.com/grizzly100/metamorphosis/blob/master/src/main/java/org/grizzlytech/metamorphosis/imaging/heif/HEIFMetadataReader.java
> I only wanted “date taken”, but the sample shows your library nicely parses the bytes returned by the Nokia native library.

 pure Java , based on metadata-extractor , support heic/heif
https://github.com/zosatapo/metadata-extractor-heif

**Comment by drewnoakes** [comment]
@zosatapo can you submit a pull request so that your work can be used by existing users of this library?

**Comment by zosatapo** [comment]
I have submitted a pull request  to extract EXIF metadata  for HEIF format , please verify it. 1.  change SequentialReader to RandomAccessReader  for reading  EXIF data buffer  from HEIF meta BOX 2.  modify HeifHandler to extract EXIF location with  ItemInfoBox  and ItemLocatonBox 发自我的华为手机-------- 原始邮件 --------发件人： Drew Noakes <notifications@github.com>日期： 2019年11月11日周一 上午9:01收件人： drewnoakes/metadata-extractor <metadata-extractor@noreply.github.com>抄送： zosatapo <zosatapo@139.com>, Mention <mention@noreply.github.com>主    题： Re: [drewnoakes/metadata-extractor] Support IOS11 HEIF format (#310)@zosatapo can you submit a pull request so that your work can be used by existing users of this library?

**Comment by lfcnassif** [comment]
hi @zosatapo thank you for your work! With your implementation it is possible to get heif thumbnail? Is it stored inside exif data?

**Comment by ahao140202** [comment]
this issue should be closed, 2.16.0 resolved it

**Comment by drewnoakes** [comment]
@ahao140202 thank you!
