### ISSUE TITLE
How can read video metadata

### ISSUE THREAD

**Issue by debjitk** [drewnoakes/metadata-extractor#323]
How can read video metadata like quality, duration, ...

**Comment by payton** [comment]
Video metadata can be read in a couple ways. The following examples assume the MP4 file format.

1. Read all metadata (outputs list of all tags extracted)
```
File file = new File("PATH_TO_VIDEO");
Metadata metadata = ImageMetadataReader.readMetadata(file);
for (Directory directory : metadata.getDirectories()) {
    for (Tag tag : directory.getTags()) {
        System.out.println(tag);
    }
}
```
2. Read specific tags (seconds)
```
File file = new File("PATH_TO_VIDEO");
Metadata metadata = ImageMetadataReader.readMetadata(file);
Directory directory = metadata.getFirstDirectoryOfType(Mp4Directory.class);
System.out.println(directory.getDescription(Mp4Directory.TAG_DURATION_SECONDS));
```
A list of possible tags from the MP4 directory are in [Mp4Directory.java](https://github.com/drewnoakes/metadata-extractor/blob/master/Source/com/drew/metadata/mp4/Mp4Directory.java)

There are also more directories available in the [media folder](https://github.com/drewnoakes/metadata-extractor/tree/master/Source/com/drew/metadata/mp4/media)

**Comment by debjitk** [comment]
@payton Thanks. What if the video file is not an MP4 ??

**Comment by payton** [comment]
@debjitk Currently, the only supported video formats are QuickTime and MP4.
