### ISSUE TITLE
（chinese）请问MP3 DOC PDF 的格式什么时候更新上来？？？？

### ISSUE THREAD

**Issue by JackChenzy** [drewnoakes/metadata-extractor#324]
(Please include as much information as possible, and attach a sample image if possible.)
Please tell me when the format of MP3 DOC PDF is updated

**Comment by drewnoakes** [comment]
No plans for these at present, though pull requests are welcome.

Please subscribe to individual issues for updates:

- PDF #327
- MP3 #328
- DOC #329
