### ISSUE TITLE
TIF file recognized as ARW

### ISSUE THREAD

**Issue by THausherr** [drewnoakes/metadata-extractor#336]
(Please include as much information as possible, and attach a sample image if possible.)

[tiff.zip](https://github.com/drewnoakes/metadata-extractor/files/1868050/tiff.zip)

The following code outputs "Arw" but it is a TIF file. 
```
public class PDFBox4176
{
    public static void main(String[] args) throws FileNotFoundException, IOException
    {
        URL url = new URL("https://issues.apache.org/jira/secure/attachment/12917179/tiff.tif");
        FileType fileType = FileTypeDetector.detectFileType(new BufferedInputStream(url.openStream()));
        System.out.println(fileType);
    }
}

```

**Comment by Nadahar** [comment]
This is a long-standing bug, see #217.

**Comment by THausherr** [comment]
Sorry, I had made a search, but only for tif and not for tiff. Close as duplicate of #217.

**Comment by Nadahar** [comment]
I guess some attention to this issue doesn't hurt :wink:

**Comment by eximius313** [comment]
> I guess some attention to this issue doesn't hurt

+1
