### ISSUE TITLE
Support .net Core 2.0 on Linux

### ISSUE THREAD

**Issue by dsyno** [drewnoakes/metadata-extractor#347]
Please add support to use MetadataExtractor on .net Core 2.0 running on Linux (which is what AWS Lambda runs on).

**Comment by Nadahar** [comment]
I'm not sure I fully understand what you mean, but metadata-extractor is a Java library that should run on any JVM. Maybe you're thinking of [metadata-extractor-dotnet](https://github.com/drewnoakes/metadata-extractor-dotnet)?

**Comment by drewnoakes** [comment]
Yep, this issue applies to the .NET implementation.

Good news is that it already supports `netstandard1.3` and `netstandard2.0` so you should be able to use it on .NET Core 2.0 without any changes.

If you experience otherwise, please open an issue on the .NET repo.
