### ISSUE TITLE
Can not retrieve mp4 video rotate property in metadata

### ISSUE THREAD

**Issue by songday** [drewnoakes/metadata-extractor#348]
here's metadata output by ffprobe:

> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'e:\tt\82_1526629849542.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    creation_time   : 2018-05-18T07:50:18.000000Z
  Duration: 00:00:10.74, start: 0.000000, bitrate: 829 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp,
 89 kb/s (default)
    Metadata:
      creation_time   : 2018-05-18T07:50:18.000000Z
      handler_name    : Core Media Audio
    Stream #0:1(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, sm
pte170m/bt709/bt709, progressive), 480x360, 735 kb/s, 29.98 fps, 29.97 tbr, 600
tbn, 1200 tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2018-05-18T07:50:18.000000Z
      handler_name    : Core Media Video
    Side data:
      displaymatrix: rotation of -90.00 degrees
   1.79 A-V: -0.028 fd=   1 aq=   30KB vq=   67KB sq=    0B f=0/0

As we can see, 'rotate          : 90' in Metadata section

I uploaded test file here: http://test01.tourting.com/wer/82_1526629849542.mp4

**Comment by payton** [comment]
We will need to find out which box this metadata is located in (or if it is in a current box that we already parse). I will do some searching myself. 

If you find or know any information on this, please post it here.
