### ISSUE TITLE
Support for AVI DateTimeOriginal (Canon)

### ISSUE THREAD

**Issue by PerBalling** [drewnoakes/metadata-extractor#350]
This tag is valid for camera model:
Canon DIGITAL IXUS 970

Please see:
https://github.com/PerBalling/metadata-extractor/pull/1
Source changed:
metadata-extractor-master\Source\com\drew\imaging\riff\RiffReader.java
metadata-extractor-master\Source\com\drew\metadata\avi\AviDirectory.java
metadata-extractor-master\Source\com\drew\metadata\avi\AviRiffHandler.java

Test:
metadata-extractor-master\Tests\com\drew\metadata\exif\AviDateTest.java
metadata-extractor-master\Tests\Data\CanonCanonPowerShotSX30IS_DateTimeOriginal.avi

Reference:
https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/RIFF.html
RIFF BroadcastExt Tags
320     DateTimeOriginal

**Comment by payton** [comment]
I think those changes look good... would you mind making a PR with them?

**Comment by PerBalling** [comment]
https://github.com/PerBalling/metadata-extractor/pull/1

**Comment by payton** [comment]
#358
