### ISSUE TITLE
NegativeArraySizeException when reading GIF

### ISSUE THREAD

**Issue by rzari** [drewnoakes/metadata-extractor#351]
When attempting to read the attached GIF (random example) it returns the following:

```java 
Exception in thread "main" java.lang.NegativeArraySizeException
	at com.adobe.xmp.impl.ByteBuffer.<init>(Unknown Source)
	at com.drew.metadata.xmp.XmpReader.extract(XmpReader.java:167)
	at com.drew.metadata.gif.GifReader.readApplicationExtensionBlock(GifReader.java:275)
	at com.drew.metadata.gif.GifReader.readGifExtensionBlock(GifReader.java:225)
	at com.drew.metadata.gif.GifReader.extract(GifReader.java:103)
	at com.drew.imaging.gif.GifMetadataReader.readMetadata(GifMetadataReader.java:60)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:158)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:121)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:197)
```

Running the file against exiftool generates (partly to verify the filetype):

- ExifTool Version Number         : 10.93
- File Name                       : IMG_5602.gif
- Directory                       : /tmp
- File Size                       : 44 kB
- File Modification Date/Time     : 2018:06:17 16:15:21+01:00
- File Access Date/Time           : 2018:06:17 16:15:30+01:00
- File Inode Change Date/Time     : 2018:06:17 16:15:21+01:00
- File Permissions                : rw-------
- File Type                       : GIF
- File Type Extension             : gif
- MIME Type                       : image/gif
- GIF Version                     : 87a
- Image Width                     : 840
- Image Height                    : 436
- Has Color Map                   : Yes
- Color Resolution Depth          : 8
- Bits Per Pixel                  : 7
- Background Color                : 0
- Warning                         : [minor] Empty XMP
- Image Size                      : 840x436
- Megapixels                      : 0.366

It looks like it could be an issue on this line in [GifReader.java](https://github.com/drewnoakes/metadata-extractor/blob/master/Source/com/drew/metadata/gif/GifReader.java#L275).  In the case of the attached image, the XmpByte length is 4 bytes long so (xmpBytes.length - 257) raises the NegativeArraySizeException. 

It looks like gatherBytes(SequentialReader reader) has a fixed byte array of size 257.  Is there a reason that 257 is being subtracted from xmpBytes.length?  Removing this appears to fix my issue but I'm not entirely familiar with the code.

Thanks.
![img_5602](https://user-images.githubusercontent.com/16512429/41509457-b3374f00-724b-11e8-831e-5facc06bbffe.gif)

**Comment by Nadahar** [comment]
I just came across the same bug with a different image. I also traced the bug to https://github.com/drewnoakes/metadata-extractor/blob/47e2bffb91d61889eecba4f61cb7bbb419a2e924/Source/com/drew/metadata/gif/GifReader.java#L275

It might be that the XMP metadata is invalid (it's only 129 bytes long in this case, resulting in a negative length when 258 is subtracted), but it should be easy to avoid an unhandled exception and instead ignore the XMP data or something like that?

![pbar-ani](https://user-images.githubusercontent.com/12900583/46450886-e9b6ee80-c793-11e8-88b9-52518595f5ef.gif)
