### ISSUE TITLE
Type mismatch: cannot convert from com.drew.metadata.Metadata to metadata.Metadata

### ISSUE THREAD

**Issue by AymanArif** [drewnoakes/metadata-extractor#352]
`Type mismatch: cannot convert from com.drew.metadata.Metadata to metadata.Metadata`, error in this line `Metadata metadata = ImageMetadataReader.readMetadata(file);`.
If changed to `com.drew.metadata.Metadata metadata = ImageMetadataReader.readMetadata(file);`, then this error arises for `print` method. `com.drew.metadata.Metadata metadata = ImageMetadataReader.readMetadata(file);`

**Comment by Nadahar** [comment]
It seems like you have a problem with your imports. Is it really necessary to import another class called ```Metadata``` in the class that makes this call? If so, one of them need to be fully qualified in every location.
