### ISSUE TITLE
Some issues when get metadata from heic picture

### ISSUE THREAD

**Issue by lzzcg** [drewnoakes/metadata-extractor#362]
Hi everyone,  I'm testing the function of 'getting metadata from heic picture', and find some issues as below. I'm wondering whether I have some misunderstanding to the function? Thank you in advance :)

1. in class ItemInfoBox.ItemInfoEntry.
  the code cannot parse subsequent bytes after eexcute the line ` itemName = reader.getString(4);`
  after I delete this line, the program works ok.

2. in class HandlerBox, I got an error when execute the line `name = reader.getNullTerminatedString((int)box.size - 32, Charset.defaultCharset());`
and after I replace the line with `name = reader.getString((int)box.size - 32);`, it works fine.

3. in class ItemLocationBox, I think the structure of the ItemLocationBox should be like below:

```java
public class ItemLocationBox extends FullBox
{
    int indexSize;
    
    int offsetSize;
    
    int lengthSize;
    
    int baseOffsetSize;
    
    long itemCount;
    
    ItemLocationInfo[] itemLocationInfos;
}


public class ItemLocationInfo
{
    long itemID;
    
    int constructionMethod;
    
    int dataReferenceIndex;
    
    byte[] baseOffset;
    
    int extentCount;
    
    Extent[] extents;
}
```

~~4. cannot get the Exif info from the mdat box, I think this feature has not been implemented yet. :)~~ moved to #371

**Comment by payton** [comment]
Thanks for the feedback! I developed the limited HEIC support given the most recent ISO documentation at the time. When testing, I had a fairly limited selection of photos to use. 

Could you provide us with some images that are causing the errors you referenced? Even better if you could add them to the image database https://github.com/drewnoakes/metadata-extractor-images

As far as your 4th point goes, yes it hasn't yet been implemented - What we have so far is very basic support. Always open to PRs if you're interested in adding something new :)

**Comment by payton** [comment]
@lzzcg Thank you for the references. I can take a look at how mp4parser is approaching this, but we are avoiding importing any external libraries.

It is very difficult for me to identify these issues if I don't have an image to reproduce it. Do you have permission to release the image you used to get these errors? I have not been able to reproduce them with my own.

**Comment by endy1106** [comment]
https://github.com/endy1106/public/blob/master/IMG_1034.HEIC

**Comment by lzzcg** [comment]
@payton  please refer to the pic in [https://github.com/endy1106/public/blob/master/IMG_1034.HEIC](url)

**Comment by drewnoakes** [comment]
@endy1106 is the linked image (IMG_1034.HEIC) yours, and if so do you grant permission for this project to use it in the [sample image repository](https://github.com/drewnoakes/metadata-extractor-images)? We don't currently have any HEIC images for testing.

**Comment by drewnoakes** [comment]
Pinging @endy1106 about the image once more. If you can provide that or another HEIC image it'd be very helpful.
