### ISSUE TITLE
Review clones made on Google Code

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor#38]
During the project's time on Google Code, 31 clones were made, of which it seems that five had changes pushed.

Review these for features to merge.

https://code.google.com/p/metadata-extractor/source/clones

* [amandra](https://code.google.com/r/amandra-xmp/source/list) - XMP/Android related changes
* ~~[nkeating](https://code.google.com/r/nkeating-working/source/list?name=nkeating-working) - cross locale unit tests (obsolete)~~
* ~~[sampisa](https://code.google.com/r/sampisa-hyper/source/list) - IPTC in TIFF~~
* ~~[raygauss-master](https://code.google.com/r/raygauss-metadata-extractor/source/list) / [raygauss-2.6.2-maven](https://code.google.com/r/raygauss-metadata-extractor/source/list?name=2.6.2-maven) - Maven/Sonatype changes~~
* ~~[farrukhnajm](https://code.google.com/r/farrukhnajm-mavenization/source/list) - Maven changes~~

**Comment by drewnoakes** [comment]
Only amandra's XMP changes are left to review. However the [link to the source](https://code.google.com/r/amandra-xmp/source/list) is giving me a 500 error.

**Comment by Odrahcyr** [comment]
Did you try git clone https://code.google.com/r/amandra-xmp/ ?
?

2015-02-01 22:12 GMT+01:00 Drew Noakes <notifications@github.com>:

**Comment by drewnoakes** [comment]
Good idea. It doesn't seem to work though:

```none
$ git clone https://code.google.com/r/amandra-xmp
Cloning into 'amandra-xmp'...
remote: Counting objects: 5187, done.
Receiving objects: 100% (5187/5187), 7.57 MiB | 2.11 MiB/s, done.
Resolving deltas: 100% (3905/3905), done.
Checking connectivity... fatal: bad object 04c52e5775bbd6386424f8f671b89b75333b861d
fatal: remote did not send all necessary objects
Unexpected end of command stream
```

**Comment by Odrahcyr** [comment]
I have a local copy of amanda's repository. I will push it to github this evening.

**Comment by drewnoakes** [comment]
Thanks @Odrahcyr. That'd be great.

**Comment by rcketscientist** [comment]
That was my fork; I'm working on merging it now.  I can handle basic git, but I'm embarrassed to say it took me about a day to finally splice it in.  

One question regarding the changes to getOrCreateDirectory.  Is the intention that a user would check with contains and explicitly call add now?

That change in particular is hanging up my push.

**Comment by rcketscientist** [comment]
Ok I submitted a pull request.  Not sure I did the whole process properly, but let me know if I need to fix anything.  Thanks.

**Comment by drewnoakes** [comment]
Great news!

The change you mention was made to allow adding multiple directories of the
same type. Previously you'd call addOrCreate which would maintain only a
single instance. I'd suggest using add directory instead as if an image
contains multiple XMP documents (which is possible) then we should reflect
them as multiple instances of XmpDirectory.

BTW, thanks for the PR. I'll take a look at it when on a proper computer.

[via phone]
