### ISSUE TITLE
General way to get height/width

### ISSUE THREAD

**Issue by Pitometsu** [drewnoakes/metadata-extractor#380]
Is there any way to get height/width in general, like `FileTypeDetector.detectFileType` does for mime type? Because currently it encoded in image-type-specific directory in directory-specific tag, AFAIK.

**Comment by Pitometsu** [comment]
E. g. https://github.com/drewnoakes/metadata-extractor/search?q=public+static+final+int+TAG_IMAGE_WIDTH&unscoped_q=public+static+final+int+TAG_IMAGE_WIDTH

**Comment by drewnoakes** [comment]
Duplicate of #10.
