### ISSUE TITLE
How to load Metadata object from a exif file

### ISSUE THREAD

**Issue by xuyao178** [drewnoakes/metadata-extractor#389]
I have got the exif infomation from a photo and store as a file. Can I use metadata-extractor to load this file as a Metadata object?
I can use command "exif -i xxx.exif" to get the infomations.

**Comment by drewnoakes** [comment]
I don't know what tool you've used to extract the exif segment, but assuming it's extracted a JPEG segment, you should be able to use `ExifReader.readJpegSegments`.

If the tool removed the preamble from the JPEG segment, you might need to use `ExifReader.extract` instead.

**Comment by xuyao178** [comment]
@drewnoakes Thanks a lot. 
I used ExifReader.readJpegSegments to solve my problem.
