### ISSUE TITLE
Bug in Mp4Reader causes wrong skip offset

### ISSUE THREAD

**Issue by ponyfleisch** [drewnoakes/metadata-extractor#390]
The skip logic [here](https://github.com/drewnoakes/metadata-extractor/blob/2.11.0/Source/com/drew/imaging/mp4/Mp4Reader.java#L62) does not handle the case [here](https://github.com/drewnoakes/metadata-extractor/blob/2.11.0/Source/com/drew/metadata/mp4/boxes/Box.java#L40) properly. An additional offset of 8 bytes is needed in this case. I suggest storing the header size in the Box object and using that to determine the offset.

Shall i submit a pull request?

**Comment by payton** [comment]
As @drewnoakes said, a PR would be great. Great catch!

**Comment by drewnoakes** [comment]
@ponyfleisch is this something you'd be able to pick up?

**Comment by drewnoakes** [comment]
Please also verify whether this applies to QuickTime handling too.

**Comment by drewnoakes** [comment]
@ponyfleisch will you have a chance to look at this?

Regardless of whether you can make a PR or not, can you share a sample file that triggers this behaviour?

**Comment by drewnoakes** [comment]
This code has since been updated to:

https://github.com/drewnoakes/metadata-extractor/blob/b694a7ed5798249197b1a624b8d77f0d61fff256/Source/com/drew/imaging/mp4/Mp4Reader.java#L64-L69

@ponyfleisch please verify if this code fixes your issue.
