### ISSUE TITLE
How do I read GPS Information

### ISSUE THREAD

**Issue by debjitk** [drewnoakes/metadata-extractor#392]
How do I read GPS Information from file. Latitude and Longitude ?

**Comment by drewnoakes** [comment]
This code should help you:

https://github.com/drewnoakes/metadata-extractor/blob/a958e0b61b50e590731b3be1dca8df8e21ebd43c/Samples/com/drew/metadata/GeoTagMapBuilder.java#L78-L90

**Comment by debjitk** [comment]
Thanks
