### ISSUE TITLE
port GifReader TagUserInputFlag bit processing from .NET

### ISSUE THREAD

**Issue by kwhopper** [drewnoakes/metadata-extractor#413]
Port this line from .NET to Java purely for consistency:

https://github.com/drewnoakes/metadata-extractor-dotnet/blob/2f446ce775cd6e7db0055ae9ed6d673eef36d541/MetadataExtractor/Formats/Gif/GifReader.cs#L334

**Comment by drewnoakes** [comment]
@kwhopper this code was added to the Java library in e5731c8ce98162a4938853b6b7b98c4b8d34a8bc which pre-dates this issue, so I'm not sure what action to take here. Am I missing something?

**Comment by kwhopper** [comment]
Difficult to recall. It's likely from comparison testing at some point when working on the RAS classes. Maybe it was to see if the bit shifting was needed, when a simple comparison to "2" is enough. If the bit shifting logic returns the same value, it's probably fine.
