### ISSUE TITLE
QuickTime/MP4 reading not thread safe

### ISSUE THREAD

**Issue by davidekholm** [drewnoakes/metadata-extractor#421]
We read metadata for .mov files using ImageMetadataReader.readMetadata(File);
To accelerate the process, we use multiple threads, however, this causes Metadata-extractor to sometimes swap the metadata between two files. It's pretty rare when I test, but I have a customer who can trigger it repeatedly. I assume that the Metadata-extractor movie reader simply isn't thread safe. Wrapping the readMetadata call in a synchronized block makes it work, but with a significant time penalty. 
(The same logic also reads metadata for images just fine so it's safe to say that the client code is fine)

**Comment by drewnoakes** [comment]
This is because of shared mutable static fields on `Mp4HandlerFactory` and `QuickTimeHandlerFactory` that snuck through PR review. The design goal is definitely to be threadsafe.

**Comment by payton** [comment]
The reasoning behind that was we need information on previous atoms to determine the significance of lower ones. This was a poor design decision, but that was the rationale (I also didn't even think about it being threadsafe at the time). We just need a better method of context passing.

**Comment by drewnoakes** [comment]
Thanks @payton.

In the Java implementation it might be tempting to pass the `Metadata` object to allow later handlers to look up earlier handler's output, but that approach may be flaky. We should look to see if we can create a specific kind of context for these operations.

In the .NET implementation we don't have a `Metadata` object, so we would definitely need a dedicated context object there.

**Comment by davidekholm** [comment]
Any progress on this? Some users are a bit sad to see that our most recent jAlbum release didn't address this.
