### ISSUE TITLE
About FileTypeDetector.detectFileType : wrong input type paramater

### ISSUE THREAD

**Issue by eleduc** [drewnoakes/metadata-extractor#424]
Why the inputStream parameter for the static method FileTypeDetector.detectFileType should be a BufferedInputStream and not a FilterInputStream ? 
The mark / reset mechanism is supported by the FilterInputStream implementation and due to the use of BufferedInputStream, it is not possible to use a derived class from FilterInputStream. 
As a consequence, we have to wrap any FilterInputStream instance within a new BufferedInputStream instance in order to be able to use this method. Moreover, we have to mark and reset the wrapped FilterInputStream, because the mark/reset mechanism is performed on the newly created BufferedInputStream. 
I do the change on a local version of this library, and it works fine : no need anymore to wrap and to mark/reset the stream. 

My local change is : 

```java
public static FileType detectFileType(@NotNull final FilterInputStream inputStream) throws IOException
```
and I use it like this : 

```java
class MyStream extends FilterInputStream { ... } 
MyStream myStream = new MyStream();
FileTypeDectector.detectType(myStream); 
```

Without the change, I did : 

```java
class MyStream extends FilterInputStream { ... } 
MyStream myStream = new MyStream();
myStream.mark(-1);
FileTypeDectector.detectType(new BufferedInputStream(myStream)); 
myStream.reset();
```

Let me know if I missed something important about your implementation choice.

**Comment by drewnoakes** [comment]
Sounds like a good change. Would you like to send a pull request?

**Comment by eleduc** [comment]
Yes, I will send you a pull request before end of this week.

**Comment by eleduc** [comment]
Pull request done.  I just perform a maven package command and it is fine. 
Let me know if missed to perform something.

**Comment by drewnoakes** [comment]
Thanks for the PR. This will be included in the next release.
