### ISSUE TITLE
TimeZones

### ISSUE THREAD

**Issue by JPT77** [drewnoakes/metadata-extractor#427]
I don't want to include it the the timestamp issue because this already is rather complex. 
I've got the following setting:
- Phone automatically switches to local timezone
- Camera doesn't 
So I have to deal with them differently when I am taking photos in a different timezone than the Camera is set to.
I want to have the Timezone in my photos where I took them.
So I added to my code the Timezone CET (Germany) and EET (Romania). They differ by one hour.
The problem now occurs when I read the Timestamp using: 
`directory.getDate(ExifDirectoryBase.TAG_DATETIME, TimeZone.getTimeZone("EET"))`
Let's say there is 10:00 stored in the Photo. With setting EET I get 9:00 while what I want is 11:00 because I want to change the CET time stored into EET not the other way round. 
It would be a dirty hack to use something like GMT+1 instead to achieve what I want. 
A little bit better would be to just use the Camera's timezone in the call and then add 1 hour manually afterwards. 

any better idea?
A clean solution would probably be to have a method that takes target and source timezone both...

**Comment by JPT77** [comment]
I've got an idea. I have to read it using what it is, CET. And then convert it to string using the target timezone EET. Let's hope that works in Java...

**Comment by JPT77** [comment]
solved it like this: 
```
int tzOffset = (
	TimeZone.getTimeZone("EET").getOffset(GregorianCalendar.AD,2019,GregorianCalendar.JUNE,1,GregorianCalendar.MONDAY,0)-
	TimeZone.getTimeZone("CET").getOffset(GregorianCalendar.AD,2019,GregorianCalendar.JUNE,1,GregorianCalendar.MONDAY,0))/1000/60/60;
filedate = Date.from(filedate.toInstant().plus(Duration.ofHours(tzOffset)));
```
would be a little easier if the library used Java 8 LocalDateTime and ZonedDateTime

**Comment by drewnoakes** [comment]
The library supports versions of Java before 8 so, at least for now, we won't have better support here. Thanks for sharing your code.

I'll close this as I don't see any actionable item here.
