### ISSUE TITLE
IPTC Tags Missing Double Point

### ISSUE THREAD

**Issue by janArb** [drewnoakes/metadata-extractor#428]
(Please include as much information as possible, and attach a sample image if possible.)
Hi,

I'm parsing the test image from the IPTC standard webpage (https://iptc.org/standards/photo-metadata/iptc-standard/): https://www.iptc.org/std/photometadata/examples/IPTC-PhotometadataRef-Std2017.1.jpg

I checked the values with ExifTool and it shows IPTC Tags

   55 Date Created                    : 2017:07:13
   60 Time Created                    : 17:01:00+00:00

However the library returns these values with double points missing:
20170713
170100+0000

![grafik](https://user-images.githubusercontent.com/6604546/63249946-d22d0b00-c26a-11e9-8bb5-9aaa74011166.png)

Best regards
Jan

**Comment by janArb** [comment]
We use https://github.com/dragon66/icafe to write IPTC tags and if I set values with double point, this changed values are read in correctly with double point. Looks like a special case in this standard IPTC file.

**Comment by drewnoakes** [comment]
In general the library stores the raw extracted value in the directory then applies presentation logic in the descriptor classes. Your screenshot shows the raw strings.

https://github.com/drewnoakes/metadata-extractor/blob/e1d8f0dcf9ef3db1afa36247fca5df881cc2cd68/Source/com/drew/metadata/iptc/IptcDescriptor.java#L81-L101

That code in `IptcDescriptor` converts from the raw string to the presentation version you're expecting.

Thanks for the links to IPTC sample data. I'll look to add those to our test data set.

I'll close this for now. Let me know if I missed something and we can re-open it.
