### ISSUE TITLE
Incorrect getGpsDestLongitudeDescription tags

### ISSUE THREAD

**Issue by kwhopper** [drewnoakes/metadata-extractor#430]
These tags appear to be the wrong ones for this method:

https://github.com/drewnoakes/metadata-extractor/blob/e1d8f0dcf9ef3db1afa36247fca5df881cc2cd68/Source/com/drew/metadata/exif/GpsDescriptor.java#L154-L158

They should probably be TAG_DEST_LONGITUDE and TAG_DEST_LONGITUDE_REF, but I can't be 100% sure.

**Comment by drewnoakes** [comment]
I agree that does look like a bug 👍
