### ISSUE TITLE
Example for writing back exif information to an image

### ISSUE THREAD

**Issue by gyf900** [drewnoakes/metadata-extractor#431]
(Please include as much information as possible, and attach a sample image if possible.)
hello drewnoakes, I found it's easy to get and manipulator exif using this lib. But how can I write those information back to my image? For apache imaging I see ExifRewriter().updateExifMetadataLossy . Is there any way to update exif information in this lib?

**Comment by drewnoakes** [comment]
This library does not support writing metadata back to images.

See #14.
