### ISSUE TITLE
sample xmp code does not work with xmp/mov file

### ISSUE THREAD

**Issue by yiandrewli1** [drewnoakes/metadata-extractor#434]
Using exiftool, I can extract xmp info from the quicktime *.mov file. But using xmp sample code here, it's returning empty directories.

**Comment by drewnoakes** [comment]
Can you provide an example of a .mov file that contains XMP metadata?

**Comment by zxcV32** [comment]
Reopening this issue because I observed this in a jpg image.

The sample image `FUJIFILM - FinePixS1Pro`here
https://github.com/drewnoakes/metadata-extractor/wiki/SampleOutput 

has XMP metadata but the library does not return anything using `ImageMetadataReader.readMetadata(InputStream)`.

**Comment by drewnoakes** [comment]
@zxcV32 it appears the library does extract XMP for FinePixS1Pro:

https://github.com/drewnoakes/metadata-extractor-images/blob/master/jpg/metadata/java/FujiFilm%20FinePixS1Pro%20(1).jpg.txt

**Comment by zxcV32** [comment]
Thanks, @drewnoakes,
 I got it working using `XmpDirectory.getXmpProperties()` method.
