### ISSUE TITLE
Missing support of standard ISO-8859-1 encoding

### ISSUE THREAD

**Issue by jonasvoelcker** [drewnoakes/metadata-extractor#437]
Hey guys, we are using your framework in our company and face a situation where the encoding of our images can not be determined.

According to this page, the "1B 2E 41" which can be found in our "CodedCharacterSet" belongs to the ISO-8859-1 encoding.

http://nozer0.github.io/en/technology/system/character-encoding/

I've added a pull request which should fix this special case and hopefully solve our issue ;)

We would like to go into production before the end of this year, so hopefully you can make it a hotfix or release before? ;)

Best regards
Jonas

**Comment by drewnoakes** [comment]
Thanks for the great bug report and PR. I'll take a look at it shortly and get a release out.

Could you provide an image that uses this encoding? It would help debugging and prevent regressions in future.

**Comment by jonasvoelcker** [comment]
That was fast, thanks for the rapid response :)

Unfortunately I cannot provide a picture of the company and actually I don't know how to produce any image with the same issue.

Regardless of the missing picture our try to change the "charsetName" within the IptcReader in debugging mode to "ISO-8859-1" solved the misinterpretation of the Strings "Köln" and "fühlt", which were previously interpreted as "K�ln" and "f�hlt".

The link has been added to the javadoc as you requested ;)

**Comment by drewnoakes** [comment]
Thanks again Jonas. I'll get a release out soon.

**Comment by jonasvoelcker** [comment]
That's great, thanks for your effort :)

**Comment by jonasvoelcker** [comment]
Helllo Drew,

last time we wrote, you announced a release being done soon. Now it is over a month. ;)

Best regards

**Comment by drewnoakes** [comment]
Thanks for the reminder. I need to set up my other machines to do release. It's more complex to publish to Maven than it is for NuGet. I'm away from my main workstation until the weekend, so will look into this then.

**Comment by jonasvoelcker** [comment]
Hello again,

it would be really lovely, if you would finally release this feature, even if it is just a hotfix.

The last month we didn't get any further errors so we thought, our images might have been fixed, but now I have run into the same error again.

We do need this at least in January, otherwise it will crash our schedule :/

Best Regards
Jonas
