### ISSUE TITLE
Unable to extract metadata from MOV files using QuickTimeMetadataReader

### ISSUE THREAD

**Issue by praveensinghthakur** [drewnoakes/metadata-extractor#440]
Please see my sample code below:

```
Metadata metadata = QuickTimeMetadataReader.readMetadata(inputStream);
			
		for (Directory directory : metadata.getDirectories()) {
			    for (Tag tag : directory.getTags()) {
			        System.out.println(tag);
			    }
			}


```
I get back only following tags always. Have tried with 2-3 different .mov files. Please advise.

**Comment by EarlyOut** [comment]
Instead of **QuickTimeMetadataReader**, try **ImageMetadataReader**.

**Comment by drewnoakes** [comment]
> I get back only following tags always

What tags are you seeing?

Please provide some more information and a sample file. Right now it's impossible to tell what's going on.

**Comment by payton** [comment]
@praveensinghthakur Any update?
