### ISSUE TITLE
Question: When will metadata extractor have a new release?

### ISSUE THREAD

**Issue by cristianturlica** [drewnoakes/metadata-extractor#442]
Hi, metadata extractor had some significant issues fixed from its last release (e.g. #419) and I was wondering when is the next one scheduled.

Thank you,
Cristian

**Comment by FreeApophis** [comment]
You do realize that EVERY Project on github using your NuGet Package got a (moderate severity) vulnerability Alert on Aug. 23rd?

Please release a new version ASAP.

**Comment by richjhart** [comment]
Android devs are still having to use version 2.11.0 as well - which is getting on for 2 years old

**Comment by drewnoakes** [comment]
Just released 2.13.0. It should be available via Maven shortly.

Please test it out and let me know if you see any issues. Thanks.
