### ISSUE TITLE
Hey Drew, I need that hotfix, please...

### ISSUE THREAD

**Issue by jonasvoelcker** [drewnoakes/metadata-extractor#459]
Hello Drew,

it's 4 months and we are facing our go live in a few weeks.

Today we checked our logic against production and it failed because of the character encoding. Could you please, please get the hotfix out as soon as possible?

I really appreciate your library, but without this change we cannot use it :(

https://github.com/drewnoakes/metadata-extractor/issues/437

Best regards
Jonas

**Comment by drewnoakes** [comment]
Just released 2.13.0. It should be available via Maven shortly.

Please test it out and let me know if you see any issues. Thanks.

**Comment by jonasvoelcker** [comment]
Hey again,

thanks a lot, the write action for the given picture now works perfectly and we are one step closer to finish our development.

I am really greatful for this and want to apologize for pushing you that often. It is clear to me, that you are investing lots of your free time for this project, so thanks!

Best Regards
Jonas
