### ISSUE TITLE
Long Title from jpeg Truncated

### ISSUE THREAD

**Issue by cmiles** [drewnoakes/metadata-extractor#474]
ExifTool and Windows File Properties report the Title of the included image as "2020 05 Blooming Paloverde and Saguaros with Ragged Top and Walcott Peak in the Background" - this is the value I expected based on the title entered into Lightroom. The relevant line from ExifTool output:

Title: 2020 05 Blooming Paloverde and Saguaros with Ragged Top and Walcott Peak in the Background

However the data I am seeing from metadata-extractor appears to truncate the Title:

517 | IPTC | Object Name | "2020 05 Blooming Paloverde and Saguaros with Ragged Top and Walc"

Notes:
 - I have at least one other example of this behavior
 - These files are exports from Lightroom 9.2.1
 - .NET Core 3.1.300-preview-015135
 - MetadataExtractor from nuget version 2.4.0
 - Could be related to #308 - I haven't dug into the details enough to say, although would note related to that discussion that while the format here could well be technically incorrect Lightroom producing it might make it more worth working around?
 - BitmapSource BitmapMetadata Title shows the complete/correct Title.

![2020-05-Blooming-Paloverde-and-Saguaros-with-Ragged-Top-and-Walcott-Peak-in-the-Background](https://user-images.githubusercontent.com/15463/81426731-76fbbb00-910e-11ea-9219-15bc38a40b1f.jpg)

**Comment by paperboyo** [comment]
Hi. I’m not using the library directly, but an app that uses it. You can find what you are looking for in its entirety under XMP (`dc:title`). It is truncated under [corresponding](https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#synchronising-iim-elements-with-existing-xmp-properties) IPTC `object name` property as this property (as some others) is truncated as per spec Adobe observes when writing it.

Unrelatedly, this kind of information belongs more in XMP `photoshop:Headline` (and its corresponding IPTC `Headline`). The [former](https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#title) is more commonly used for short, often numeric, cataloguing labels, the latter for [human readable titles](https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#headline).
