### ISSUE TITLE
Most EXIF tags are not found for iPhone HEIC photos

### ISSUE THREAD

**Issue by nicksorin** [drewnoakes/metadata-extractor#476]
Sample photo taken with iPhone 8: https://drive.google.com/open?id=1DMGFFP6cZsI0aMOtcMct8vlwSTeMZBpk

Using Windows 10, check photo Properties > Details:

- Origin - Date taken: 05/12/2019 17:01
- Image - Width: 4032 pixels
- Image - Height: 3024 pixels
- Camera - Camera maker: Apple
- Camera - Camera model: iPhone 8
- Camera - Exposure time: 1/14 sec
- Camera - ISO speed: ISO-100
- Camera - Focal length: 4 mm
- Advanced photo - Lens maker: Apple
- Advanced photo - Lens model: iPhone 8 back camera
- Advanced photo - EXIF version: 0231
- GPS data

Using metadata-extractor, print all tags from all directories:

- Major Brand : heic
- Minor Version : 0
- Compatible Brands : mif1 miaf MiHB heic
- Width : 512 pixels
- Height : 512 pixels
- Rotation : 0 degrees
- Bits Per Channel : 8 8 8
- Profile Size : 548
- CMM Type : appl
- Version : 4.0.0
- Class : Display Device
- Color space : RGB 
- Profile Connection Space : XYZ 
- Profile Date/Time : 2017:07:07 13:22:32
- Signature : acsp
- Primary Platform : Apple Computer, Inc.
- Device manufacturer : APPL
- XYZ values : 0.964 1 0.825
- Tag Count : 10
- Profile Description : Display P3
- Copyright : Copyright Apple Inc., 2017
- Media White Point : (0.9505, 1, 1.0891)
- Red Colorant : (0.5151, 0.2412, 65536)
- Green Colorant : (0.292, 0.6922, 0.0419)
- Blue Colorant : (0.1571, 0.0666, 0.7841)
- Red TRC : para (0x70617261): 32 bytes
- Chromatic Adaptation : sf32 (0x73663332): 44 bytes
- Blue TRC : para (0x70617261): 32 bytes
- Green TRC : para (0x70617261): 32 bytes
- Detected File Type Name : HEIF
- Detected File Type Long Name : High Efficiency Image File Format
- Detected MIME Type : image/heif
- Expected File Name Extension : heif
- File Name : IMG_9175.HEIC
- File Size : 2087335 bytes
- File Modified Date : Sun Apr 05 21:24:24 +02:00 2020

Would be highly appreciated if you could improve HEIC support.

Note: if needed, you can add this photo to the public library

**Comment by drewnoakes** [comment]
@nicksorin in the last few days we've improved HEIC support on `master` which has not yet been released via Maven. Would you be able to test using the latest code and let us know if you see the data you expect?

> Note: if needed, you can add this photo to the public library

Thanks very much!

**Comment by drewnoakes** [comment]
I ran this on `master` and see that we don't pull out a bunch of data from the file. The .NET implementation does, so the action item here is to port logic from .NET to Java to achieve parity across the implementations.

**Comment by nicksorin** [comment]
Thanks, @drewnoakes for your quick feedback. Keep my fingers crossed for you to find the time to implement this improvement!

**Comment by drewnoakes** [comment]
I don't know when I'll be able to get to it. In the meantime someone else is welcome to step in with a PR. It should be a relatively straightforward task, and a nice introduction to the library.

**Comment by normana10** [comment]
I had started work on this about a month ago and got distracted, I've just put in a PR #478

**Comment by drewnoakes** [comment]
Fixed by @normana10 in #478.
