### ISSUE TITLE
Could you help release the recent WebP fix via Maven?

### ISSUE THREAD

**Issue by JieyingXu** [drewnoakes/metadata-extractor#479]
Hi Drew,

I recently reported a bug regarding WebP image analyzing (#473 ), thank you very much for fixing it in such a short time. However, my project cannot depend on this fix since it is not released. I attempted to use the current version (2.13.0) on production and it fails ~1% of all uploaded WebP, so I have to ramp down my WebP support on prod.

Is it possible to release this fix via Maven? That would be a great help to unblock our production ramp for supporting WebP images. Really appreciate your help!

Jieying

**Comment by drewnoakes** [comment]
https://github.com/drewnoakes/metadata-extractor/releases/tag/2.14.0

**Comment by JieyingXu** [comment]
> https://github.com/drewnoakes/metadata-extractor/releases/tag/2.14.0

Thank you so much for your help!!
