### ISSUE TITLE
Samsung HEIC photo can't get exif information

### ISSUE THREAD

**Issue by WBJisMyName** [drewnoakes/metadata-extractor#487]
Hi Drew Noakes, 
    Recently I use your extractor as library(2.14) on my Samsung s10+, but after I shoot heic photo and used library to parse,
I found the result is not what I want.
   Here is the result:

Directory 1
[HEIF] Major Brand - heic
[HEIF] Minor Version - 0
[HEIF] Compatible Brands - mif1 heic 
Directory 2
[HEIF] Width - 512 pixels
[HEIF] Height - 512 pixels
[HEIF] Rotation - 270 degrees
Directory 3
[File Type] Detected File Type Name - HEIF
[File Type] Detected File Type Long Name - High Efficiency Image File Format
[File Type] Detected MIME Type - image/heif
[File Type] Expected File Name Extension - heif

    Can you give me some advice? Thanks.
    The photo link is down below
    https://www.dropbox.com/s/u1jm3he9jvsnrum/20200630_112758.heic?dl=0

**Comment by drewnoakes** [comment]
Thank you for the sample image. I can repro this issue. Are you able to donate the image to the test data suite?

**Comment by drewnoakes** [comment]
The .NET implementation throws an exception for this file too.

**Comment by WBJisMyName** [comment]
Sure. Thank you for quick reply!

**Comment by drewnoakes** [comment]
Exif data is in there. Now, to get it out :)

![image](https://user-images.githubusercontent.com/350947/86378766-5d6d8e80-bccd-11ea-8b36-c63898601add.png)

**Comment by WBJisMyName** [comment]
thank you
