### ISSUE TITLE
Nokia 6.1 phone

### ISSUE THREAD

**Issue by gmmapowell** [drewnoakes/metadata-extractor#490]
I have a Nokia 6.1 phone and it generates MP4 videos which QuickTime recognizes but the metadata-extractor does not.

Looking into this, it seems that the identifying 8 bytes are **ftypnvr1** which is not one of the options in QuickTimeTypeChecker.

```
od -cx '/Users/gareth/Desktop/Maggy 2019 Photos/VID_20190327_121555.mp4' | head
0000000   \0  \0  \0 034   f   t   y   p   n   v   r   1  \0 001  \0 001
             0000    1c00    7466    7079    766e    3172    0100    0100
0000020    i   s   o   m   m   p   4   2   n   v   r   1  \0  \0  \b  \v
             7369    6d6f    706d    3234    766e    3172    0000    0b08
0000040    m   o   o   v  \0  \0  \0   l   m   v   h   d  \0  \0  \0  \0
             6f6d    766f    0000    6c00    766d    6468    0000    0000
0000060  330 301 031 376 330 301 031 376  \0  \0 003 350  \0  \0 006 000
             c1d8    fe19    c1d8    fe19    0000    e803    0000    e306
0000100   \0 001  \0  \0 001  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
             0100    0000    0001    0000    0000    0000    0000    0000
```

**Comment by drewnoakes** [comment]
Can you provide a sample file please? Ideally a very short one. For example, cover the lens with your hand and record a subsecond file, then upload it here. Be aware there may be GPS data in there.

**Comment by drewnoakes** [comment]
Alternatively make and test the change yourself. It should be a very simple addition to this file:

https://github.com/drewnoakes/metadata-extractor/blob/master/Source/com/drew/imaging/quicktime/QuickTimeTypeChecker.java

**Comment by gmmapowell** [comment]
Sure. Hope this is short enough.
[ftypnvr1.zip](https://github.com/drewnoakes/metadata-extractor/files/4971828/ftypnvr1.zip)

**Comment by drewnoakes** [comment]
@gmmapowell thanks for the sample file.
