### ISSUE TITLE
strange EPOCH_1_JAN_1904 value

### ISSUE THREAD

**Issue by choim4389** [drewnoakes/metadata-extractor#496]
why is EPOCH_1_JAN_1904 not -208284480000L but -2082844799175L?

**Comment by drewnoakes** [comment]
Can you explain why you think it should be a different value? Do you see a bug because of this?

**Comment by macan-rtzr** [comment]
@drewnoakes we've been using createdAt time to make uniqueId. 
the value from metadata-extractor is always end with 825, but the value from android media store is end with 000. 
so, the two different uid can be created from same file.

**Comment by choim4389** [comment]
@drewnoakes we've been using createdAt time to make uniqueId.
the value from metadata-extractor is always end with 825, but the value from android media store is end with 000.
so, the two different uid can be created from same file.

**Comment by drewnoakes** [comment]
Sounds reasonable. Can you make a pull request?

**Comment by choim4389** [comment]
https://github.com/drewnoakes/metadata-extractor/pull/498
