### ISSUE TITLE
GPS directory cannot be decoded for OnePlus 8 image

### ISSUE THREAD

**Issue by axelfontaine** [drewnoakes/metadata-extractor#497]
Sample image: https://github.com/drewnoakes/metadata-extractor-images/blob/master/jpg/OnePlus8.jpg

All fields are listed as 0, even though Android correctly shows the correct details.

**Comment by drewnoakes** [comment]
It seems that the values in the file are actually zero. Exiftool shows the same.

Can you provide more details on how Android shows the location data?

**Comment by axelfontaine** [comment]
Arrghh! I just checked on the original device and Google Photos DOES show GPS data. However when I check on another it doesn't. Which means that somehow it pulls the data from a different source on the original device! (Go figure why the camera app didn't save it in the image??) So metadata-extractor works as expected. Terribly sorry about the trouble. My bad. Closing.

**Comment by drewnoakes** [comment]
No problem. Thanks for following up.
