### ISSUE TITLE
Can't get descripted Samsung makernote tags as SamsungType2MakernoteDirectory

### ISSUE THREAD

**Issue by dohykim** [drewnoakes/metadata-extractor#505]
I have Samsung galaxy S8+ and read all meatadata from my photos
I saw undescripted one that is 'Makernote : [98 values]'. 

I read around and guess SamsungType2MakernoteDirectory type not detected.
at ExifTiffHandler.java line 511
`if (!"SAMSUNG".equals(cameraMake)) {
                                    return false;
                                }`
I think it should be equalsIgnoreCase

![image](https://user-images.githubusercontent.com/11845306/95149392-c1b65780-07c0-11eb-9f71-cba9c4ae2b35.png)
result :
com.drew.metadata.exif.ExifSubIFDDirectory -- Exif SubIFD  ///   Makernote : [98 values]

and edit to uppercase
![image](https://user-images.githubusercontent.com/11845306/95149467-fde9b800-07c0-11eb-9a20-9f70dd30efb8.png)
result:
com.drew.metadata.exif.makernotes.SamsungType2MakernoteDirectory -- Samsung Makernote  ///   Maker Note Version : 1.00
com.drew.metadata.exif.makernotes.SamsungType2MakernoteDirectory -- Samsung Makernote  ///   Device Type : Cell Phone
com.drew.metadata.exif.makernotes.SamsungType2MakernoteDirectory -- Samsung Makernote  ///   Unknown tag (0x000c) : 0
com.drew.metadata.exif.makernotes.SamsungType2MakernoteDirectory -- Samsung Makernote  ///   Unknown tag (0x0010) : 90/65689
com.drew.metadata.exif.makernotes.SamsungType2MakernoteDirectory -- Samsung Makernote  ///   Raw Data Byte Order : Little-endian (Intel)
com.drew.metadata.exif.makernotes.SamsungType2MakernoteDirectory -- Samsung Makernote  ///   Raw Data CFA Pattern : Swap
com.drew.metadata.exif.makernotes.SamsungType2MakernoteDirectory -- Samsung Makernote  ///   Face Detect : Off

**Comment by dohykim** [comment]
![20170209_195138](https://user-images.githubusercontent.com/11845306/95149744-a8fa7180-07c1-11eb-83eb-5513e171f469.jpg)
add sample file that originally lowerCase maker

**Comment by drewnoakes** [comment]
@dohykim I agree, it does look like ignoreCase comparision would be better here. Would you like to make a pull request?

Also, are you happy to donate that sample image to the project for testing purposes?

**Comment by dohykim** [comment]
yes sure
