### ISSUE TITLE
ftyp3gp5 type not supported

### ISSUE THREAD

**Issue by CedricCarniel** [drewnoakes/metadata-extractor#509]
Hello,

I'm using 2.15.0 and processing many images worked like a charm.
Now I need to process videos but some of them can't be open.
Calls to ImageMetadataReader.readMetadata thows 
com.drew.imaging.ImageProcessingException: File format could not be determined
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:185)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:124)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:204)

I traced the code to QuickTimeTypeChecker where I found the type list and ftyp3gp5 is not here.

Let me know if you want the video, I've no issues sharing it, I have a 7MB file

**Comment by drewnoakes** [comment]
A sample file would be great. If you can link it here I will add it to the media library.

Also seeing as you found the relevant code, would you be able to put a pull request together?

**Comment by CedricCarniel** [comment]
I was able to create an even smaller file (1MB) here attached.

[ftyp3gp5 - 20201023_222722_1 - no gps.zip](https://github.com/drewnoakes/metadata-extractor/files/5431722/ftyp3gp5.-.20201023_222722_1.-.no.gps.zip)

You added format-mov tag which actually works, but using FileType.Mp4 gives more interesting info in MP4 Directory, like GPS location. 
Also I found a few pages, like this one https://github.com/PidgeyL/Forensic-File-Handler/blob/master/README.md stating ftyp3gp5 is MP4.
