### ISSUE TITLE
Roadmap for 2.8 – Suggestions are welcome!

### ISSUE THREAD

**Issue by Odrahcyr** [drewnoakes/metadata-extractor#52]
If you as a user want something to be done in the next release, feel free to post below. 

@drewnoakes 
If I recall correctly you wanted to release 2.8 in January. I would prefer not to release before 11.1. As I already mentioned I think we should focus on supporting more formats respectively improve support for those which are already supported, f.e. gif and png, for 2.8.

**Comment by drewnoakes** [comment]
2.8.0 has now been released and is available via Maven Central.
