### ISSUE TITLE
Add Schema.PHOTOSHOP_PROPERTIES

### ISSUE THREAD

**Issue by cowwoc** [drewnoakes/metadata-extractor#520]
Please add `Schema.PHOTOSHOP_PROPERTIES = "http://ns.adobe.com/photoshop/1.0/"` for extracting photoshop-specific XMP tags.

**Comment by drewnoakes** [comment]
Sounds reasonable. Can you submit a pull request?

**Comment by cowwoc** [comment]
@drewnoakes Does the above PR work for you?

**Comment by drewnoakes** [comment]
@cowwoc thanks for following up. That PR targets your fork of the project, not this one. That is, merging it would modify your fork, not this repo.

Can you create a new PR from the branch on your fork against this repo? This URL should do the job:

https://github.com/drewnoakes/metadata-extractor/compare/master...cowwoc:schema-photoshop

**Comment by cowwoc** [comment]
@drewnoakes Good catch. I've created two new PRs for your review. The second one can be found at https://github.com/drewnoakes/metadata-extractor/pull/523
