### ISSUE TITLE
Ability to add/update metadata

### ISSUE THREAD

**Issue by cowwoc** [drewnoakes/metadata-extractor#521]
Would you consider adding functionality to programmatically add/update metadata as opposed to just reading it?

**Comment by jefftucker1952** [comment]
This has been discussed before:

https://github.com/drewnoakes/metadata-extractor/issues/14

**Comment by cowwoc** [comment]
Thank you for the pointer.

**Comment by jefftucker1952** [comment]
Glad to help. I knew it rang a bell.

This comes up frequently, here and elsewhere. There's an unmet need out there for a really good app to enter metadata in existing fields, to add xmp fields, to do wholesale copying of data from one field to another, and so on. And I don't mean some API, or a command-line beast - I'm talking about something with a good, intuitive UI. Not easy to do, and probably not enough money in it to attract a developer, sadly.

**Comment by DesertCookie** [comment]
Would love to have this functionality as I have a few hundred photos that need their metadata copied from their source files, as the editing process erased them.
