### ISSUE TITLE
MP4 video rotation is wrong if inverted

### ISSUE THREAD

**Issue by amerson8s** [drewnoakes/metadata-extractor#532]
First of all, lemme thank you guys for this great library, I was able to find the project through stack-overflow.
 
When a video is taken while the android camera is inverted, like upside down the value is wrong
i.e. it should be -90 instead of 90
after debugging I checked that the code does :
   '<addr>Math.abs(right degree value);</addr>'
It's working fine with iPhone videos
**you had this fix 6 months ago**
https://github.com/drewnoakes/metadata-extractor/commit/961ad72399a44b5e101e3b500b687c118a819f44

can you please apply it for the equivalent class in MP4
com.drew.metadata.mp4.boxes.TrackHeaderBox.addMetadata(Mp4Directory)

Thanks a lot

**Comment by drewnoakes** [comment]
@amerson8s thanks for pointing this out. Can you make a pull request?

**Comment by amerson8s** [comment]
> 
> 
> @amerson8s thanks for pointing this out. Can you make a pull request?

Okay, sure.
