### ISSUE TITLE
File format could not be determined for encrypted InputStream

### ISSUE THREAD

**Issue by zjmo** [drewnoakes/metadata-extractor#536]
Cannot retrieve metadata from mp3 files.

This cannot determine the type exception:
`ImageMetadataReader.readMetadata(inputStream);`

This cannot read the metadata information even if does not incurr in any exception:
`ImageMetadataReader.readMetadata(inputStream, inputStream.available(), FileType.Mp3);`

In this case I've used an input stream generated by Tink Library with StreamingAEAD config.
The metatada reader works fine with video and image files.

Bonus considerations:
I've inspected the library and it looks it does not write the bytes to a temp file before reading the metadata. Could you confirm this?  Thanks.

**Comment by drewnoakes** [comment]
Is your stream correctly decrypting the data?

Also `inputStream.available()` is probably not doing what you think it is.

> I've inspected the library and it looks it does not write the bytes to a temp file before reading the metadata. Could you confirm this?

The library does not write any files, no.

**Comment by drewnoakes** [comment]
If you've used the stream to decode the image, you will have to seek back to the beginning before using the same stream with this library. If the stream doesn't support seek, you'll have to re-create it.

**Comment by Nadahar** [comment]
This might be a red herring, but have you tried to call `Mp3MetadataReader` reader directly instead of using `ImageMetadataReader`?

**Comment by drewnoakes** [comment]
The file you've linked is an MP3 that starts with an `ID3` tag. This library does not currently support ID3, and that is being tracked by #328. The concept of encryption here was misleading. The other issue is clearer, so I'll close this as a duplicate for now.
