### ISSUE TITLE
Can this library read GPS from this photo?

### ISSUE THREAD

**Issue by lemonka** [drewnoakes/metadata-extractor#537]
(Please include as much information as possible, and attach a sample image if possible.)
Sorry for being lazy but testing this either Java or DotNet will take me I believe few hours as both of those are not which I know :/ 

I have phone POCO F2 Pro and any "normal" software cannot read GSP from this photo - on phone shows correct in default gallery as well as in 3rd party applicaiton "Photo Exif Editor - Metadata Editor", but in other exif readers its shows zeros or NaN regarding GPS.

https://e.pcloud.link/publink/show?code=XZdDyVZwG52sqdpQPby7ioEkIByvYN8splX

Can anyone tell me if this lib can read it?

**Comment by drewnoakes** [comment]
Yes it reads GPS if it's there.

**Comment by lemonka** [comment]
As said - there is for sure GPS Data (other than 0 / NaN ect) but I have found only one program which can do this. All ExifTool related tools are helpless... Can You check it? Im really not proficient with Java/DotNet and setting it up for me will take hours...
