### ISSUE TITLE
ExifSubIFDDirectory from png file is null

### ISSUE THREAD

**Issue by Kinnthox** [drewnoakes/metadata-extractor#564]
I've been trying to extract the metadata from a png file. If I use this line of code:

![Screenshot_1009](https://user-images.githubusercontent.com/97395468/149798965-979fb758-706f-4abf-9a5f-8ffe7e6c6bea.jpg)

It works with jpg files but not with png files. With png files it returns null.
Can someone tell my why and how to fix it?

metadata is:

![Screenshot_1008](https://user-images.githubusercontent.com/97395468/149799332-38657641-d8c6-4270-b2df-f68548676218.jpg)

**Comment by drewnoakes** [comment]
Sounds like your PNG file doesn't contain Exif info. In such cases the directory will be absent.

There may be other kinds of directory that contain the data you are after. Perhaps you can walk through them all and see whether any suit your purposes.

Alternatively, revise your upstream processing (if any) to ensure Exif is added to your PNG files.

**Comment by Kinnthox** [comment]
I am searching for the original date time a picture was taken, which the png files, I've tested my code with, had. So the directory isn't null...

**Comment by drewnoakes** [comment]
Which directory isn't null? An image will have multiple directories, not just Exif.

**Comment by Kinnthox** [comment]
This directory isn't null:
https://user-images.githubusercontent.com/97395468/149798965-979fb758-706f-4abf-9a5f-8ffe7e6c6bea.jpg

And that is the directory i am working with in my project. It works with jpg files but not with png files...

**Comment by drewnoakes** [comment]
By directory I mean a Java class, such as `ExifSubIFDDirectory`.

**Comment by Kinnthox** [comment]
> Sounds like your PNG file doesn't contain Exif info. In such cases the directory will be absent.
> 
> There may be other kinds of directory that contain the data you are after. Perhaps you can walk through them all and see whether any suit your purposes.
> 
> Alternatively, revise your upstream processing (if any) to ensure Exif is added to your PNG files.

Are there any other kinds of directory that contain the original date time a picture was taken on? I think ExifSubIFDDirectory is the only one right?

**Comment by drewnoakes** [comment]
My advise would be to use the sample code to walk through all tags in all dictionaries and print them out. There could be all sorts of metadata nested in there, including timestamps.

**Comment by Kinnthox** [comment]
Alright. Thank you!
