### ISSUE TITLE
JPG - width and height dimensions are switched

### ISSUE THREAD

**Issue by SalyczeQ** [drewnoakes/metadata-extractor#567]
(Please include as much information as possible, and attach a sample image if possible.)
![7ee2f463-68d8-499a-abc6-555416f03c00](https://user-images.githubusercontent.com/11751660/151037810-280b727a-aa1e-41b1-a530-7faddd8a4683.jpeg)
![718bc0d7-79ba-465f-81d6-fda4a6ce5f5c](https://user-images.githubusercontent.com/11751660/151037814-7d565c4c-5169-495f-bb1f-51d4e94e2444.jpeg)

images were taken by iPhone7. 

original images are oriented on height, but recognized dimensions switched as you can see from debugging view in IDE:

![image](https://user-images.githubusercontent.com/11751660/151038009-562bc936-f26b-46d5-8471-8ee4739e86d5.png)

**Comment by drewnoakes** [comment]
This may be "correct". Take a look in other directories for alignment/orientation/rotation information.

Those dimensions likely represent how the pixels are stored in the file. Other metadata may instruct a viewer to flip the image somehow before displaying it on screen.

**Comment by SalyczeQ** [comment]
![image](https://user-images.githubusercontent.com/11751660/151070105-cff35136-b8c5-4382-a372-4c7758c9f3a0.png)
sorry, I was in hurry, so maybe I did not provide much information.

here You can see this EXIF info:
[Exif IFD0] Orientation - Right side, top (Rotate 90 CW)

so, I can swap them, but when I check info about image in Linux nautilus I got this:
![image](https://user-images.githubusercontent.com/11751660/151070691-fa54d35f-ea8b-4cfc-a203-fc44b8f0cfab.png)
...
hmm
but Linux image viewer is showing this: (same as your lib)
![image](https://user-images.githubusercontent.com/11751660/151070525-dfd110c6-2d07-484c-8ce9-e35238cf4f42.png)


so it seems that it depends on how SW (lib) is working with Exif info. Sometimes it is included, a sometimes not. I just thought that this behavior is consistent everywhere.

**Comment by SalyczeQ** [comment]
I think that issue here is clear, and it is required to check metadata for alignment/orientation/rotation information.

I was just confused because when I scale the image and metatags are removed the image is flipped.
