### ISSUE TITLE
Buffer over/underflows in PhotoshopReader

### ISSUE THREAD

**Issue by Odrahcyr** [drewnoakes/metadata-extractor#57]
> [Photoshop] Number of requested bytes cannot be negative
> [Photoshop] Attempt to read from beyond end of underlying data source

These two errors are really common and should not happen that often. This issue may be related to other existing issues.

**Comment by drewnoakes** [comment]
Thanks for the report! This was a significant bug which must have been a regression as the code prior to this fix could not have worked.

Revisiting this also highlighted #87 as an obvious omission from the library.
