### ISSUE TITLE
Observed multiple instances of PNG chunk 'mkBT', for which multiples are not allowed

### ISSUE THREAD

**Issue by RicardoBochnia** [drewnoakes/metadata-extractor#58]
It seems like multiple instances of chunk 'mkBT' in png files are not that uncommon. I've got this particular messages for many png files. Also got some for other chunks but they were very rare compared to 'mkBT'.

We should investigate if multiple instances of 'mkBT' always indicates an error. Also we would need a way to deal with them. ExifTool can read the metadata without any error.

Sample:
![hammer-icon](https://cloud.githubusercontent.com/assets/8988676/5384370/06b81084-80b9-11e4-8b8f-f41785abf652.png)

**Comment by sedhha** [comment]
I am getting this for exiF exceptions:
```
"error": "Observed multiple instances of PNG chunk 'eXIf', for which multiples are not allowed",
    "exception": "com.drew.imaging.png.PngProcessingException",
    "failure": {
        "message": "Observed multiple instances of PNG chunk 'eXIf', for which multiples are not allowed",
        "exception": "com.drew.imaging.png.PngProcessingException",
        ```

**Comment by drewnoakes** [comment]
@sedhha can you create a new issue and attach an image that reproduces this please?
