### ISSUE TITLE
Can I remove Exif of image file by this library?

### ISSUE THREAD

**Issue by eziosudo** [drewnoakes/metadata-extractor#583]
I want to deal with some attachment file to remove Exif if there is. Can this library do help? 
I can get directories, including Exif by guide but I cannot find a way to remove them.

**Comment by StefanOltmann** [comment]
No, this library can only read/„extract“ metadata.

**Comment by drewnoakes** [comment]
That's right. Today there's no means of modifying the original file using this library.
