### ISSUE TITLE
Upgrade 2.6 - 2.7: Image throwing "cannot set a null String"

### ISSUE THREAD

**Issue by jamesgorrie** [drewnoakes/metadata-extractor#59]
After upgrading from 0.6 - 0.7, I have had a few images throwing [this error](https://github.com/drewnoakes/metadata-extractor/blob/master/Source/com/drew/metadata/Directory.java#L245). I am trying to figure out what it might be, but reverting back to 0.6 seems to work fine.

**Sample image**
![2014-12-11t082710z_900208513_gm1eacb19gh01_rtrmadp_3_garuda-indonesia-ceo](https://cloud.githubusercontent.com/assets/31692/5392752/d51cc394-8121-11e4-9f33-e0b9bd19a436.JPG)

**Comment by theefer** [comment]
@drewnoakes I've just tested 2.7.0 off the latest master and it still seems to be throwing the same image on the sample image from this issue, as well as with the image from https://github.com/drewnoakes/metadata-extractor/issues/72. Can you confirm they are fixed for you after your fix?

**Comment by theefer** [comment]
Actually I may not be correctly loading the latest version I built, ignore my previous comment while I confirm...

**Comment by theefer** [comment]
Apologies, I can confirm these images are fine, and the encoding issues we had under 2.6.* are also resolved. Great work!
