### ISSUE TITLE
PNG: Extract metadata from iTXt and zTXt chunks (similar as the .net version already does)

### ISSUE THREAD

**Issue by StefanOltmann** [drewnoakes/metadata-extractor#590]
I converted a JPG from Unsplash (= you can use it in your test file repository) to a PNG using Affinity Photo and GIMP with the option to preserve metadata.

In both cases Exiftool as well as the macOS Preview app show me the EXIF metadata. I created the Exiftool report using `exiftool -g1 -a photo.jpg` and for all photos they have a category named `ExifIFD`.

But only the JPG has actually a `ExifIFD0Directory` and `ExifSubIFDDirectory` in the `com.drew.metadata.Metadata` instance returned by `ImageMetadataReader.readMetadata(file)`.

I saw that there is a [sampleWithExifData.png](https://github.com/drewnoakes/metadata-extractor-images/blob/master/png/sampleWithExifData.png) which interestingly doesn't have a EXIF tab in the macOS preview app.

I digged a bit into the code and found that the PNGs created by GIMP and Affinity Photo don't seem to have a `eXIf` `PngChunkType`. So it looks like the information is stored somewhere else in the file. I assumed the `XmpDirectory`, but that does not have exposure data.

I'm interested in this metadata:
- date original / taken time
- geo location
- make
- model
- lens make
- lens model
- iso equivalent
- exposure time
- f-number
- focal length

Is there a way to extract these from the PNGs below right now or is that unsupported?

Original JPG: [photo.jpg](https://user-images.githubusercontent.com/9299303/193809143-766ff3c0-5c99-432e-97fc-b154cdbad2cf.jpg) ([Exiftool info](https://github.com/drewnoakes/metadata-extractor/files/9706290/photo.jpg.txt))

Affinity Photo PNG: [photo-affinity.png](https://user-images.githubusercontent.com/9299303/193809211-5bbeda44-4b93-4102-8365-b354606c19dc.png) ([Exiftool info](https://github.com/drewnoakes/metadata-extractor/files/9706293/photo-affinity.png.txt))

GIMP PNG: [photo-gimp.png](https://user-images.githubusercontent.com/9299303/193809238-aa55e2cd-5881-4f9b-b651-3f039995ec42.png) ([Exiftool info](https://github.com/drewnoakes/metadata-extractor/files/9706294/photo-gimp.png.txt))

**Comment by drewnoakes** [comment]
As you say, there is Exif metadata in your PNG files, but we're not pulling it out.

This should be a straightforward change. Would you be able to make a pull request? I can help you. This has been implemented in the .NET version of the library, and should be straightforward to port to Java.

The logic needs to go under here, where we special case `iTXt` and `zTXt` PNG chunks:

https://github.com/drewnoakes/metadata-extractor/blob/e9ff975209fbb7f3a51e203266ef9813b9fb81d1/Source/com/drew/imaging/png/PngMetadataReader.java#L211-L297

The .NET implementation can be seen here, and in the two callers above of `ProcessTextChunk`:

https://github.com/drewnoakes/metadata-extractor-dotnet/blob/f3f02b98728dc97a0087588a1cb6d1b03ab10157/MetadataExtractor/Formats/Png/PngMetadataReader.cs#L369

The Java version is handling the `XML:com.adobe.xmp` case, but not `Raw profile type xmp`, `Raw profile type exif`, `Raw profile type APP1`, `Raw profile type icc`, `Raw profile type icm` or `Raw profile type iptc` cases.

**Comment by StefanOltmann** [comment]
@drewnoakes Thank you for the hint. Yes, I can make a pull request, but I need to find the time to do that first. Right now PNG support is for my app not a requirement - I was just trying out different formats and how well they are supported. As soon as my app needs PNG support I will send you that PR. :)
