### ISSUE TITLE
Unit tests should pass in all locales

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor#6]
Some unit tests involve culture-sensitive formatting of values and as such can fail in different cultures/locales.
- `NikonType2MakernoteTest1#testGetAutoFlashCompensationDescription`fails with `0,67 EV` not `0.67 EV` (in Germany)
- `PngMetadataReaderTest#testGimpGreyscaleWithManyChunks` fails with `Mon Dec 31 23:08:30 EST 2012` instead of `Tue Jan 01 04:08:30 GMT 2013` (in EST).

This may also be the case for other tests.

Preference is to force the culture during unit testing rather than modifying the code under test to always use the en-GB culture.  Users should get a format that's suited to their culture.

http://stackoverflow.com/questions/8190124/junit-testing-double-tostring-in-multiple-cultures

(Migrated from Google Code issues [29](https://code.google.com/p/metadata-extractor/issues/detail?id=29) and [92](https://code.google.com/p/metadata-extractor/issues/detail?id=92))

**Comment by veita** [comment]
There's a regression in tags/2.8.1, and master (HEAD) .
```
git clone https://github.com/drewnoakes/metadata-extractor.git
cd metadata-extractor
mvn install
```
fails with
```
[INFO] BUILD FAILURE
...
Failed tests: testGimpGreyscaleWithManyChunks(com.drew.imaging.png.PngMetadataReaderTest):
  expected:<[Tue] Jan 01 04:08:30 GMT...> but was :<[Di] Jan 01 04:08:30 GMT...>
```

**Comment by veita** [comment]
To fix this issue you may replace in Tests/com/drew/imaging/png/PngMetadataReaderTest.java, line 102

```Java
 SimpleDateFormat formatter = new SimpleDateFormat("EE MMM DD HH:mm:ss z yyyy");
```
with
```Java
 SimpleDateFormat formatter = new SimpleDateFormat("EE MMM DD HH:mm:ss z yyyy", Locale.US);
```
Or use the culture-neutral standard time format for string comparisons
```Java
 formatter = new SimpleDateFormat("YYYY-MM-dd'T'HH:mm:ss'Z'");
 formatter.setTimeZone(TimeZone.getTimeZone("Etc/UTC"));
```
