### ISSUE TITLE
IPTC Credit Line is cut off when written with adobe bridge 

### ISSUE THREAD

**Issue by Starstrum** [drewnoakes/metadata-extractor#600]
When parsing through metadata written by adobe bridge the credit line gets cut off even thought the data is still there. I assume this isn't expected behavior, but I see the IIM specification for credit line on iptc.org is limited to 32 bytes https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#credit-line. 

With metadata written by other writers the full data will come through. I'll attach 2 images below the first one has metadata written with adobe bridge the second one has metadata written with gimp.

![jupiter-full-metadata](https://user-images.githubusercontent.com/46724866/211861170-0d350ac4-d771-4f83-bf33-a2def9fd6368.jpg)

![jupiter-full-metadata2](https://user-images.githubusercontent.com/46724866/211862506-2b2bd40d-ee64-4a74-be37-c78decc22fdc.jpg)

Edit: Here's some of the code being used to put the metadata into a map for more context

```
private void populateMetadata(Metadata metadata) {
        for (Iterator<?> di = metadata.getDirectories().iterator(); di.hasNext(); ) {
            Directory directory = (Directory) di.next();

            @SuppressWarnings("unchecked")
            Map<String, String> tags = (Map<String, String>) computeIfAbsent(
                directory.getName(),
                key -> new HashMap<>());

            for (Iterator<?> ti = directory.getTags().iterator(); ti.hasNext(); ) {
                Tag tag = (Tag) ti.next();

                try {
                    tags.put(tag.getTagName(), directory.getDescription(tag.getTagType()));
                } catch (Exception error) {
                    errors.add(error);
                }
            }
        }
    }
```

**Comment by paperboyo** [comment]
Check XMP’s photoshop:credit. It should have the whole thing (I haven’t, though). Bridge is correct to observe the limit when writing. See eg. [here](https://iptc.org/std/photometadata/specification/mapping/iptc-pmd-newsmlg2.html) for equivalency between (some) IPTC IIM and (some) XMP fields.

**Comment by Starstrum** [comment]
Awesome I see it now thank you

**Comment by drewnoakes** [comment]
@paperboyo thanks very much for your expertise here.

@Starstrum are you willing and able to share those images for our regression test suite in https://github.com/drewnoakes/metadata-extractor-images? It sounds like an edge case we may not yet have covered.

**Comment by Starstrum** [comment]
@drewnoakes I am is there an official process?

**Comment by drewnoakes** [comment]
@Starstrum thanks, no you don't have to do anything. I can add them. I just want to make sure you give permission for them to be used in that way.
