### ISSUE TITLE
Support AVIF / AV1 images

### ISSUE THREAD

**Issue by sunlei18** [drewnoakes/metadata-extractor#608]
Now the picture compression rate is relatively good av1, in the current are very popular, can support avif picture format and meta information analysis

**Comment by drewnoakes** [comment]
Could you provide a sample image to this repository please?

https://github.com/drewnoakes/metadata-extractor-images

Do you have any links to documentation about the file format specification?

**Comment by Noki** [comment]
@drewnoakes I just added a PR with a sample file: https://github.com/drewnoakes/metadata-extractor-images/pull/47

Would love to see AVIF supported!

**Comment by StefanOltmann** [comment]
@Noki Done. ;)
