### ISSUE TITLE
Question: Is it possible to read the EXIF data from a HEIC?

### ISSUE THREAD

**Issue by r-pf** [drewnoakes/metadata-extractor#631]
Is it possible to read/extract the EXIF data from a HEIC with the metadata extractor? I can't find it in the list of supported files.
If not: Is it intended to integrate it into the metadata extractor?

**Comment by anowak-ct** [comment]
I would love to have HEIC support as well ... It's the standard for (newer) iPhones, AFAIK

**Comment by StefanOltmann** [comment]
The .Net version supports this already. So I guess someone needs to port the code and send a PR.

**Comment by StefanOltmann** [comment]
Yes, it's supported and just missing in the list.

Just tested it with an HEIC file from an iPhone SE.

**Comment by drewnoakes** [comment]
This was implemented in https://github.com/drewnoakes/metadata-extractor/pull/478

**Comment by StefanOltmann** [comment]
Thanks, @drewnoakes!

I added HEIF-support to https://github.com/Ashampoo/kim based on your code.

However, I'm now reconsidering its inclusion. I'm concerned about potential patent-related issues with HEIF/HEIC.

I currently utilize my library (as well as your previous one) in a commercial application. Do I need to obtain a license to handle HEIC metadata parsing?

Is there a risk of legal consequences for incorporating the patented HEIC logic into our libraries? I'm hoping you can provide some guidance on this matter.
