### ISSUE TITLE
Support for AVIF format code completed but new Maven package not released

### ISSUE THREAD

**Issue by hdsuperman** [drewnoakes/metadata-extractor#664]
I am a user of your library, thank you for your great work, and I am delighted to notice that this library has already incorporated support for [AVIF format code](https://github.com/drewnoakes/metadata-extractor/pull/649), which is a significant update crucial for applications dealing with modern image formats.

However, I observed that a new maven package containing these changes has not been released yet. As a user, I am eagerly anticipating the release of this new version so that we can incorporate these functionalities into our projects.

**Comment by drewnoakes** [comment]
Thanks for your interest. There are a few other changes to go into the next release. I'll get it out Real Soon Now.
