### ISSUE TITLE
Sometimes XMP data tags change names

### ISSUE THREAD

**Issue by rdkgit** [drewnoakes/metadata-extractor#670]
Hi!

I'm analyzing some drone images and pulling out the exif metadata and xmp metadata using the java version of library, latest and greatest version.  I'm using maven to build from source.

Sometimes I'm finding the resulting tag names are for example:

Camera:Pitch
Camera_2_:Pitch
Camera_1_:Pitch

I can't pin down when/why the tag names sometimes change.   Sometimes when I build clean the resulting tags change until next clean build.

Any suggestions where to look to find/fix this?

Thanks,

Bobby

**Comment by rdkgit** [comment]
I should add that in my code, I first get the metadata from input stream.

this.md = ImageMetadataReader.readMetadata(new ByteArrayInputStream(imageData));

Then I retrieve all the metadata and put it into a HashMap<String,String> with tagName being the key.

**Comment by drewnoakes** [comment]
In XMP the tag names come from the data itself. Maybe your input files use different names.

**Comment by rdkgit** [comment]
I'll dig more through the XMP code.  Having a difficult time reproducing the issue.  Its somewhat random.

**Comment by drewnoakes** [comment]
I'll close this for now. If you discover a bug in the library we can revisit.
