### ISSUE TITLE
Expose API for file format detection

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor#68]
It would be useful to have the file format detection code be available for reuse in other situations.

**Comment by Odrahcyr** [comment]
GIFs are not recognized anymore. `GIF87a_MAGIC_NUMBER` is outside of the range of `six` according to FindBugs, so comparing them will always return false.

**Comment by drewnoakes** [comment]
Thanks, pushing up a fix shortly.

I'm going to rearrange the [image database](https://github.com/drewnoakes/metadata-extractor/wiki/ImageDatabase) a little to include some non camera/scanner captured images too, such as GIF, PNG, etc. That will catch more of these regression bugs.
