### ISSUE TITLE
Deploy 2.7.1 to Maven Central Repository

### ISSUE THREAD

**Issue by Yugge** [drewnoakes/metadata-extractor#69]
Hi! 

I need the fix in 2.7.1 in my Maven project and would greatly appreciate if you could deploy the code to Maven Central Repository. 

Thanks in advance!

**Comment by Odrahcyr** [comment]
Well, I don't think it is time to release 2.7.1 yet because the changes are quite small. I think we'll be able to release 2.7.1 in early February.

However I think we could deploy a 2.7.1-SNAPSHOT but only @drewnoakes has the permission to do that. By the way would just the jar be sufficient or does it really need to be deployed to Maven Central?

**Comment by drewnoakes** [comment]
@Yugge, there are currently [very few changes between 2.7.0 and master](https://github.com/drewnoakes/metadata-extractor/compare/2.7.0...master?w=1). Mostly they are code/documentation formatting.

What functionality is it that you require from master which is not in 2.7.0?

**Comment by Yugge** [comment]
@Odrahcyr We would much rather have the dependency external rather then including the jar file as the project (massive in size) would become hard to maintain if we start breaking our dependency standards. There is no plan on releasing before the March so we could probably wait . :)  

@drewnoakes When I wrote this, the only problem we seemed to have was #59 , but another problem came up regarding the IPTC Urgency tag. Apparently there are a lot press images (apparently as much as 3 out of 10) from back in 05' that contains what would be considered a faulty tag. I looked at one of the files in a hex editor and the urgency tag was 02 0A 00 00 1C and not 02 0A 00 01 30 1C as would be expected. I will open a issue regarding this issue. This however makes our need for the new version not as urgent.

**Comment by drewnoakes** [comment]
I'm happy to put together a 2.7.1 release that includes the regression #59 in v2.7.0. Please do submit an example of the other issue you're experiencing and there's a chance that a fix for that can be bundled in the release as well.

**Comment by Yugge** [comment]
@drewnoakes That is great news! I detailed the issue in #70. :)

**Comment by theefer** [comment]
+1 on releasing 2.7.1, we're currently preparing a large ingestion job and would be great to be able to upgrade to 2.7.* to fix the encoding issues but avoid the #59 regression.

Thanks!

**Comment by Odrahcyr** [comment]
@drewnoakes I think we should do #65 and #68 before releasing 2.7.1.

**Comment by drewnoakes** [comment]
I've made a start on #68. Will take a further look at that now and try to merge it in.

**Comment by drewnoakes** [comment]
#68 is done.

I think #65 will require an API change which would be better suited to a 2.8 or 3.0 release. If you can find a simpler approach to solving that issue then that'd be great.

At this point I think it makes sense to let some further testing occur on master and aim to release 2.7.1 this weekend.

**Comment by Odrahcyr** [comment]
@drewnoakes Could you test #28 with the JSOM patch? If the patch is working we could include #28 in 2.7.1

**Comment by drewnoakes** [comment]
A few more changes made today. Hopefully that's all for 2.7.1. Please run some tests and we'll aim to release on Sunday. Thanks all for the help.

**Comment by drewnoakes** [comment]
2.7.1 is now available via Maven:

http://search.maven.org/#artifactdetails%7Ccom.drewnoakes%7Cmetadata-extractor%7C2.7.1%7Cjar

GitHub release and tag to follow tomorrow.
