### ISSUE TITLE
ProcessTag (iptcreader) dies on (faulty?) urgency tag

### ISSUE THREAD

**Issue by Yugge** [drewnoakes/metadata-extractor#70]
When trying to extract metadata from the image below, `processTag` crashes with the following message:

```
Exception in thread "main" java.lang.IllegalArgumentException: n must be zero or greater.
	at com.drew.lang.SequentialByteArrayReader.skip(SequentialByteArrayReader.java:77)
	at com.drew.metadata.iptc.IptcReader.processTag(IptcReader.java:171)
```
exiftool reports the Urgency field as `unknown ()` which made me suspicious so I tried removing the tag, that made the image metadata extraction work.

Upon examining the hex of the metadata the urgency field was `02 0A 00 00 1C` compared to `02 0A 00 01 30 1C` which would be written if you set the tag to 0 (no urgency).

I first presumed this was just faulty metadata but apparently this is how it is like for 3 out of 10 official press images tried from 2005. Which makes me wonder if it is some kind of outdated standard?

If it is not and the metadata is indeed faulty, might there be possible to catch the problem and continue reading the rest of the metadata? It is critical for our users that any official press material would be extractable.

Image:
![458426](https://cloud.githubusercontent.com/assets/247807/5814797/ab61c8be-a08f-11e4-8ccf-ac50b4ff0bb0.JPG)

**Comment by drewnoakes** [comment]
In your image the IPTC data advertises a zero-length tag which then triggers an exception from new code that fixes a long-standing bug in IPTC character encoding.

I can't find anything in [the IPTC standard](https://raw.githubusercontent.com/wiki/drewnoakes/metadata-extractor/docs/IPTC-IIMV4.2.pdf) regarding zero-length tags, so for now I think we should just ignore them. It's simple enough to defend against the exception, and I'll push a fix for this shortly.

> [JpegComment] JPEG Comment = Generated by IJG JPEG Library

Are all the affected images generated by this software by any chance?

Could you test this fix on your images? If all's well, I'll get this out in 2.7.1 soon (as discussed in #69).

**Comment by Yugge** [comment]
This works, thanks a lot! :)

Yes, every faulty image was generated by IJG JPEG Library
