### ISSUE TITLE
Expose API to determine if tag is known or not

### ISSUE THREAD

**Issue by theefer** [drewnoakes/metadata-extractor#71]
I haven't found a way to determine whether a given Tag is "known" (i.e. corresponds to a registered mapping for that directory) or not. The closest thing seems to be [the code that generates the "Unknown tag..." string](https://github.com/drewnoakes/metadata-extractor/blob/master/Source/com/drew/metadata/Directory.java#L901), but that relies on `getTagNameMap()` which is protected.

So far the only way I've found is to string match tag names against "Unknown tag (0x...)", which is of course terrible.

Would it make sense to add a simple helper method on Directory or Tag to determine whether a given Tag is known or not?

**Comment by Odrahcyr** [comment]
You could use directory.getTags() to get a Collection of Tag objects and iterate over it while using the public methods of [Tag](https://github.com/drewnoakes/metadata-extractor/blob/master/Source/com/drew/metadata/Tag.java) to determine if a given tag is inside the collection.

**Comment by theefer** [comment]
We're currently using `directory.getTags()` to get a list of all tags (returns both known and unknown tags AFAICS). Which public method of Tag would you use to determine if it's known?

**Comment by drewnoakes** [comment]
By 'known', do you mean present in the image and `Directory`, or do you mean understood by the library?

**Comment by theefer** [comment]
By "known" I mean included in the set of registered and named tags (e.g. [for IPTC](https://github.com/drewnoakes/metadata-extractor/blob/master/Source/com/drew/metadata/iptc/IptcDirectory.java#L122)). I assume these correspond to standard tags from the spec, whereas anything else is outside the canonical standard?

**Comment by Odrahcyr** [comment]
In that case I think it would be sufficient to make `getTagNameMap` public and return a unmodifiable map. No reason to keep `getTagNameMap` protected imo.

**Comment by theefer** [comment]
That makes sense to me and would solve the problem.

**Comment by drewnoakes** [comment]
@theefer, is your use case that you wish to filter out tags that are not able to be decoded by a `Descriptor`? Are you just trying to remove all `"Unknown tag..."` text from your program's output? I'd like to understand your actual requirement in order to consider multiple potential solutions.

**Comment by theefer** [comment]
Sure.

I'm working on an image management system and I use the metadata-extractor library to extract all the file metadata (IPTC, EXIF, etc) into an ElasticSearch index. For each directory we're interested in, we call `directory.getTags()` and record all the tags in a Map that gets indexed (using `tag.getTagName()` as key and `tag.getDescription` as value).

That's working fine, but we also end up indexing a lot of "Unknown tag..." which we are not interested in and likely never will be, so we want to filter them out.

Does that help understand my use case?

**Comment by drewnoakes** [comment]
Yes that's great thanks. Would a `tag.hasName()` method be a convenient way to filter out `Unknown tag (0x..)` strings?

I'm taking your meaning of a 'known' tag to be that its name is known, not that its value is decodable.

**Comment by theefer** [comment]
That's right, and yes it would be.

**Comment by theefer** [comment]
Great, thanks!
