### ISSUE TITLE
JpegSegmentReader checkForBytesOnStream() should not rely on available()

### ISSUE THREAD

**Issue by tkrah** [drewnoakes/metadata-extractor#79]
The use of `inputStream.available()` is just a hint how much may be read without blocking. It's just a indication.
So you actually have to use read() to put the stream forward and not loop around this:

`bytesNeeded <= stream.available()`

because it may never change until you actually read something.
I got many valid jpeg files which are provided through a CipherInputStream which are failing here because available() won't change until you read().

Please change this check to use `read()` (or e.g. use a `PushBackInputStream` wrapper) - but imho available() won't do the job here.

**Comment by drewnoakes** [comment]
Thanks. Are you able to either provide a small code sample that reproduces this issue, or provide a PR?

**Comment by tkrah** [comment]
Got a sample ZIP-File here: https://mgmbox.mgm-tp.com/public.php?service=files&t=4e3ccc24988cc33ac675d75144033569

There is a JUnit Test attached with 2 methods. `testOK` just uses the plain `FileInputStream`, `testNotOk` first does encrypt it in memory and provides a `CipherInputStream` in DECRYPT mode which fails.

**Comment by drewnoakes** [comment]
@tkrah, what version of the library are you using? It seems that you're using an old version. Please try again with 2.7.1.

**Comment by tkrah** [comment]
I am sorry, used still 2.6.4. 2.7.1 seems to work fine now. Closed it.
