### ISSUE TITLE
Missing metadata from image

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor#80]
![Image](https://cloud.githubusercontent.com/assets/350947/5930366/776d3e56-a686-11e4-91a1-0d6d6bccbf21.jpg)

The above image was provided by Alan Pater:

> I am working on putting together some tools for a Camera Trap project
> in the Ecuadorian Amazon. One very promising tool is Wildbook, which
> uses your metadata-extractor.
>
> One branch I am following is the implementation of Darwin Core
> metadata as XMP to imbed in images. Frank Bungartz at the Charles
> Darwin Foundation has implemented DwC as XMP to imbed in images.
> Exiftool added support for that last year and I am working with the
> developers of exiv2 to add DwC support to that library.
> 
> Attached is a sample image with all the DwC XMP metadata. Would it be
> possible to test with this image to make sure no issues pop up?

Indeed metadata-extractor has some trouble with this image:

> ERROR: Attempt to read from beyond end of underlying data source (requested index: 282, requested count: 1980482, max index: 3161)

There are also many fewer tags extracted than achieved with `exiftool`, though I haven't yet researched why this is the case.

**Comment by Odrahcyr** [comment]
This issues seems related to #57

**Comment by drewnoakes** [comment]
@Odrahcyr well spotted. Indeed it does seem to be handled correctly since fixing 57. I'll push this image in the sample images repo shortly and xref here.

**Comment by drewnoakes** [comment]
Outstanding issues in the [decoded text](https://github.com/drewnoakes/metadata-extractor-images/blob/119774c964c67479d7b8c548954d4134d4157327/jpg/metadata/issue%2080.jpg.txt) are:

* `Windows XP Author` is junk (Ĳ*䵍)
* Many XMP fields are ignored. The file has 231, but only three are extracted.
