### ISSUE TITLE
Tag "Comments" using getUserCommentDescription method returns null.

### ISSUE THREAD

**Issue by Archdeacon** [drewnoakes/metadata-extractor#81]
String exif = "File: " + file;
    File jpgFile = new File(file);
    Metadata metadata = ImageMetadataReader.readMetadata(jpgFile);

    for (Directory directory : metadata.getDirectories()) {
         String directoryName = directory.getName();
         for (Tag tag : directory.getTags()) {
             String tagName = tag.getTagName();
             String description = tag.getDescription();
            if (tagName.toLowerCase().contains("comment")) {
                Log.d("DEBUG", description);    //Returns the    correct values.
            }
            exif += "\n " + tagName + ": " + description;  
            Log.d("DEBUG", directoryName + " " + tagName + " " + description);
    }
    ExifSubIFDDirectory exifDirectory = metadata.getDirectory(ExifSubIFDDirectory.class);
    ExifSubIFDDescriptor descriptor = new ExifSubIFDDescriptor(exifDirectory);
    String comment = descriptor.getUserCommentDescription();  // Always null.
    byte[] commentBytes = exifDirectory.getByteArray(ExifSubIFDDirectory.TAG_USER_COMMENT);

   
![dogs](https://cloud.githubusercontent.com/assets/10742402/5953197/27c01896-a7b8-11e4-8801-43c2f62a9970.jpg)
//byte[] array throws an exception so I assume also null. Please excuse lack of formatting as have never used this before!

**Comment by drewnoakes** [comment]
It seems that there is only one comment in this image, and that it's stored as the Windows XP comment:

    [Exif IFD0] Windows XP Comment = tosca luna

You should access this via:

    ExifIFD0Directory ifd0Directory = metadata.getDirectory(ExifIFD0Directory.class);
    ExifIFD0Descriptor ifd0Descriptor = new ExifIFD0Descriptor(ifd0Directory);
    String comment = ifd0Descriptor.getWindowsCommentDescription();

The `ExifSubIFDDirectory.TAG_USER_COMMENT` is certainly not present in this image.

The Windows XP comment is stored in UTF-16 too, so if you call `getString` on the directory directly, you will receive an unexpected string. Instead, use the descriptor class which knows how to decode this type of tag.

**Comment by drewnoakes** [comment]
I'm going to close this for now. Post a reply if this is still an issue for you.

**Comment by Archdeacon** [comment]
Drew,
Can I just ask a simple question about metadata-extractor: am I able 
to/write /these tags, at least the /Comment/s one? A while ago I wrote a 
VB.NET version for a Windows app which involved/byte-arrays/ and 
suchlike. I would hate to have to repeat this rigmarole if you have 
already done it.
Regards, Robin M.

-- 
   Click 'You Are Here' in the link below for Google Maps.
   The SeaStar site link: www.SeaStar.co.nf
                  (Mirror www.SeaStar.99k.org)
   The Bank demo link:    www.Lanham.99k.org
                  (Mirror www.Lanham.eu5.org)

**Comment by drewnoakes** [comment]
@Archdeacon it's not yet possible to write tags unfortunately. You can set values in a `Directory` object, but it's not possible to write them back to Exif data.

**Comment by Archdeacon** [comment]
Drew,
Just a quick one: is there any chance that /metadata-extractor /will be
able to _write_ tags? I am having problems doing this with the /Android
ExifInterface/ at present, especially the /UserComments /one.
Regards, Derf.

-- 
  Click 'You Are Here' in the link below for Google Maps.
  The SeaStar site link: www.SeaStar.co.nf 
                 (Mirror www.SeaStar.99k.org)
  The Bank demo link:    www.Lanham.99k.org  
                 (Mirror www.Lanham.eu5.org)

**Comment by Odrahcyr** [comment]
Yes, see issue #14

**Comment by drewnoakes** [comment]
@Archdeacon as Richard says, there's a separate issue for tracking that request. However I don't have any timeline for when such a feature might be added.
