### ISSUE TITLE
Support WebP image format

### ISSUE THREAD

**Issue by knight1128** [drewnoakes/metadata-extractor#85]
http://en.wikipedia.org/wiki/WebP

could you support for webp?

**Comment by drewnoakes** [comment]
I don't see why not.

The container format is RIFF:

https://developers.google.com/speed/webp/docs/riff_container

Some sample images at:

https://developers.google.com/speed/webp/gallery1
https://developers.google.com/speed/webp/gallery2

**Comment by drewnoakes** [comment]
It seems that Exif and ICC data are available in the `"EXIF"` and `"IPPC"` chunks respectively.

Other chunks may contain additional metadata such as image frame size:

* `"VP8 "` details are in the [VP8 Data Format RFC](http://tools.ietf.org/html/rfc6386)
* `"VP8L"` details are [here](https://gerrit.chromium.org/gerrit/gitweb?p=webm/libwebp.git;a=blob;f=doc/webp-lossless-bitstream-spec.txt;hb=master)
* `"VP8X"` details are [here](https://developers.google.com/speed/webp/docs/riff_container#extended_file_format)
* `"ANIM"` details are [here](https://developers.google.com/speed/webp/docs/riff_container#animation)

**Comment by drewnoakes** [comment]
@knight1128, please take a look and see if the code on master meets your expectations for WebP support.
