### ISSUE TITLE
Roadmap question

### ISSUE THREAD

**Issue by nathanaeljones** [drewnoakes/metadata-extractor#95]
We ported this to C#, but weren't aware of the GitHub repo, and ported https://code.google.com/p/metadata-extractor/source/detail?r=eb70b234529ae267c9ba72e9df68d9acb7e3504b

When the link appeared, I realized we needed to re-port the library. What version is the most stable, and you would recommend for porting? Is there an upcoming release we should wait for?

**Comment by drewnoakes** [comment]
The current master is very stable. It'll be released in the near future as v2.8.0 and whatever changes occur between now and then will only be minor.

Hopefully with the project now on GitHub it'll be easier for you to track its development.

**Comment by drewnoakes** [comment]
I suggest you [watch](https://github.com/drewnoakes/metadata-extractor/watchers) the project to be notified of changes as they happen.
