### ISSUE TITLE
Simple functionality now out-of-sync with documentation 

### ISSUE THREAD

**Issue by wbt** [drewnoakes/metadata-extractor#99]
The commit at https://github.com/drewnoakes/metadata-extractor/commit/372fe2944887727ab8910cbdddfc3d7cfc12de68#diff-5c46a03e89b3679809755db3b8de325cL111 breaks the example at https://github.com/drewnoakes/metadata-extractor/wiki/GettingStarted#query-the-raw-value-of-a-specific-tag by removing the method used there.  Options to rectify this include (a) fixing the code base for backward-compatibility so that when people upgrade to use a newer version of the library, their code won't break, or if that's not feasible (b) updating the documentation so that at least future uses will be easier :-).

Thanks for your work!

**Comment by drewnoakes** [comment]
Thanks for pointing this out. It's fixed now.

I believe the wiki is editable by any user, so feel free to modify the examples and text in whatever way you think makes them clearest.
